"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { BookOpen, CheckCircle2, Clock3, Dumbbell, FileText, Flame, GraduationCap, RotateCcw, Target, Trophy, LockKeyhole, BarChart3 } from "lucide-react";

type Q = { q:string; a:string[]; correct:number; why:string; topic:string };
type Attempt = { id:string; activity_type:string; topic:string|null; questions:number; correct:number; score:number; duration_seconds:number; created_at:string };

const quiz: Q[] = [
 {q:"If the price of an article increases from ₹400 to ₹460, what is the percentage increase?",a:["10%","12%","15%","20%"],correct:2,why:"Increase = ₹60. 60/400 × 100 = 15%.",topic:"Percentages"},
 {q:"A sum is divided in the ratio 3:5. If the total is 64, what is the smaller share?",a:["18","24","30","40"],correct:1,why:"Total parts = 8. One part = 8, so 3 × 8 = 24.",topic:"Ratio & Proportion"},
 {q:"Which topic is explicitly included in the 2026 SI PWT General Studies syllabus?",a:["Telangana Movement and State Formation","Computer programming","Commercial law","Organic chemistry only"],correct:0,why:"Telangana Movement and State Formation is explicitly included.",topic:"Telangana"},
 {q:"The 2026 SI Preliminary Written Test has how many questions and marks?",a:["100/100","150/150","200/200","250/250"],correct:2,why:"The official notification specifies 200 objective questions for 200 marks.",topic:"Exam Pattern"},
 {q:"For an OC/EWS candidate, the minimum qualifying percentage in the 2026 SI PWT is:",a:["20%","25%","30%","40%"],correct:2,why:"The official minimum is 30% for OC/EWS, 25% for BC and 20% for SC/ST/Ex-Servicemen.",topic:"Exam Pattern"},
 {q:"Which pair belongs to the Arithmetic portion of the PWT syllabus?",a:["Simple interest and time & work","Essay and précis","Ethics and emotional intelligence","Reading comprehension and vocabulary"],correct:0,why:"Simple interest and time & work are listed under Arithmetic.",topic:"Arithmetic"},
 {q:"The 2026 SI selection sequence begins with:",a:["Final Written Examination","Preliminary Written Test","Certificate Verification","Training"],correct:1,why:"The official sequence begins PWT, then PMT/PET, then FWE.",topic:"Exam Pattern"},
 {q:"In the PWT, marking multiple bubbles for one question receives full marks.",a:["True","False","Only GS","Only Arithmetic"],correct:1,why:"Full marks require the single correct bubble; other cases receive the stated negative treatment.",topic:"Exam Pattern"},
 {q:"Which Final Written paper contains ethics, gender sensitivity, social awareness and emotional intelligence?",a:["Paper I","Paper II","Paper III","Paper IV"],correct:3,why:"These personality-test areas are in Paper IV General Studies.",topic:"Final Written"},
 {q:"The PWT is conducted as one paper of what duration?",a:["90 minutes","2 hours","3 hours","4 hours"],correct:2,why:"The 2026 SI notification specifies a three-hour PWT.",topic:"Exam Pattern"}
];

const syllabus = [
 ["Arithmetic","Number system, SI/CI, ratio & proportion, averages, percentages, profit & loss, time & work, work & wages, time & distance, clocks/calendars, partnership and mensuration."],
 ["Reasoning / Mental Ability","Verbal and non-verbal reasoning, analogies, similarities/differences, spatial visualization/orientation, problem solving, analysis, judgment, decision making and visual memory."],
 ["General Science","Contemporary science and technology, everyday observation and experience, and environmental protection issues."],
 ["Current Affairs","National and international current events, refreshed from verified sources."],
 ["History & Geography","Indian history and national movement, geography principles and geography of India."],
 ["Polity & Economy","Indian political system, rural development, planning and economic reforms."],
 ["Telangana","Telangana Movement and State Formation: 1948–1970, 1971–1990 and 1991–2014."],
 ["Final Written","English; Telugu/Urdu; Arithmetic & Reasoning; General Studies including personality-test topics."]
];

const plan = [["Learn","Concept from basics → standard method → shortcut → examples."],["Practice","Topic-wise questions with increasing difficulty and timed practice."],["Daily Quiz","Fresh questions with answer-specific explanations."],["Previous-paper model","Original questions matching official structure without copying papers."],["Mock Exam","Timed full-length simulations using the current official model."],["Weakness Engine","Every mistake is tagged to a topic and fed into revision."],["Revision","Spaced review of weak topics and missed questions."],["Physical Prep","Run/PET preparation alongside written preparation."]];

function daysLeft(date:string|null){ if(!date) return null; return Math.max(0,Math.ceil((new Date(`${date}T23:59:59`).getTime()-Date.now())/86400000)); }

export default function StudyPage(){
 const supabase=createClient();
 const [user,setUser]=useState<{id:string;email?:string}|null>(null);
 const [loading,setLoading]=useState(true); const [tab,setTab]=useState("today"); const [target,setTarget]=useState<any>(null); const [attempts,setAttempts]=useState<Attempt[]>([]); const [mistakes,setMistakes]=useState<any[]>([]); const [answers,setAnswers]=useState<Record<number,number>>({}); const [showResults,setShowResults]=useState(false); const [saving,setSaving]=useState(false);
 const [examType,setExamType]=useState("si"); const [targetDate,setTargetDate]=useState(""); const [dailyMinutes,setDailyMinutes]=useState(120); const [message,setMessage]=useState("");

 async function load(){
   setLoading(true); const {data:{user:u}}=await supabase.auth.getUser();
   if(!u){setUser(null);setLoading(false);return;} setUser({id:u.id,email:u.email});
   const [t,a,m]=await Promise.all([
    supabase.from("study_targets").select("*").eq("user_id",u.id).maybeSingle(),
    supabase.from("study_attempts").select("id,activity_type,topic,questions,correct,score,duration_seconds,created_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(200),
    supabase.from("study_mistakes").select("id,topic,question,explanation,created_at,resolved_at").eq("user_id",u.id).is("resolved_at",null).order("created_at",{ascending:false}).limit(100)
   ]); setTarget(t.data); setAttempts(a.data??[]); setMistakes(m.data??[]);
   if(t.data){setExamType(t.data.exam_type);setTargetDate(t.data.target_date??"");setDailyMinutes(t.data.daily_minutes??120);} setLoading(false);
 }
 useEffect(()=>{load(); const {data:l}=supabase.auth.onAuthStateChange(()=>load()); return ()=>l.subscription.unsubscribe();},[]);

 const score=useMemo(()=>quiz.reduce((n,x,i)=>n+(answers[i]===x.correct?1:0),0),[answers]);
 const recent=useMemo(()=>attempts.filter(a=>Date.now()-new Date(a.created_at).getTime()<3600000),[attempts]);
 const overall=useMemo(()=>{const q=attempts.reduce((n,a)=>n+a.questions,0),c=attempts.reduce((n,a)=>n+a.correct,0);return q?Math.round(c/q*100):0},[attempts]);
 const topicStats=useMemo(()=>{const m=new Map<string,{q:number;c:number}>();attempts.forEach(a=>{if(!a.topic)return;const x=m.get(a.topic)||{q:0,c:0};x.q+=a.questions;x.c+=a.correct;m.set(a.topic,x)});return [...m.entries()].map(([topic,x])=>({topic,accuracy:x.q?Math.round(x.c/x.q*100):0,questions:x.q})).sort((a,b)=>a.accuracy-b.accuracy)},[attempts]);
 const gaps=useMemo(()=>{const fromMistakes=mistakes.reduce((m,x)=>m.set(x.topic,(m.get(x.topic)||0)+1),new Map<string,number>()); return [...fromMistakes.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5)},[mistakes]);

 async function saveTarget(){if(!user)return;setSaving(true);setMessage("");const {error}=await supabase.from("study_targets").upsert({user_id:user.id,exam_type:examType,target_date:targetDate||null,daily_minutes:dailyMinutes},{onConflict:"user_id"});setSaving(false);setMessage(error?error.message:"Target saved. Your plan is now personal to this account.");await load();}
 async function finishQuiz(){if(!user||Object.keys(answers).length<quiz.length){setMessage("Answer all 10 questions before finishing.");return;}setSaving(true);const correct=score;const {data:attempt,error}=await supabase.from("study_attempts").insert({user_id:user.id,target_type:examType,activity_type:"quiz",topic:"Mixed PWT",questions:10,correct,score:correct,duration_seconds:0,metadata:{source:"daily_quiz",questions:quiz.map(q=>q.topic)}}).select("id").single();if(!error&&attempt){const wrong=quiz.map((q,i)=>({q,i})).filter(x=>answers[x.i]!==x.q.correct);if(wrong.length)await supabase.from("study_mistakes").insert(wrong.map(x=>({user_id:user.id,attempt_id:attempt.id,topic:x.q.topic,question:x.q.q,explanation:x.q.why})));}setSaving(false);setShowResults(true);await load();}

 if(loading)return <main className="min-h-screen grid place-items-center bg-white text-black"><p className="font-black">Loading your private study dashboard…</p></main>;
 if(!user)return <main className="min-h-screen bg-white text-black"><div className="mx-auto flex min-h-[70vh] max-w-xl flex-col items-center justify-center px-6 text-center"><div className="grid size-16 place-items-center rounded-2xl bg-black text-white"><LockKeyhole/></div><h1 className="mt-6 text-4xl font-black tracking-tight">Your Police Prep is private.</h1><p className="mt-4 text-sm leading-7 text-black/55">Login to create your personal SI/Constable target, save every attempt, build your scorecard and let the gap engine adapt your preparation.</p><a href="/login" className="mt-7 rounded-xl bg-black px-6 py-3 text-sm font-black text-white">Login / Sign up</a></div></main>;

 return <main className="min-h-screen bg-white text-black">
  <section className="border-b border-black/10 bg-black text-white"><div className="mx-auto max-w-7xl px-4 py-9 sm:px-6 lg:px-8"><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.2em] text-white/55"><GraduationCap size={16}/> TargetBud Study · Private</div><div className="mt-3 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><h1 className="text-4xl font-black tracking-[-.04em] sm:text-6xl">Your Police Prep Command Center.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/60">Target → learn → practice → assess → find gaps → revise → repeat. Your scores and mistakes belong to your account.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Overall",`${overall}%`],["Questions",attempts.reduce((n,a)=>n+a.questions,0)],["1h score",recent.reduce((n,a)=>n+a.correct,0)+" correct"],["Gaps",mistakes.length]].map(([a,b])=><div key={a} className="rounded-xl border border-white/15 bg-white/5 p-3"><p className="text-[10px] uppercase tracking-wider text-white/40">{a}</p><p className="mt-1 text-lg font-black">{b}</p></div>)}</div></div></div></section>
  <nav className="sticky top-14 z-30 border-b border-black/10 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 py-2 sm:px-6 lg:px-8">{[["today","Dashboard"],["target","My Target"],["syllabus","Syllabus"],["learn","Learn"],["quiz","Daily Quiz"],["mock","Mock"],["revision","Gaps & Revision"],["physical","Physical"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-black ${tab===id?"bg-black text-white":"text-black/55 hover:bg-black/[.05]"}`}>{label}</button>)}</div></nav>
  <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
   {tab==="today"&&<div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-black/10 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-black/40">Hourly assessment</p><h2 className="mt-2 text-3xl font-black">Where you stand right now</h2></div><BarChart3/></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><p className="text-xs text-black/45">Target</p><p className="mt-2 text-xl font-black">{examType.toUpperCase()}</p><p className="mt-1 text-xs text-black/45">{targetDate?`${daysLeft(targetDate)} days left`:"Set a target date"}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-black/45">Last hour</p><p className="mt-2 text-xl font-black">{recent.reduce((n,a)=>n+a.questions,0)} Q</p><p className="mt-1 text-xs text-black/45">{recent.length?Math.round(recent.reduce((n,a)=>n+a.correct,0)/Math.max(1,recent.reduce((n,a)=>n+a.questions,0))*100)+"% accuracy":"No attempt yet"}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-black/45">Top gap</p><p className="mt-2 text-xl font-black">{gaps[0]?.[0]??"Not enough data"}</p><p className="mt-1 text-xs text-black/45">{gaps[0]?`${gaps[0][1]} missed items`:"Take the quiz"}</p></div></div><div className="mt-6 rounded-xl bg-black/[.04] p-5"><p className="text-xs font-black uppercase tracking-wider text-black/40">Next best action</p><p className="mt-2 text-lg font-black">{gaps[0]?`Revise ${gaps[0][0]} and take a 10-question targeted set.`:"Take today's diagnostic quiz so TargetBud can identify your first gaps."}</p><button onClick={()=>setTab(gaps[0]?"revision":"quiz")} className="mt-4 rounded-xl bg-black px-4 py-2.5 text-xs font-black text-white">{gaps[0]?"Work on gap →":"Start assessment →"}</button></div></div><div className="rounded-2xl border border-black/10 p-6"><Target/><h2 className="mt-4 text-xl font-black">Your target</h2><p className="mt-2 text-sm leading-6 text-black/55">{target?`${examType.toUpperCase()} · ${dailyMinutes} minutes/day`:"Set your exam target and daily capacity."}</p><button onClick={()=>setTab("target")} className="mt-5 w-full rounded-xl bg-black px-4 py-3 text-xs font-black text-white">Manage target</button><div className="mt-5 border-t pt-5"><p className="text-xs font-black uppercase tracking-wider text-black/40">Hourly loop</p><p className="mt-2 text-sm leading-6 text-black/55">Every hour: assess activity → calculate accuracy/speed → identify gaps → recommend the next task. No activity means no fabricated score.</p></div></div></div>}

   {tab==="target"&&<div className="mx-auto max-w-3xl"><p className="text-[11px] font-black uppercase tracking-[.2em] text-black/40">Personal target</p><h2 className="mt-2 text-3xl font-black">Prepare against a target, not a timetable.</h2><p className="mt-3 text-sm leading-6 text-black/55">TargetBud uses this target to shape the daily workload and later the mock/revision cadence.</p><div className="mt-6 space-y-4 rounded-2xl border p-6"><label className="block text-sm font-black">Target exam<select value={examType} onChange={e=>setExamType(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"><option value="si">SI</option><option value="constable">Constable</option><option value="both">Both</option></select></label><label className="block text-sm font-black">Personal target date<input type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label className="block text-sm font-black">Daily study minutes<input type="number" min={30} max={600} step={15} value={dailyMinutes} onChange={e=>setDailyMinutes(Number(e.target.value))} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><button disabled={saving} onClick={saveTarget} className="rounded-xl bg-black px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving?"Saving…":"Save my target"}</button>{message&&<p className="text-sm font-bold">{message}</p>}</div></div>}

   {tab==="syllabus"&&<div><p className="text-[11px] font-black uppercase tracking-[.2em] text-black/40">Official 2026 syllabus map</p><h2 className="mt-2 text-3xl font-black">Everything we track</h2><div className="mt-6 grid gap-3 md:grid-cols-2">{syllabus.map(([a,b])=><article key={a} className="rounded-2xl border p-5"><h3 className="font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-black/55">{b}</p></article>)}</div></div>}

   {tab==="learn"&&<div className="grid gap-4 lg:grid-cols-3">{[["Percentages","Formula first → standard method → shortcut → practice","15 min"],["Number System","Factors, multiples, divisibility and remainder thinking","20 min"],["Reasoning","Pattern recognition before speed shortcuts","20 min"],["Telangana Movement","Timeline + causes + milestones + revision questions","25 min"],["Indian Polity","Concept → example → MCQ → mistake review","25 min"],["Current Affairs","Verified facts → why it matters → quiz","20 min"]].map(([a,b,c])=><article key={a} className="rounded-2xl border p-5"><BookOpen/><h3 className="mt-5 text-lg font-black">{a}</h3><p className="mt-2 text-sm leading-6 text-black/55">{b}</p><span className="mt-4 inline-flex rounded-full bg-black/[.05] px-3 py-1 text-xs font-bold">{c}</span></article>)}</div>}

   {tab==="quiz"&&<div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] font-black uppercase tracking-[.2em] text-black/40">Daily Quiz</p><h2 className="mt-2 text-3xl font-black">10 questions · diagnostic</h2></div><span className="rounded-full bg-black px-3 py-1.5 text-xs font-black text-white">{Object.keys(answers).length}/10</span></div><div className="mt-6 space-y-4">{quiz.map((x,i)=><article key={i} className="rounded-2xl border p-5"><div className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-black text-xs font-black text-white">{i+1}</span><div className="flex-1"><p className="text-xs font-black uppercase tracking-wider text-black/35">{x.topic}</p><h3 className="mt-1 font-black leading-6">{x.q}</h3><div className="mt-4 grid gap-2 sm:grid-cols-2">{x.a.map((o,j)=><button key={o} onClick={()=>{setAnswers(v=>({...v,[i]:j}));setShowResults(false)}} className={`rounded-xl border px-4 py-3 text-left text-sm font-bold ${answers[i]===j?"border-black bg-black text-white":"border-black/10 hover:border-black/30"}`}>{o}</button>)}</div>{showResults&&<div className="mt-4 rounded-xl bg-black/[.04] p-4 text-sm leading-6"><b>{answers[i]===x.correct?"Correct":"Review"}.</b> {x.why}</div>}</div></div></article>)}</div><button disabled={saving} onClick={finishQuiz} className="mt-6 rounded-xl bg-black px-5 py-3 text-sm font-black text-white disabled:opacity-50">{saving?"Saving…":"Finish, score & save"}</button>{showResults&&<button onClick={()=>{setAnswers({});setShowResults(false)}} className="ml-2 rounded-xl border px-5 py-3 text-sm font-black"><RotateCcw size={15} className="mr-2 inline"/>Retry</button>}{showResults&&<p className="mt-4 text-lg font-black">Score: {score}/10 · {score*10}%</p>}</div>}

   {tab==="mock"&&<div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border p-6"><FileText/><h2 className="mt-5 text-2xl font-black">PWT full mock</h2><p className="mt-2 text-sm leading-6 text-black/55">200 objective questions · 200 marks · 3 hours. Official model: 100 Arithmetic & Reasoning/Mental Ability + 100 General Studies. Negative marking is applied according to the notification.</p><div className="mt-5 rounded-xl bg-black/[.04] p-4 text-sm font-bold">Full mock engine is the next expansion: timer, section mix, negative marking, topic analytics and post-mock gap plan.</div></div><div className="rounded-2xl border p-6"><Trophy/><h2 className="mt-5 text-2xl font-black">Previous-paper model</h2><p className="mt-2 text-sm leading-6 text-black/55">Original questions will reproduce the skill mix, difficulty progression, timing pressure and topic distribution without republishing copyrighted papers.</p></div></div>}

   {tab==="revision"&&<div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="rounded-2xl border p-6"><RotateCcw/><h2 className="mt-5 text-2xl font-black">Your current gaps</h2>{gaps.length?<div className="mt-5 space-y-2">{gaps.map(([t,n])=><div key={t} className="flex items-center justify-between rounded-xl border p-4"><span className="font-black">{t}</span><span className="rounded-full bg-black px-3 py-1 text-xs font-black text-white">{n} misses</span></div>)}</div>:<p className="mt-4 text-sm leading-6 text-black/55">No gap history yet. Complete the diagnostic quiz and future attempts will populate this automatically.</p>}</div><div className="rounded-2xl border p-6"><BarChart3/><h2 className="mt-5 text-2xl font-black">Topic accuracy</h2><div className="mt-5 space-y-3">{topicStats.length?topicStats.slice(0,8).map(x=><div key={x.topic}><div className="flex justify-between text-sm font-bold"><span>{x.topic}</span><span>{x.accuracy}%</span></div><div className="mt-1 h-2 rounded-full bg-black/10"><div className="h-2 rounded-full bg-black" style={{width:`${x.accuracy}%`}}/></div></div>):<p className="text-sm text-black/55">Complete assessments to build your topic profile.</p>}</div></div></div>}

   {tab==="physical"&&<div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border p-6"><Dumbbell/><h2 className="mt-5 text-2xl font-black">Physical preparation</h2><p className="mt-2 text-sm leading-6 text-black/55">Track your run sessions, distance, time and consistency alongside written preparation. Targets are kept separate for post-specific requirements.</p><button onClick={()=>setMessage("Physical logging is connected to the same private account model; detailed run logs are the next tracker expansion.")} className="mt-5 rounded-xl bg-black px-4 py-3 text-xs font-black text-white">Log today's session</button></div><div className="rounded-2xl border p-6"><Clock3/><h2 className="mt-5 text-2xl font-black">Your routine</h2><p className="mt-2 text-sm leading-6 text-black/55">Use your {dailyMinutes}-minute daily capacity for written work, plus a separate physical session. The scheduler will remind you without inventing completion.</p></div></div>}
  </section>
 </main>;
}