const SUPABASE_URL='https://zfcreqiioyfgrrgshdqu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_3n4waPJXVlvrodlJso8sdw_y_m--gMB';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=id=>document.getElementById(id);
const loans=[['₹10L','2% / month','₹20,000','4 / 12 months'],['₹6L','2.5% / month','₹15,000','2 / 6 months'],['₹5L','2.5% / month','₹12,500','Start date TBD'],['₹6L','0% until 1 Jan 2027','₹0','Due 1 Jan 2027']];
$('loans').innerHTML=loans.map(x=>`<div class="loan"><div class="loan-line"><span>${x[0]}</span><span>${x[2]}</span></div><div class="loan-sub">${x[1]} · ${x[3]}</div></div>`).join('');
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const esc=s=>String(s).replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function msg(t,error=false){$('authMsg').textContent=t;$('authMsg').style.color=error?'#dc2626':'#167342'}
async function signIn(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return msg('Enter email and password.',true);const {error}=await db.auth.signInWithPassword({email,password});if(error)msg(error.message,true)}
async function signUp(){const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return msg('Enter email and password.',true);if(password.length<6)return msg('Password must be at least 6 characters.',true);const {error}=await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(error)msg(error.message,true);else msg('Account created. Check your email if confirmation is required.')}
async function loadEod(){const {data,error}=await db.from('eod_entries').select('id,entry_date,category,amount,note').order('entry_date',{ascending:false}).order('created_at',{ascending:false});if(error){$('eodList').textContent='Could not load EOD entries: '+error.message;return}const rows=data||[];$('eodList').innerHTML=rows.length?rows.map(x=>`<div><b>${x.entry_date}</b> · ${esc(x.category)} · ₹${Number(x.amount).toLocaleString('en-IN')}${x.note?` · ${esc(x.note)}`:''}</div>`).join(''):'No entries yet. Add today’s EOD spending.';const done=rows.some(x=>x.entry_date===today());$('eodDate').value=today();$('todayStatus').textContent=done?'DONE':'TODO';$('todayStatus').className='tag '+(done?'good':'warn')}
$('signIn').onclick=signIn;$('signUp').onclick=signUp;$('password').onkeydown=e=>{if(e.key==='Enter')signIn()};$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
$('addEod').onclick=async()=>{const date=$('eodDate').value||today(),category=$('eodCat').value,amount=Number($('eodAmount').value||0),note=$('eodNote').value.trim();if(category!=='No Spend'&&amount<=0)return;if(category==='No Spend'&&amount!==0)return;const {data:{user}}=await db.auth.getUser();if(!user)return;const {error}=await db.from('eod_entries').insert({user_id:user.id,entry_date:date,category,amount,note:note||null});if(error)return alert(error.message);$('eodAmount').value='';$('eodNote').value='';await loadEod()};
async function showApp(){$('auth').classList.add('hidden');$('app').classList.remove('hidden');await loadEod()}
async function boot(){const {data:{session}}=await db.auth.getSession();if(session)await showApp();else $('eodDate').value=today()}
db.auth.onAuthStateChange((event,session)=>{if(session)showApp();else if(event==='SIGNED_OUT'){$('app').classList.add('hidden');$('auth').classList.remove('hidden')}});boot();