"use client";
import Link from "next/link";
import { cloneElement, type FormEvent, type ReactElement, type ReactNode, useEffect, useState } from "react";
import { ArrowLeft, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";
type Loan={id:string;name:string;principal:number;monthly_rate:number;monthly_interest:number;maturity_date:string|null;status:string};
type Form={name:string;principal:string;monthly_rate:string;monthly_interest:string;maturity_date:string;status:string};
const empty=():Form=>({name:"",principal:"",monthly_rate:"",monthly_interest:"",maturity_date:"",status:"active"});
const money=(v:number)=>`₹${Math.round(Number(v)||0).toLocaleString("en-IN")}`;
export default function LoansPage(){const [items,setItems]=useState<Loan[]>([]),[form,setForm]=useState<Form>(empty()),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){setItems([]);setLoading(false);return}const {data,error}=await s.from("loan_accounts").select("*").eq("user_id",user.id).order("created_at",{ascending:false});if(error)setError(error.message);setItems((data??[]) as Loan[]);setLoading(false)} useEffect(()=>{load()},[]);
 function edit(x:Loan){setEditing(x.id);setForm({name:x.name,principal:String(x.principal),monthly_rate:String(x.monthly_rate),monthly_interest:String(x.monthly_interest),maturity_date:x.maturity_date??"",status:x.status})} function reset(){setEditing(null);setForm(empty())}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){setError("Please sign in.");setSaving(false);return}const payload={user_id:user.id,name:form.name.trim(),principal:Number(form.principal)||0,monthly_rate:Number(form.monthly_rate)||0,monthly_interest:Number(form.monthly_interest)||0,maturity_date:form.maturity_date||null,status:form.status};const q=editing?s.from("loan_accounts").update(payload).eq("id",editing).eq("user_id",user.id).select().single():s.from("loan_accounts").insert(payload).select().single();const {data,error}=await q;if(error)setError(error.message);else{if(editing)setItems(p=>p.map(x=>x.id===editing?data as Loan:x));else setItems(p=>[data as Loan,...p]);reset()}setSaving(false)}
 async function remove(id:string){if(!confirm("Delete this loan?"))return;const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from("loan_accounts").delete().eq("id",id).eq("user_id",user.id);if(error)setError(error.message);else setItems(p=>p.filter(x=>x.id!==id))}
 const principal=items.reduce((s,x)=>s+Number(x.principal||0),0),interest=items.reduce((s,x)=>s+Number(x.monthly_interest||0),0);
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading loans…</main>;
 return <main className="min-h-screen bg-slate-50 px-3 py-5 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/goal" className="inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-bold ring-1 ring-slate-200"><ArrowLeft size={16}/>Finance</Link><b>Loans</b><button onClick={load} className="rounded-xl bg-white p-2.5 ring-1 ring-slate-200"><RefreshCw size={16}/></button></header>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}
 <section className="mt-5 grid gap-3 sm:grid-cols-3"><K l="Loan accounts" v={String(items.length)}/><K l="Principal outstanding" v={money(principal)}/><K l="Monthly interest recorded" v={money(interest)}/></section>
 <section className="mt-5 grid gap-5 lg:grid-cols-[360px_1fr]"><form onSubmit={save} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between"><div><p className="text-xs font-black tracking-[.16em] text-violet-600">{editing?"EDIT":"ADD"}</p><h1 className="mt-1 text-xl font-black">{editing?"Edit loan":"Add loan"}</h1></div>{editing&&<button type="button" onClick={reset}><X size={18}/></button>}</div><F l="Loan name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></F><F l="Principal outstanding"><input required type="number" min="0" value={form.principal} onChange={e=>setForm({...form,principal:e.target.value})}/></F><F l="Monthly rate %"><input type="number" min="0" step="0.001" value={form.monthly_rate} onChange={e=>setForm({...form,monthly_rate:e.target.value})}/></F><F l="Monthly interest"><input type="number" min="0" value={form.monthly_interest} onChange={e=>setForm({...form,monthly_interest:e.target.value})}/></F><F l="Maturity date"><input type="date" value={form.maturity_date} onChange={e=>setForm({...form,maturity_date:e.target.value})}/></F><F l="Status"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>active</option><option>closed</option><option>paused</option></select></F><button disabled={saving} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white"><Plus size={17}/>{saving?"Saving…":editing?"Save changes":"Add loan"}</button></form>
 <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-black">Your loans</h2><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Loan</th><th className="px-4 py-3">Principal</th><th className="px-4 py-3">Rate</th><th className="px-4 py-3">Interest/month</th><th className="px-4 py-3">Maturity</th><th className="px-4 py-3">Status</th><th></th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(x=><tr key={x.id}><td className="px-4 py-3 font-bold">{x.name}</td><td className="px-4 py-3">{money(x.principal)}</td><td className="px-4 py-3">{x.monthly_rate}%</td><td className="px-4 py-3">{money(x.monthly_interest)}</td><td className="px-4 py-3">{x.maturity_date||"—"}</td><td className="px-4 py-3">{x.status}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button onClick={()=>edit(x)} className="rounded-lg p-2 hover:bg-slate-100"><Pencil size={16}/></button><button onClick={()=>remove(x.id)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50"><Trash2 size={16}/></button></div></td></tr>)}{!items.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No loans recorded. Add one to make loan totals part of Finance.</td></tr>}</tbody></table></div></section></section></div></main>}
function F({l,children}:{l:string;children:ReactNode}){return <label className="mt-3 block text-xs font-bold">{l}{cloneElement(children as ReactElement<any>,{className:"mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none"})}</label>} function K({l,v}:{l:string;v:string}){return <div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-[10px] uppercase tracking-wider text-slate-400">{l}</p><p className="mt-1 text-xl font-black">{v}</p></div>}
