"use client";
import Link from "next/link";
import { cloneElement, type FormEvent, type ReactElement, type ReactNode, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Pencil, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Investment={id:string;name:string;investment_type:string;principal_amount:number;expected_rate:number;rate_period:"Monthly"|"Yearly";invested_on:string;maturity_on:string|null;monthly_addition:number;current_value:number|null;contribution_type:"Monthly"|"On maturity";funding_source:"Salary"|"Other";expected_maturity_amount:number|null};
type Form={name:string;investment_type:string;principal_amount:string;expected_rate:string;rate_period:"Monthly"|"Yearly";invested_on:string;maturity_on:string;monthly_addition:string;current_value:string;contribution_type:"Monthly"|"On maturity";funding_source:"Salary"|"Other";expected_maturity_amount:string};
const types=["FD","RD","SIP","Mutual Fund","PPF","Stocks","Gold","Other"];
const empty=():Form=>({name:"",investment_type:"FD",principal_amount:"",expected_rate:"",rate_period:"Yearly",invested_on:new Date().toISOString().slice(0,10),maturity_on:"",monthly_addition:"",current_value:"",contribution_type:"Monthly",funding_source:"Salary",expected_maturity_amount:""});
const money=(v:number)=>`₹${Math.round(Number(v)||0).toLocaleString("en-IN")}`;
export default function InvestmentsPage(){
 const [items,setItems]=useState<Investment[]>([]),[form,setForm]=useState<Form>(empty()),[editing,setEditing]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){setItems([]);setLoading(false);return}const {data,error}=await s.from("goal_investments").select("*").eq("user_id",user.id).order("invested_on",{ascending:false});if(error)setError(error.message);setItems((data??[]) as Investment[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const total=useMemo(()=>items.reduce((s,i)=>s+Number(i.current_value??i.principal_amount??0),0),[items]);
 function startEdit(i:Investment){setEditing(i.id);setForm({name:i.name,investment_type:i.investment_type,principal_amount:String(i.principal_amount??""),expected_rate:String(i.expected_rate??""),rate_period:i.rate_period,invested_on:i.invested_on,maturity_on:i.maturity_on??"",monthly_addition:String(i.monthly_addition??""),current_value:i.current_value==null?"":String(i.current_value),contribution_type:i.contribution_type,funding_source:i.funding_source,expected_maturity_amount:i.expected_maturity_amount==null?"":String(i.expected_maturity_amount)})}
 function reset(){setEditing(null);setForm(empty())}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){setError("Please sign in.");setSaving(false);return}const payload={user_id:user.id,name:form.name.trim(),investment_type:form.investment_type,principal_amount:Number(form.principal_amount)||0,expected_rate:Number(form.expected_rate)||0,rate_period:form.rate_period,invested_on:form.invested_on,maturity_on:form.maturity_on||null,monthly_addition:Number(form.monthly_addition)||0,current_value:form.current_value===""?null:Number(form.current_value),contribution_type:form.contribution_type,funding_source:form.funding_source,expected_maturity_amount:form.expected_maturity_amount===""?null:Number(form.expected_maturity_amount)};const q=editing?s.from("goal_investments").update(payload).eq("id",editing).eq("user_id",user.id).select().single():s.from("goal_investments").insert(payload).select().single();const {data,error}=await q;if(error)setError(error.message);else{if(editing)setItems(p=>p.map(x=>x.id===editing?data as Investment:x));else setItems(p=>[data as Investment,...p]);reset()}setSaving(false)}
 async function remove(id:string){if(!confirm("Delete this investment?"))return;const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user)return;const {error}=await s.from("goal_investments").delete().eq("id",id).eq("user_id",user.id);if(error)setError(error.message);else setItems(p=>p.filter(x=>x.id!==id))}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading investments…</main>;
 return <main className="min-h-screen bg-slate-50 px-3 py-5 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl">
  <header className="flex items-center justify-between gap-3"><Link href="/goal" className="inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-bold ring-1 ring-slate-200"><ArrowLeft size={16}/>Finance</Link><div className="flex items-center gap-2"><b>Investments</b><button onClick={load} className="rounded-xl bg-white p-2.5 ring-1 ring-slate-200"><RefreshCw size={16}/></button></div><Link href="/goal/activity" className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Manage cash flow</Link></header>
  {error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}
  <section className="mt-5 grid gap-3 sm:grid-cols-3"><K label="Investments" v={String(items.length)}/><K label="Recorded value" v={money(total)}/><K label="Monthly additions" v={money(items.reduce((s,i)=>s+Number(i.monthly_addition||0),0))}/></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-[390px_1fr]"><form onSubmit={save} className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[.16em] text-violet-600">{editing?"EDIT":"ADD"}</p><h1 className="mt-1 text-xl font-black">{editing?"Edit investment":"Add investment"}</h1></div>{editing&&<button type="button" onClick={reset}><X size={18}/></button>}</div>
  <Field label="Name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>
  <Field label="Type"><select value={form.investment_type} onChange={e=>setForm({...form,investment_type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></Field>
  <Field label="Principal"><input required type="number" min="0" value={form.principal_amount} onChange={e=>setForm({...form,principal_amount:e.target.value})}/></Field>
  <div className="grid grid-cols-2 gap-3"><Field label="Rate %"><input type="number" min="0" step="0.01" value={form.expected_rate} onChange={e=>setForm({...form,expected_rate:e.target.value})}/></Field><Field label="Rate period"><select value={form.rate_period} onChange={e=>setForm({...form,rate_period:e.target.value as any})}><option>Yearly</option><option>Monthly</option></select></Field></div>
  <div className="grid grid-cols-2 gap-3"><Field label="Invested on"><input type="date" required value={form.invested_on} onChange={e=>setForm({...form,invested_on:e.target.value})}/></Field><Field label="Maturity"><input type="date" value={form.maturity_on} onChange={e=>setForm({...form,maturity_on:e.target.value})}/></Field></div>
  <div className="grid grid-cols-2 gap-3"><Field label="Monthly addition"><input type="number" min="0" value={form.monthly_addition} onChange={e=>setForm({...form,monthly_addition:e.target.value})}/></Field><Field label="Current value"><input type="number" min="0" value={form.current_value} onChange={e=>setForm({...form,current_value:e.target.value})}/></Field></div>
  <div className="grid grid-cols-2 gap-3"><Field label="Contribution"><select value={form.contribution_type} onChange={e=>setForm({...form,contribution_type:e.target.value as any})}><option>Monthly</option><option>On maturity</option></select></Field><Field label="Funding"><select value={form.funding_source} onChange={e=>setForm({...form,funding_source:e.target.value as any})}><option>Salary</option><option>Other</option></select></Field></div>
  <Field label="Expected maturity amount"><input type="number" min="0" value={form.expected_maturity_amount} onChange={e=>setForm({...form,expected_maturity_amount:e.target.value})}/></Field>
  <button disabled={saving} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white"><Plus size={17}/>{saving?"Saving…":editing?"Save changes":"Add investment"}</button></form>
  <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[.16em] text-violet-600">PORTFOLIO</p><h2 className="mt-1 text-xl font-black">Every investment is actionable</h2></div><span className="text-xs text-slate-500">Edit or delete any row</span></div><div className="mt-4 overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Investment</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Principal</th><th className="px-4 py-3">Rate</th><th className="px-4 py-3">Maturity</th><th className="px-4 py-3">Current</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(i=><tr key={i.id} className="hover:bg-slate-50"><td className="px-4 py-3 font-bold">{i.name}</td><td className="px-4 py-3">{i.investment_type}</td><td className="px-4 py-3">{money(i.principal_amount)}</td><td className="px-4 py-3">{i.expected_rate}% {i.rate_period}</td><td className="px-4 py-3">{i.maturity_on||"—"}</td><td className="px-4 py-3 font-black">{money(i.current_value??i.principal_amount)}</td><td className="px-4 py-3"><div className="flex justify-end gap-1"><button onClick={()=>startEdit(i)} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Edit"><Pencil size={16}/></button><button onClick={()=>remove(i.id)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" aria-label="Delete"><Trash2 size={16}/></button></div></td></tr>)}{!items.length&&<tr><td colSpan={7} className="p-10 text-center text-slate-500">No investments yet. Add your first one on the left.</td></tr>}</tbody></table></div></section></section>
 </div></main>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="mt-3 block text-xs font-bold">{label}{cloneElement(children as ReactElement<any>,{className:"mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm font-normal outline-none"})}</label>}
function K({label,v}:{label:string;v:string}){return <div className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p className="text-[10px] uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{v}</p></div>}
