"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase-browser";
import { categorizeTransaction, normalizeHeader, parseCsvLine, parseMoney } from "@/lib/finance-categorizer";
import { extractPdfStatement } from "@/lib/pdf-statement";
import { validateCredentials } from "@/lib/auth-validation";
import { BankConnectCard } from "@/components/bank-connect-card";

type Txn={transaction_date:string|null;description:string;amount:number;transaction_type:string;category:string;confidence:number;source:string;fingerprint:string};
function money(v:number){return `₹${Math.round(v).toLocaleString("en-IN")}`}
function clean(v:string){return v.toLowerCase().replace(/\s+/g," ").replace(/[^a-z0-9 .&/-]/g,"").trim()}
function bankOf(source:string){const p=source.split("::");return p[1]||"Bank account not identified"}
const icons:Record<string,string>={Food:"🍔",Fuel:"⛽",Groceries:"🛒",Shopping:"🛍️",Transport:"🚕",Subscriptions:"🔁","Bills & Utilities":"💡",Healthcare:"🏥",Education:"📚",Entertainment:"🎬","EMI / Loans":"🏦",Investment:"💎",Transfer:"🔄","Cash Withdrawal":"💵",Income:"💰",Other:"📦"};
async function fingerprint(v:string){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function toDate(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}

export default function FinancePage(){
 const router=useRouter();
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [userEmail,setUserEmail]=useState<string|null>(null);const [mode,setMode]=useState<"signin"|"signup">("signin");
 const [supabase,setSupabase]=useState<ReturnType<typeof createClient>|null>(null);const [transactions,setTransactions]=useState<Txn[]>([]);const [busy,setBusy]=useState(false);const [importing,setImporting]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 const [selected,setSelected]=useState<{bank:string;kind:"income"|"expense"|"balance"}|null>(null);
 useEffect(()=>{let live=true;try{const c=createClient();setSupabase(c);c.auth.getUser().then(({data})=>{if(live)setUserEmail(data.user?.email??null)});const {data}=c.auth.onAuthStateChange((_e,s)=>{if(live)setUserEmail(s?.user?.email??null)});return()=>{live=false;data.subscription.unsubscribe()}}catch(e){setError(e instanceof Error?e.message:"Supabase configuration is missing.")}},[]);
 useEffect(()=>{if(!supabase||!userEmail)return;supabase.from("finance_transactions").select("transaction_date,description,amount,transaction_type,category,confidence,source,fingerprint").order("transaction_date",{ascending:false}).limit(2000).then(({data})=>{if(data)setTransactions(data as Txn[])})},[supabase,userEmail]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(!supabase)throw Error("Supabase is not configured.");const v=validateCredentials(email,password,mode);if(v)throw Error(v);const r=mode==="signin"?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:window.location.origin+"/finance"}});if(r.error)throw r.error;if(mode==="signup"&&!r.data.session)setMessage("Account created. Check your email to confirm it.");else{setUserEmail(r.data.user?.email??email.trim());router.refresh()}}catch(e){setError(e instanceof Error?e.message:"Authentication failed")}finally{setBusy(false)}}
 async function save(rows:Txn[],label:string){if(!supabase)throw Error("Supabase is not configured.");const u=(await supabase.auth.getUser()).data.user;if(!u)throw Error("Your session expired. Please sign in again.");const {error:e}=await supabase.from("finance_transactions").upsert(rows.map(r=>({...r,user_id:u.id})),{onConflict:"user_id,fingerprint",ignoreDuplicates:true});if(e)throw e;const {data}=await supabase.from("finance_transactions").select("transaction_date,description,amount,transaction_type,category,confidence,source,fingerprint").order("transaction_date",{ascending:false}).limit(2000);setTransactions((data||[]) as Txn[]);setMessage(`Analyzed ${rows.length.toLocaleString()} ${label} transactions. Duplicates were skipped.`)}
 async function csv(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!supabase)return;setImporting(true);setError("");setMessage("");try{const lines=(await f.text()).split(/\r?\n/).filter(Boolean);if(lines.length<2)throw Error("CSV appears to be empty.");const hs=parseCsvLine(lines[0]).map(normalizeHeader);const find=(...ns:string[])=>ns.map(normalizeHeader).map(n=>hs.indexOf(n)).find(i=>i>=0)??-1;const di=find("transaction date","date","transactiondate"),xi=find("description","details","narration","remarks","merchant"),ai=find("amount","transaction amount","value"),db=find("debit","withdrawal","debit amount"),cr=find("credit","deposit","credit amount"),ti=find("type","transaction type","dr cr"),bi=find("bank","account","account name","paid by","source account");if(xi<0||(ai<0&&db<0&&cr<0))throw Error("I couldn't identify the transaction description and amount columns.");const rows:Txn[]=[];for(const line of lines.slice(1)){const c=parseCsvLine(line),description=(c[xi]||"").trim();if(!description)continue;const debit=db>=0?Math.abs(parseMoney(c[db])):0,credit=cr>=0?Math.abs(parseMoney(c[cr])):0,raw=ai>=0?parseMoney(c[ai]):credit||-debit;if(!raw&&!debit&&!credit)continue;const amount=ai>=0?Math.abs(raw):credit||debit;const typeHint=ti>=0?c[ti]:credit>0?"credit":"debit";const classified=categorizeTransaction(description,amount,typeHint);const transaction_type=/credit|received|income|deposit/i.test(typeHint)?"income":"expense";const d=di>=0?toDate(c[di]):null;const bank=bi>=0?(c[bi]||"Unknown account").trim():"Unknown account";rows.push({transaction_date:d,description,amount,transaction_type,category:classified.category,confidence:classified.confidence,source:`gpay::${bank}`,fingerprint:await fingerprint(`${d||""}|${clean(description)}|${amount.toFixed(2)}|${transaction_type}|${bank}`)})}if(!rows.length)throw Error("No usable transactions were found.");await save(rows,"CSV")}catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setImporting(false);e.target.value=""}}
 async function pdf(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!supabase)return;setImporting(true);setError("");setMessage("");try{if(!f.name.toLowerCase().endsWith(".pdf"))throw Error("Please select a PDF statement.");if(f.size>25*1024*1024)throw Error("PDF is larger than 25 MB.");const parsed=await extractPdfStatement(f);if(!parsed.length)throw Error("No transaction rows found. Make sure this is a text-based statement.");const rows:Txn[]=[];for(const r of parsed){const c=categorizeTransaction(r.description,r.amount,r.transaction_type==="income"?"credit":"debit");const bank=r.source_account||"Unknown account";rows.push({transaction_date:r.transaction_date,description:r.description,amount:r.amount,transaction_type:r.transaction_type,category:c.category,confidence:c.confidence,source:`pdf-statement::${bank}`,fingerprint:await fingerprint(`${r.provider_transaction_id||""}|${r.transaction_date||""}|${clean(r.description)}|${r.amount.toFixed(2)}|${r.transaction_type}|${bank}`)})}await save(rows,"PDF")}catch(e){setError(e instanceof Error?e.message:"PDF import failed")}finally{setImporting(false);e.target.value=""}}
 async function signOut(){if(!supabase)return;await supabase.auth.signOut();setUserEmail(null);setTransactions([])}
 const banks=useMemo(()=>{const map:Record<string,{income:number;expense:number;transactions:Txn[]}>={};for(const t of transactions){const b=bankOf(t.source);if(!map[b])map[b]={income:0,expense:0,transactions:[]};map[b].transactions.push(t);if(t.transaction_type==="income")map[b].income+=Number(t.amount);else if(t.transaction_type==="expense")map[b].expense+=Number(t.amount)}return Object.entries(map).sort((a,b)=>(b[1].income+b[1].expense)-(a[1].income+a[1].expense))},[transactions]);
 const detail=useMemo(()=>{if(!selected)return [];const b=banks.find(([name])=>name===selected.bank)?.[1];if(!b)return [];if(selected.kind==="income")return b.transactions.filter(t=>t.transaction_type==="income");if(selected.kind==="expense")return b.transactions.filter(t=>t.transaction_type==="expense");return []},[selected,banks]);
 const totals=useMemo(()=>({income:transactions.filter(t=>t.transaction_type==="income").reduce((s,t)=>s+t.amount,0),expense:transactions.filter(t=>t.transaction_type==="expense").reduce((s,t)=>s+t.amount,0)}),[transactions]);
 if(!userEmail)return <main className="min-h-screen px-5 py-12"><div className="mx-auto max-w-md rounded-[2rem] border border-white/10 bg-white/[.045] p-7 shadow-2xl"><p className="text-sm font-semibold text-violet-300">TARGETBUD PRIVATE AREA</p><h1 className="mt-3 text-3xl font-semibold">Your money, made simple.</h1><p className="mt-2 text-sm text-slate-400">Sign in to understand every rupee across your accounts.</p><form onSubmit={submit} className="mt-7 space-y-4"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"/>{error&&<p className="text-sm text-red-300">{error}</p>}{message&&<p className="text-sm text-emerald-300">{message}</p>}<button disabled={busy} className="w-full rounded-xl bg-violet-500 px-4 py-3 font-semibold">{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form><button onClick={()=>{setMode(mode==="signin"?"signup":"signin");setError("");setMessage("")}} className="mt-4 w-full text-sm text-violet-300">{mode==="signin"?"Create a new account":"Already have an account? Sign in"}</button></div></main>;
 return <main className="min-h-screen px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><header className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold tracking-[.2em] text-violet-300">TARGETBUD FINANCE</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">Your money, by bank</h1><p className="mt-1 text-sm text-slate-400">Start with the account. Click any number to see exactly where it came from.</p></div><button onClick={signOut} className="rounded-xl border border-white/15 px-4 py-2 text-sm">Sign out</button></header>
 <section className="mt-7 grid gap-4 sm:grid-cols-3"><div className="rounded-[1.7rem] border border-emerald-400/20 bg-emerald-400/10 p-5"><p className="text-sm text-slate-300">💰 Total income</p><button onClick={()=>setSelected(null)} className="mt-2 text-3xl font-bold">{money(totals.income)}</button><p className="mt-1 text-xs text-slate-500">Across imported accounts</p></div><div className="rounded-[1.7rem] border border-rose-400/20 bg-rose-400/10 p-5"><p className="text-sm text-slate-300">🛒 Total expenses</p><p className="mt-2 text-3xl font-bold">{money(totals.expense)}</p><p className="mt-1 text-xs text-slate-500">Only transactions currently classified as expenses</p></div><div className="rounded-[1.7rem] border border-sky-400/20 bg-sky-400/10 p-5"><p className="text-sm text-slate-300">🏦 Accounts found</p><p className="mt-2 text-3xl font-bold">{banks.length}</p><p className="mt-1 text-xs text-slate-500">From the imported transaction sources</p></div></section>
 <BankConnectCard />
 <section className="mt-6 rounded-[2rem] border border-white/10 bg-white/[.045] p-5 sm:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold text-violet-300">🏦 YOUR ACCOUNTS</p><h2 className="mt-1 text-2xl font-semibold">Income, expenses and balance</h2></div><p className="text-right text-xs text-slate-500">Click an amount<br/>to open details</p></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{banks.length?banks.map(([bank,b])=><div key={bank} className="rounded-2xl border border-white/10 bg-black/10 p-5"><div className="flex items-center justify-between"><div><p className="font-semibold">🏦 {bank}</p><p className="mt-1 text-xs text-slate-500">{b.transactions.length} imported transaction{b.transactions.length===1?"":"s"}</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs">90-day activity</span></div><div className="mt-5 grid grid-cols-3 gap-2"><button onClick={()=>setSelected({bank,kind:"income"})} className="rounded-xl bg-emerald-400/10 p-3 text-left"><p className="text-xs text-slate-400">Income</p><p className="mt-1 font-bold text-emerald-300">{money(b.income)}</p></button><button onClick={()=>setSelected({bank,kind:"expense"})} className="rounded-xl bg-rose-400/10 p-3 text-left"><p className="text-xs text-slate-400">Expenses</p><p className="mt-1 font-bold text-rose-300">{money(b.expense)}</p></button><button onClick={()=>setSelected({bank,kind:"balance"})} className="rounded-xl bg-sky-400/10 p-3 text-left"><p className="text-xs text-slate-400">Balance</p><p className="mt-1 font-bold text-sky-300">—</p></button></div><p className="mt-3 text-xs text-slate-500">Balance is shown only when the uploaded source contains a real account balance. A GPay payment statement does not provide the current bank balance.</p></div>):<div className="rounded-2xl border border-dashed border-white/10 p-8 text-center sm:col-span-2"><p className="text-4xl">🏦</p><p className="mt-3 font-semibold">Connect a bank above or upload a statement</p><p className="mt-1 text-sm text-slate-500">TargetBud will build the bank-wise view automatically.</p></div>}</div></section>
 <section className="mt-6 rounded-[2rem] border border-violet-400/20 bg-violet-500/5 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">📥 Add more history</p><p className="mt-1 text-sm text-slate-400">PDF/CSV remains available for historical backfill or unsupported providers.</p></div><div className="flex gap-2"><label className="cursor-pointer rounded-xl border border-white/15 px-4 py-3 font-semibold">{importing?"Analyzing…":"Upload PDF"}<input type="file" accept="application/pdf,.pdf" onChange={pdf} disabled={importing} className="hidden"/></label><label className="cursor-pointer rounded-xl bg-violet-500 px-4 py-3 font-semibold">{importing?"Analyzing…":"Upload CSV"}<input type="file" accept=".csv,text/csv" onChange={csv} disabled={importing} className="hidden"/></label></div></div>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}{message&&<p className="mt-4 text-sm text-emerald-300">{message}</p>}</section>
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 sm:items-center"><div className="max-h-[85vh] w-full max-w-2xl overflow-hidden rounded-[2rem] border border-white/10 bg-slate-950 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-xs font-semibold text-violet-300">{selected.bank}</p><h2 className="mt-1 text-xl font-semibold">{selected.kind==="income"?"Income details":selected.kind==="expense"?"Expense details":"Current balance"}</h2></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 px-3 py-2">✕</button></div>{selected.kind==="balance"?<div className="p-6"><p className="text-4xl font-bold">Balance unavailable</p><p className="mt-3 text-sm text-slate-400">The imported GPay statement contains payment activity, not the bank's current balance. Connect a bank to receive account summary data.</p></div>:<div className="max-h-[65vh] overflow-y-auto p-5">{detail.length?detail.map(t=><div key={t.fingerprint} className="flex items-center justify-between gap-4 border-b border-white/5 py-4"><div className="min-w-0"><p className="font-medium">{icons[t.category]||"📦"} {t.category}</p><p className="truncate text-sm text-slate-400">{t.description}</p><p className="text-xs text-slate-600">{t.transaction_date||"—"}</p></div><p className="shrink-0 font-bold">{money(t.amount)}</p></div>):<p className="py-8 text-center text-sm text-slate-500">No transactions in this category.</p>}</div>}</div></div>}
 </div></main>;
}
