"use client";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase-browser";
import { categorizeTransaction, normalizeHeader, parseCsvLine, parseMoney } from "@/lib/finance-categorizer";
import { extractPdfStatement } from "@/lib/pdf-statement";
import { validateCredentials } from "@/lib/auth-validation";

type Txn={transaction_date:string|null;description:string;amount:number;transaction_type:string;category:string;confidence:number;source:string;fingerprint:string};
async function fp(v:string){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)}
function clean(v:string){return v.toLowerCase().replace(/\s+/g," ").replace(/[^a-z0-9 .&/-]/g,"").trim()}

export default function FinancePage(){
 const router=useRouter();const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [userEmail,setUserEmail]=useState<string|null>(null);const [mode,setMode]=useState<"signin"|"signup">("signin");const [busy,setBusy]=useState(false);const [importing,setImporting]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [supabase,setSupabase]=useState<ReturnType<typeof createClient>|null>(null);const [transactions,setTransactions]=useState<Txn[]>([]);const [menu,setMenu]=useState(false);
 useEffect(()=>{let on=true;try{const c=createClient();setSupabase(c);c.auth.getUser().then(({data})=>{if(on)setUserEmail(data.user?.email??null)});const {data}=c.auth.onAuthStateChange((_e,s)=>{if(on)setUserEmail(s?.user?.email??null)});return()=>{on=false;data.subscription.unsubscribe()}}catch(e){setError(e instanceof Error?e.message:"Supabase configuration is missing.")}},[]);
 useEffect(()=>{if(!supabase||!userEmail)return;supabase.from("finance_transactions").select("transaction_date,description,amount,transaction_type,category,confidence,source,fingerprint").order("transaction_date",{ascending:false}).limit(1000).then(({data})=>{if(data)setTransactions(data as Txn[])})},[supabase,userEmail]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(!supabase)throw Error("Supabase is not configured.");const v=validateCredentials(email,password,mode);if(v)throw Error(v);const r=mode==="signin"?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:window.location.origin+"/finance"}});if(r.error)throw r.error;if(mode==="signup"&&!r.data.session)setMessage("Account created. Check your email to confirm your account, then sign in.");else{setUserEmail(r.data.user?.email??email.trim());setMessage("Signed in successfully.");router.refresh()}}catch(e){setError(e instanceof Error?e.message:"Authentication failed.")}finally{setBusy(false)}}
 async function save(rows:Txn[],label:string){if(!supabase)throw Error("Supabase is not configured.");const u=(await supabase.auth.getUser()).data.user;if(!u)throw Error("Your session expired. Please sign in again.");const {error:e}=await supabase.from("finance_transactions").upsert(rows.map(r=>({...r,user_id:u.id})),{onConflict:"user_id,fingerprint",ignoreDuplicates:true});if(e)throw e;const {data}=await supabase.from("finance_transactions").select("transaction_date,description,amount,transaction_type,category,confidence,source,fingerprint").order("transaction_date",{ascending:false}).limit(1000);setTransactions((data||[]) as Txn[]);setMessage(`Analyzed ${rows.length.toLocaleString()} ${label} transactions. Existing duplicates were skipped and categories were detected automatically.`)}
 async function csv(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!supabase)return;setImporting(true);setError("");setMessage("");setMenu(false);try{const lines=(await f.text()).split(/\r?\n/).filter(Boolean);if(lines.length<2)throw Error("CSV appears to be empty.");const hs=parseCsvLine(lines[0]).map(normalizeHeader);const find=(...ns:string[])=>ns.map(normalizeHeader).map(n=>hs.indexOf(n)).find(i=>i>=0)??-1;const di=find("transaction date","date","transactiondate"),xi=find("description","details","narration","remarks","merchant"),ai=find("amount","transaction amount","value"),db=find("debit","withdrawal","debit amount"),cr=find("credit","deposit","credit amount"),ti=find("type","transaction type","dr cr");if(xi<0||(ai<0&&db<0&&cr<0))throw Error("I couldn't identify the transaction description and amount columns.");const rows:Txn[]=[];for(const line of lines.slice(1)){const c=parseCsvLine(line),description=(c[xi]||"").trim();if(!description)continue;const debit=db>=0?Math.abs(parseMoney(c[db])):0,credit=cr>=0?Math.abs(parseMoney(c[cr])):0,raw=ai>=0?parseMoney(c[ai]):credit||-debit;if(!raw&&!debit&&!credit)continue;const amount=ai>=0?Math.abs(raw):credit||debit,typeHint=ti>=0?c[ti]:credit>0?"credit":"debit",classified=categorizeTransaction(description,amount,typeHint),transaction_type=/credit|received|income|deposit/i.test(typeHint)?"income":"expense",d=di>=0?date(c[di]):null;rows.push({transaction_date:d,description,amount,transaction_type,category:classified.category,confidence:classified.confidence,source:"gpay",fingerprint:await fp(`${d||""}|${clean(description)}|${amount.toFixed(2)}|${transaction_type}`)})}if(!rows.length)throw Error("No usable transactions were found.");await save(rows,"CSV")}catch(e){setError(e instanceof Error?e.message:"Import failed.")}finally{setImporting(false);e.target.value=""}}
 async function pdf(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!supabase)return;setImporting(true);setError("");setMessage("");setMenu(false);try{if(!f.name.toLowerCase().endsWith(".pdf"))throw Error("Please select a PDF statement.");if(f.size>25*1024*1024)throw Error("PDF is larger than 25 MB. Please upload a smaller statement.");const parsed=await extractPdfStatement(f);if(!parsed.length)throw Error("No transaction rows found. Make sure this is a text-based bank statement.");const rows:Txn[]=[];for(const r of parsed){const c=categorizeTransaction(r.description,r.amount,r.transaction_type==="income"?"credit":"debit");rows.push({...r,category:c.category,confidence:c.confidence,source:"pdf-statement",fingerprint:await fp(`${r.transaction_date||""}|${clean(r.description)}|${r.amount.toFixed(2)}|${r.transaction_type}`)})}await save(rows,"PDF")}catch(e){setError(e instanceof Error?e.message:"PDF import failed.")}finally{setImporting(false);e.target.value=""}}
 async function signOut(){if(!supabase)return;await supabase.auth.signOut();setUserEmail(null);setTransactions([])}
 const metrics=useMemo(()=>{const expense=transactions.filter(t=>t.transaction_type==="expense").reduce((s,t)=>s+Number(t.amount),0),income=transactions.filter(t=>t.transaction_type==="income").reduce((s,t)=>s+Number(t.amount),0),categories=transactions.filter(t=>t.transaction_type==="expense").reduce<Record<string,number>>((a,t)=>{a[t.category]=(a[t.category]||0)+Number(t.amount);return a},{});return{expense,income,savings:income-expense,categories}},[transactions]);
 if(!userEmail)return <main className="min-h-screen px-5 py-12"><div className="mx-auto max-w-md rounded-3xl border border-white/10 bg-white/[.045] p-7"><p className="text-sm font-semibold text-violet-300">TARGETBUD PRIVATE AREA</p><h1 className="mt-3 text-3xl font-semibold">My Finance</h1><p className="mt-2 text-sm text-slate-400">Sign in to access your private financial workspace.</p><form onSubmit={submit} className="mt-7 space-y-4"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Password" className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3"/>{error&&<p className="text-sm text-red-300">{error}</p>}{message&&<p className="text-sm text-emerald-300">{message}</p>}<button disabled={busy} className="w-full rounded-xl bg-violet-500 px-4 py-3 font-semibold">{busy?"Please wait…":mode==="signin"?"Sign in":"Create account"}</button></form><button onClick={()=>{setMode(mode==="signin"?"signup":"signin");setError("");setMessage("")}} className="mt-4 w-full text-sm text-violet-300">{mode==="signin"?"Create a new account":"Already have an account? Sign in"}</button></div></main>;
 const top=Object.entries(metrics.categories).sort((a,b)=>b[1]-a[1]).slice(0,6);return <main className="min-h-screen px-5 py-10"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between gap-4"><div><p className="text-sm text-violet-300">PRIVATE WORKSPACE</p><h1 className="mt-2 text-4xl font-semibold">My Finance</h1><p className="mt-2 text-slate-400">Signed in as {userEmail}</p></div><div className="flex gap-2"><button onClick={()=>setMenu(!menu)} className="rounded-xl border border-white/15 px-3 py-2 text-xl sm:hidden">☰</button><button onClick={signOut} className="rounded-xl border border-white/15 px-4 py-2 text-sm">Sign out</button></div></header>
 {menu&&<div className="mt-4 rounded-2xl border border-white/10 bg-slate-950 p-3 sm:hidden"><label className="flex cursor-pointer gap-3 rounded-xl px-3 py-3 font-semibold"><span>📄</span>Import PDF statement<input type="file" accept="application/pdf,.pdf" onChange={pdf} disabled={importing} className="hidden"/></label><label className="flex cursor-pointer gap-3 rounded-xl px-3 py-3 font-semibold"><span>📥</span>Import GPay CSV<input type="file" accept=".csv,text/csv" onChange={csv} disabled={importing} className="hidden"/></label></div>}
 <section className="mt-8 rounded-3xl border border-violet-400/20 bg-violet-500/5 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-semibold">Smart Transaction Import</h2><p className="mt-1 text-sm text-slate-400">Upload a bank PDF statement or GPay CSV. TargetBud categorizes transactions automatically.</p></div><div className="flex flex-wrap gap-2"><label className="cursor-pointer rounded-xl border border-white/15 px-4 py-3 font-semibold">{importing?"Analyzing…":"Upload PDF Statement"}<input type="file" accept="application/pdf,.pdf" onChange={pdf} disabled={importing} className="hidden"/></label><label className="cursor-pointer rounded-xl bg-violet-500 px-4 py-3 font-semibold">{importing?"Analyzing…":"Upload GPay CSV"}<input type="file" accept=".csv,text/csv" onChange={csv} disabled={importing} className="hidden"/></label></div></div>{error&&<p className="mt-4 text-sm text-red-300">{error}</p>}{message&&<p className="mt-4 text-sm text-emerald-300">{message}</p>}<p className="mt-3 text-xs text-slate-500">PDFs are parsed in your browser; the uploaded PDF itself is not stored.</p></section>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Income",metrics.income],["Expenses",metrics.expense],["Net cash flow",metrics.savings],["Transactions",transactions.length]].map(([t,v])=><div key={String(t)} className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><p className="text-sm text-slate-400">{t}</p><p className="mt-3 text-2xl font-semibold">{t==="Transactions"?Number(v).toLocaleString():`₹${Number(v).toLocaleString("en-IN",{maximumFractionDigits:0})}`}</p></div>)}</div>
 <div className="mt-6 grid gap-6 lg:grid-cols-3"><section className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><h2 className="font-semibold">Top spending categories</h2><div className="mt-4 space-y-3">{top.length?top.map(([c,a])=><div key={c} className="flex justify-between text-sm"><span>{c}</span><span>₹{a.toLocaleString("en-IN",{maximumFractionDigits:0})}</span></div>):<p className="text-sm text-slate-500">Upload a statement to see spending.</p>}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.045] p-5 lg:col-span-2"><h2 className="font-semibold">Recent transactions</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">Date</th><th className="pb-3">Description</th><th className="pb-3">Category</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{transactions.slice(0,20).map(t=><tr key={t.fingerprint} className="border-t border-white/5"><td className="py-3">{t.transaction_date||"—"}</td><td className="py-3">{t.description}</td><td className="py-3">{t.category}</td><td className="py-3 text-right">{t.transaction_type==="income"?"+":"−"}₹{Number(t.amount).toLocaleString("en-IN",{maximumFractionDigits:0})}</td></tr>)}</tbody></table></div></section></div></div></main>;
}
