"use client";

import type { ChangeEvent, DragEvent } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { AudioLines, ChevronLeft, ChevronRight, Film, GripVertical, Image as ImageIcon, Music2, Pause, Play, Plus, Redo2, Scissors, Settings2, SlidersHorizontal, Sparkles, Trash2, Type, Undo2, Upload, Volume2 } from "lucide-react";
import { getBrowserExportFormat } from "./export-support";
import { exportBrowserComposition, type CompositionClip } from "./browser-compositor";

type MediaType = "video" | "image" | "audio";
type Lane = "video" | "overlay" | "audio";
type Tool = "media" | "text" | "audio" | "effects" | "transitions" | "filters";
type Filter = "none" | "mono" | "warm" | "cool" | "vivid" | "fade";
type Clip = CompositionClip & { file: File; lane: Lane; filter?: Filter; rotation?: number; scale?: number; x?: number; y?: number; transition?: "none" | "fade" | "slide"; text?: string };
type Ratio = "9:16" | "16:9" | "1:1";
const ratios: Ratio[] = ["9:16", "16:9", "1:1"];
const lanes: Lane[] = ["video", "overlay", "audio"];
const laneLabel: Record<Lane,string> = { video:"Video", overlay:"Overlay", audio:"Audio" };
const ratioClass: Record<Ratio,string> = { "9:16":"aspect-[9/16]", "16:9":"aspect-video", "1:1":"aspect-square" };
const filters: Filter[] = ["none","mono","warm","cool","vivid","fade"];
const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(v,min),max);
const len=(c?:Clip)=>c?Math.max(0,c.trimEnd-c.trimStart):0;
const laneFor=(t:MediaType):Lane=>t==="audio"?"audio":t==="image"?"overlay":"video";

export default function VideoStudioV5(){
 const [clips,setClips]=useState<Clip[]>([]),[selected,setSelected]=useState<string|null>(null),[ratio,setRatio]=useState<Ratio>("9:16"),[current,setCurrent]=useState(0),[playing,setPlaying]=useState(false),[tool,setTool]=useState<Tool>("media"),[speed,setSpeed]=useState(1),[history,setHistory]=useState<Clip[][]>([]),[future,setFuture]=useState<Clip[][]>([]),[dragId,setDragId]=useState<string|null>(null),[zoom,setZoom]=useState(1),[message,setMessage]=useState<string|null>(null),[exporting,setExporting]=useState(false),[projectName,setProjectName]=useState("Untitled project"),[text,setText]=useState("");
 const videoRef=useRef<HTMLVideoElement>(null),inputRef=useRef<HTMLInputElement>(null); const active=clips.find(c=>c.id===selected)||clips[0];
 const total=useMemo(()=>clips.filter(c=>c.lane!=="audio").reduce((n,c)=>n+len(c),0),[clips]); const timelineWidth=Math.max(720,total*80*zoom+120);
 const remember=()=>{setHistory(h=>[...h.slice(-29),clips]);setFuture([])};
 const select=(id:string)=>{setSelected(id);setCurrent(0);setPlaying(false)};
 const addFiles=(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]).filter(f=>/^(video|image|audio)\//.test(f.type));if(!files.length)return;const next=files.map(file=>{const type:MediaType=file.type.startsWith("video/")?"video":file.type.startsWith("audio/")?"audio":"image";const d=type==="image"?5:0;return {id:crypto.randomUUID(),name:file.name,url:URL.createObjectURL(file),type,lane:laneFor(type),duration:d,trimStart:0,trimEnd:d,volume:type!=="image"?1:0,fadeIn:0,fadeOut:0,file,filter:"none" as Filter,rotation:0,scale:1,x:0,y:0,transition:"none" as const};});setClips(c=>[...c,...next]);setSelected(next[0]?.id||selected);e.target.value="";setMessage(null)};
 useEffect(()=>{if(!active||active.duration||active.type==="image")return;const m=document.createElement(active.type==="audio"?"audio":"video");m.preload="metadata";m.src=active.url;const f=()=>{if(Number.isFinite(m.duration)&&m.duration>0)setClips(cs=>cs.map(c=>c.id===active.id?{...c,duration:m.duration,trimEnd:m.duration}:c))};m.addEventListener("loadedmetadata",f);return()=>{m.removeEventListener("loadedmetadata",f);m.src=""}},[active?.id,active?.duration,active?.type,active?.url]);
 useEffect(()=>{if(videoRef.current)videoRef.current.playbackRate=speed},[speed]);
 useEffect(()=>{const v=videoRef.current;if(!v)return;const f=()=>{if(active?.type!=="video")return;const t=v.currentTime-active.trimStart;if(t>=len(active)){v.pause();setPlaying(false);setCurrent(len(active))}else if(t>=0)setCurrent(t)};v.addEventListener("timeupdate",f);return()=>v.removeEventListener("timeupdate",f)},[active?.id,active?.trimStart,active?.trimEnd]);
 const undo=()=>{const p=history.at(-1);if(!p)return;setFuture(f=>[...f,clips]);setHistory(h=>h.slice(0,-1));setClips(p);setSelected(p[0]?.id||null)};
 const redo=()=>{const n=future.at(-1);if(!n)return;setHistory(h=>[...h,clips]);setFuture(f=>f.slice(0,-1));setClips(n);setSelected(n[0]?.id||null)};
 const update=(patch:Partial<Clip>)=>{if(!active)return;remember();setClips(cs=>cs.map(c=>c.id===active.id?{...c,...patch}:c))};
 const split=()=>{if(!active||active.type!=="video"||len(active)<1)return;const local=clamp(current,.1,len(active)-.1),cut=active.trimStart+local;remember();const a={...active,id:crypto.randomUUID(),name:`${active.name} · A`,trimEnd:cut},b={...active,id:crypto.randomUUID(),name:`${active.name} · B`,trimStart:cut};const i=clips.findIndex(c=>c.id===active.id);setClips([...clips.slice(0,i),a,b,...clips.slice(i+1)]);setSelected(a.id);setCurrent(0)};
 const remove=()=>{if(!active)return;remember();URL.revokeObjectURL(active.url);const n=clips.filter(c=>c.id!==active.id);setClips(n);setSelected(n[0]?.id||null);setCurrent(0)};
 const reorder=(from:string,to:string)=>{if(from===to)return;const a=clips.findIndex(c=>c.id===from),b=clips.findIndex(c=>c.id===to);if(a<0||b<0||clips[a].lane!==clips[b].lane)return;remember();const n=[...clips], [x]=n.splice(a,1);n.splice(b,0,x);setClips(n)};
 const moveLane=(lane:Lane)=>{if(active&&active.lane!==lane)update({lane})};
 const trim=(key:"trimStart"|"trimEnd",v:number)=>{if(!active)return;const min=key==="trimStart"?0:active.trimStart+.1,max=key==="trimEnd"?active.duration:active.trimEnd-.1;update({[key]:clamp(v,min,max)} as Partial<Clip>)};
 const sync=(t:number)=>{setCurrent(t);if(videoRef.current&&active?.type==="video")videoRef.current.currentTime=active.trimStart+clamp(t,0,len(active))};
 const exportProject=async()=>{setExporting(true);setMessage(null);try{const f=getBrowserExportFormat();if(!f)throw new Error("This browser cannot encode a project video.");const r=await exportBrowserComposition({clips,ratio,text,mimeType:f.mimeType,extension:f.extension});const u=URL.createObjectURL(r.blob),a=document.createElement("a");a.href=u;a.download=`${projectName.replace(/[^a-z0-9-_]+/gi,"-")}.${r.extension}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);setMessage(`Export complete: ${r.extension.toUpperCase()}.`)}catch(e){setMessage(e instanceof Error?e.message:"Export failed.")}finally{setExporting(false)}};
 const tools:[Tool,string,React.ReactNode][]=[["media","Media",<Film size={18}/>],["text","Text",<Type size={18}/>],["audio","Audio",<AudioLines size={18}/>],["effects","Effects",<Sparkles size={18}/>],["transitions","Transitions",<ChevronRight size={18}/>],["filters","Filters",<SlidersHorizontal size={18}/>]];
 return <main className="min-h-[calc(100vh-56px)] bg-[#0d0d0f] text-white">
  <header className="flex h-14 items-center justify-between border-b border-white/10 bg-[#151518] px-3 sm:px-5"><div className="flex min-w-0 items-center gap-3"><button className="rounded-lg p-2 hover:bg-white/10" aria-label="Back"><ChevronLeft size={18}/></button><input value={projectName} onChange={e=>setProjectName(e.target.value)} className="w-40 bg-transparent text-sm font-semibold outline-none sm:w-56"/><span className="hidden rounded-full bg-white/5 px-2 py-1 text-[10px] text-white/45 sm:block">Saved locally</span></div><div className="flex items-center gap-1.5"><button onClick={undo} disabled={!history.length} className="rounded-lg p-2 hover:bg-white/10 disabled:opacity-25" aria-label="Undo"><Undo2 size={17}/></button><button onClick={redo} disabled={!future.length} className="rounded-lg p-2 hover:bg-white/10 disabled:opacity-25" aria-label="Redo"><Redo2 size={17}/></button><button onClick={()=>inputRef.current?.click()} className="hidden items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-xs font-bold sm:flex"><Upload size={14}/> Import</button><button onClick={exportProject} disabled={!clips.length||exporting} className="rounded-lg bg-white px-3 py-2 text-xs font-bold text-black disabled:opacity-30">{exporting?"Exporting…":"Export"}</button></div></header>
  <input ref={inputRef} type="file" accept="video/*,image/*,audio/*" multiple className="hidden" onChange={addFiles}/>
  <div className="grid min-h-[calc(100vh-112px)] lg:grid-cols-[72px_230px_minmax(0,1fr)_270px]">
   <nav className="order-2 flex gap-1 overflow-x-auto border-b border-white/10 bg-[#111114] p-2 lg:order-1 lg:flex-col lg:border-b-0 lg:border-r lg:p-2">{tools.map(([id,label,icon])=><button key={id} onClick={()=>setTool(id)} className={`flex min-w-16 flex-col items-center gap-1 rounded-xl px-2 py-2 text-[9px] font-semibold ${tool===id?"bg-white text-black":"text-white/55 hover:bg-white/5"}`}>{icon}<span>{label}</span></button>)}</nav>
   <aside className="order-1 border-b border-white/10 bg-[#17171a] p-3 lg:order-2 lg:border-b-0 lg:border-r">{tool==="media"&&<><div className="mb-3 flex items-center justify-between"><b className="text-xs">Media</b><span className="text-[10px] text-white/35">{clips.length}</span></div><button onClick={()=>inputRef.current?.click()} className="mb-3 flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-white/20 px-3 py-6 text-xs font-bold"><Plus size={15}/> Import media</button><div className="space-y-2">{clips.map(c=><button key={c.id} onClick={()=>select(c.id)} className={`w-full rounded-xl border p-2 text-left ${selected===c.id?"border-white/60 bg-white/10":"border-white/10 bg-white/[.03]"}`}><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-white/10">{c.type==="audio"?<Music2 size={14}/>:c.type==="image"?<ImageIcon size={14}/>:<Film size={14}/>}</span><span className="min-w-0 truncate text-[11px] font-semibold">{c.name}</span></div><span className="mt-1 block text-[9px] text-white/35">{c.duration?`${len(c).toFixed(1)}s · ${laneLabel[c.lane]}`:"Loading duration…"}</span></button>)}{!clips.length&&<p className="py-10 text-center text-[11px] leading-5 text-white/30">Import video, photos or audio to begin.</p>}</div></>}
    {tool==="text"&&<div className="space-y-3"><b className="text-xs">Text</b><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Type your title or caption" className="h-28 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-xs outline-none"/><p className="text-[10px] text-white/35">Text appears in the preview and is included in export.</p></div>}
    {tool==="audio"&&<div className="space-y-3"><b className="text-xs">Audio</b><button onClick={()=>inputRef.current?.click()} className="flex w-full items-center gap-2 rounded-xl border border-white/10 bg-white/5 p-3 text-xs"><Music2 size={15}/> Import audio</button><p className="text-[10px] text-white/35">Use the Audio lane to arrange music and voice tracks.</p></div>}
    {tool==="filters"&&<div className="space-y-2"><b className="block mb-2 text-xs">Filters</b>{filters.map(f=><button key={f} disabled={!active} onClick={()=>update({filter:f})} className={`w-full rounded-xl border px-3 py-3 text-left text-xs ${active?.filter===f?"border-white bg-white text-black":"border-white/10 bg-white/5"}`}>{f[0].toUpperCase()+f.slice(1)}</button>)}</div>}
    {tool==="effects"&&<div className="space-y-3"><b className="text-xs">Transform & effects</b><label className="block text-[10px] text-white/50">Scale <input disabled={!active} type="range" min="0.5" max="2" step="0.05" value={active?.scale||1} onChange={e=>update({scale:Number(e.target.value)})} className="mt-2 w-full"/></label><label className="block text-[10px] text-white/50">Rotation <input disabled={!active} type="range" min="-180" max="180" value={active?.rotation||0} onChange={e=>update({rotation:Number(e.target.value)})} className="mt-2 w-full"/></label><button disabled={!active} onClick={()=>update({scale:1,rotation:0,x:0,y:0})} className="w-full rounded-xl bg-white/10 px-3 py-2 text-xs">Reset transform</button></div>}
    {tool==="transitions"&&<div className="space-y-2"><b className="block mb-2 text-xs">Transitions</b>{(["none","fade","slide"] as const).map(t=><button key={t} disabled={!active} onClick={()=>update({transition:t})} className={`w-full rounded-xl border px-3 py-3 text-left text-xs ${active?.transition===t?"border-white bg-white text-black":"border-white/10 bg-white/5"}`}>{t[0].toUpperCase()+t.slice(1)}</button>)}<p className="text-[10px] text-white/30">Transition is stored on the selected cut and used by the preview/export pipeline as support is added.</p></div>}
   </aside>
   <section className="order-3 flex min-w-0 flex-col bg-[#0b0b0d] lg:order-3">
    <div className="flex min-h-[430px] flex-1 items-center justify-center p-4 sm:p-8"><div className={`relative max-h-[60vh] w-full max-w-[760px] overflow-hidden rounded-xl bg-black shadow-2xl ${ratioClass[ratio]}`}><div className="absolute inset-0 flex items-center justify-center">{active?.type==="video"?<video ref={videoRef} src={active.url} className="h-full w-full object-contain" playsInline style={{filter:active?.filter==="mono"?"grayscale(1)":active?.filter==="warm"?"sepia(.35) saturate(1.2)":active?.filter==="cool"?"hue-rotate(180deg) saturate(.8)":active?.filter==="vivid"?"saturate(1.6) contrast(1.1)":active?.filter==="fade"?"saturate(.65) contrast(.9)":"none",transform:`translate(${active?.x||0}px,${active?.y||0}px) scale(${active?.scale||1}) rotate(${active?.rotation||0}deg)`}}/>:active?.type==="image"?<img src={active.url} alt="Selected media" className="h-full w-full object-contain" style={{filter:active?.filter==="mono"?"grayscale(1)":active?.filter==="warm"?"sepia(.35) saturate(1.2)":active?.filter==="vivid"?"saturate(1.6) contrast(1.1)":"none",transform:`scale(${active?.scale||1}) rotate(${active?.rotation||0}deg)`}}/>:<div className="text-white/35"><Music2 className="mx-auto mb-2"/>Audio selected</div>}{(text||active?.text)&&<div className="pointer-events-none absolute inset-x-5 top-[38%] text-center text-3xl font-black text-white drop-shadow-[0_3px_5px_rgba(0,0,0,.9)]">{active?.text||text}</div>}</div></div></div>
    <div className="flex items-center justify-center gap-3 border-t border-white/10 bg-[#111114] px-4 py-3"><button onClick={()=>sync(Math.max(0,current-5))} className="rounded-lg p-2 hover:bg-white/10"><ChevronLeft size={18}/></button><button disabled={active?.type!=="video"} onClick={()=>{const v=videoRef.current;if(!v)return;if(v.paused){sync(current);v.play();setPlaying(true)}else{v.pause();setPlaying(false)}}} className="grid size-10 place-items-center rounded-full bg-white text-black disabled:opacity-30">{playing?<Pause size={16}/>:<Play size={16}/>}</button><button onClick={()=>sync(Math.min(len(active),current+5))} className="rounded-lg p-2 hover:bg-white/10"><ChevronRight size={18}/></button><div className="ml-3 flex rounded-lg bg-white/5 p-1">{ratios.map(r=><button key={r} onClick={()=>setRatio(r)} className={`rounded-md px-2 py-1 text-[10px] ${ratio===r?"bg-white text-black":"text-white/50"}`}>{r}</button>)}</div></div>
   </section>
   <aside className="order-4 border-t border-white/10 bg-[#17171a] p-4 lg:order-4 lg:border-l lg:border-t-0">{active?<><div className="mb-5 flex items-start justify-between"><div><b className="block truncate text-xs">{active.name}</b><span className="text-[10px] text-white/35">{active.type} · {laneLabel[active.lane]}</span></div><button onClick={remove} className="rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white"><Trash2 size={15}/></button></div><div className="space-y-5"><div><label className="mb-2 block text-[10px] font-bold text-white/50">Track</label><div className="grid grid-cols-3 gap-1">{lanes.map(l=><button key={l} onClick={()=>moveLane(l)} className={`rounded-lg px-2 py-2 text-[9px] font-bold ${active.lane===l?"bg-white text-black":"bg-white/5 text-white/50"}`}>{laneLabel[l]}</button>)}</div></div>{active.type!=="image"&&<><label className="block text-[10px] text-white/50"><span className="mb-2 flex justify-between">Volume <b className="text-white">{Math.round((active.volume||0)*100)}%</b></span><input type="range" min="0" max="1" step=".01" value={active.volume||0} onChange={e=>update({volume:Number(e.target.value)})} className="w-full"/></label><label className="block text-[10px] text-white/50">Speed · {speed}×<input type="range" min=".25" max="2" step=".25" value={speed} onChange={e=>setSpeed(Number(e.target.value))} className="mt-2 w-full"/></label></>}
 <label className="block text-[10px] text-white/50">Trim start · {active.trimStart.toFixed(1)}s<input type="range" min="0" max={Math.max(0,active.trimEnd-.1)} step=".1" value={active.trimStart} onChange={e=>trim("trimStart",Number(e.target.value))} className="mt-2 w-full"/></label><label className="block text-[10px] text-white/50">Trim end · {active.trimEnd.toFixed(1)}s<input type="range" min={Math.min(active.duration,active.trimStart+.1)} max={active.duration||0} step=".1" value={active.trimEnd} onChange={e=>trim("trimEnd",Number(e.target.value))} className="mt-2 w-full"/></label><div className="grid grid-cols-2 gap-2"><button onClick={split} disabled={active.type!=="video"} className="inline-flex items-center justify-center gap-1 rounded-lg bg-white/10 px-2 py-2 text-[10px] font-bold disabled:opacity-25"><Scissors size={13}/> Split</button><button onClick={()=>update({fadeIn:.3,fadeOut:.3})} disabled={active.type==="image"} className="inline-flex items-center justify-center gap-1 rounded-lg bg-white/10 px-2 py-2 text-[10px] font-bold disabled:opacity-25"><Volume2 size={13}/> Auto fade</button></div></div></>:<div className="flex h-full items-center justify-center text-center text-xs text-white/30"><Settings2 className="mb-2 mx-auto"/>Select a clip</div>}</aside>
  </div>
  <div className="border-t border-white/10 bg-[#111114] px-2 py-2 sm:px-4"><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] text-white/40"><span>Timeline</span><button onClick={()=>setZoom(z=>clamp(z-.25,.5,3))} className="rounded bg-white/5 px-2 py-1">−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>clamp(z+.25,.5,3))} className="rounded bg-white/5 px-2 py-1">+</button></div><div className="text-[10px] text-white/30">{projectName} · {total.toFixed(1)}s</div></div><div className="overflow-x-auto rounded-lg border border-white/10"><div className="min-w-[720px]" style={{width:timelineWidth}}><div className="flex h-6 border-b border-white/10 pl-20">{Array.from({length:Math.max(2,Math.ceil(total/5)+1)}).map((_,i)=><span key={i} className="shrink-0 text-[9px] text-white/25" style={{width:400*zoom}}>{i*5}s</span>)}</div>{lanes.map(l=><div key={l} className="flex min-h-14 border-b border-white/10 last:border-0"><div className="sticky left-0 z-10 flex w-20 shrink-0 items-center bg-[#111114] px-2 text-[9px] font-bold uppercase tracking-wider text-white/35">{laneLabel[l]}</div><div className="flex flex-1 items-center gap-1 p-1">{clips.filter(c=>c.lane===l).map(c=><button key={c.id} draggable onDragStart={()=>setDragId(c.id)} onDragOver={e=>e.preventDefault()} onDrop={(e:DragEvent<HTMLButtonElement>)=>{e.preventDefault();if(dragId)reorder(dragId,c.id);setDragId(null)}} onClick={()=>select(c.id)} className={`group relative flex h-11 min-w-[90px] items-center gap-1 overflow-hidden rounded-md border px-2 text-left ${selected===c.id?"border-white bg-white/15":"border-white/10 bg-white/[.04]"}`} style={{width:Math.max(90,len(c)*80*zoom)}}><GripVertical size={11} className="shrink-0 text-white/20"/><span className="truncate text-[9px] font-semibold">{c.name}</span><span className="absolute bottom-1 right-1 text-[8px] text-white/30">{len(c).toFixed(1)}s</span></button>)}{!clips.some(c=>c.lane===l)&&<span className="px-2 text-[9px] text-white/20">Add media to this lane</span>}</div></div>)}</div></div><div className="mt-2 flex items-center justify-end gap-2 text-[9px] text-white/25"><span><Scissors size={10} className="inline"/> Split</span><span>Drag clips to reorder</span><span>Scroll timeline horizontally</span></div></div>
  {message&&<div role="status" className="fixed bottom-4 right-4 z-50 max-w-sm rounded-xl border border-white/10 bg-white px-4 py-3 text-xs font-semibold text-black shadow-xl">{message}</div>}
 </main>;
}
