"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, CheckCircle2, LockKeyhole, RefreshCw, Target, TrendingUp, WalletCards } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";
import { AUTO_REINVEST_RATE, GOAL_TARGET, currentValue, dateOnly, projectGoal, recurringMonthly, isActive, type GoalActivity, type GoalInvestment, type GoalSettlement } from "@/lib/goal-projection";

type Investment=GoalInvestment;
type Activity=GoalActivity;
type Settlement=GoalSettlement & { id:string; account_balance:number; expense_reserve:number; return_rate:number };
type Point={date:Date;value:number};
const money=(n:number)=>`₹${Math.round(Math.max(0,n)).toLocaleString("en-IN")}`;
const shortMoney=(n:number)=>n>=10000000?`₹${(n/10000000).toFixed(1)}Cr`:n>=100000?`₹${(n/100000).toFixed(1)}L`:n>=1000?`₹${Math.round(n/1000)}K`:money(n);
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const monthName=(d:Date)=>d.toLocaleDateString("en-IN",{month:"short",year:"numeric"});
const fullDate=(d:Date)=>d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
const daysInMonth=(d:Date)=>new Date(d.getFullYear(),d.getMonth()+1,0).getDate();
function Chart({points}:{points:Point[]}){const W=1080,H=340,L=58,R=22,T=24,B=46,max=Math.max(GOAL_TARGET,...points.map(p=>p.value),1),pw=W-L-R,ph=H-T-B;const path=points.map((p,i)=>{const x=L+(points.length===1?pw/2:i/(points.length-1)*pw),y=T+ph-p.value/max*ph;return`${i?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");const ty=T+ph-GOAL_TARGET/max*ph;return <div className="overflow-x-auto rounded-[1.5rem] bg-[#f7f8fa] p-3"><svg viewBox={`0 0 ${W} ${H}`} className="min-w-[720px] w-full"><line x1={L} x2={W-R} y1={ty} y2={ty} stroke="#7c3aed" strokeWidth="2" strokeDasharray="7 7"/><text x={W-R} y={ty-8} textAnchor="end" fontSize="12" fontWeight="700" fill="#7c3aed">₹70L target</text>{[0,.25,.5,.75,1].map(q=><g key={q}><line x1={L} x2={W-R} y1={T+ph*(1-q)} y2={T+ph*(1-q)} stroke="#e5e7eb"/><text x={L-9} y={T+ph*(1-q)+4} textAnchor="end" fontSize="11" fill="#6b7280">{shortMoney(max*q)}</text></g>)}<path d={path} fill="none" stroke="#111827" strokeWidth="4" strokeLinecap="round"/><text x={L} y={H-13} fontSize="11" fill="#6b7280">{monthName(points[0].date)}</text><text x={W-R} y={H-13} textAnchor="end" fontSize="11" fill="#6b7280">{monthName(points[points.length-1].date)}</text></svg></div>}

export default function GoalInsightsPage(){
 const [investments,setInvestments]=useState<Investment[]>([]),[activities,setActivities]=useState<Activity[]>([]),[settlements,setSettlements]=useState<Settlement[]>([]),[userId,setUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[accountBalance,setAccountBalance]=useState(""),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const today=new Date();
 const lastDay=daysInMonth(today),settlementOpen=today.getDate()>lastDay-5,currentMonth=monthStart(today).toISOString().slice(0,10);
 async function load(){setLoading(true);const s=createClient(),{data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}setUserId(user.id);const[{data:inv,error:ie},{data:act,error:ae},{data:set,error:se}]=await Promise.all([s.from("goal_investments").select("*").eq("user_id",user.id).order("invested_on",{ascending:true}),s.from("cash_flows").select("*").eq("user_id",user.id).eq("is_recurring",true).order("flow_date",{ascending:true}),s.from("goal_month_end_settlements").select("*").eq("user_id",user.id).order("month_start",{ascending:false})]);if(ie||ae||se)setMessage(ie?.message||ae?.message||se?.message||"Unable to load data.");setInvestments((inv??[])as Investment[]);setActivities((act??[])as Activity[]);setSettlements((set??[])as Settlement[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const active=activities.filter(a=>isActive(a,today)),monthlyIncome=active.filter(a=>a.flow_type==="income").reduce((s,a)=>s+recurringMonthly(a),0),monthlyExpenses=active.filter(a=>a.flow_type==="expense").reduce((s,a)=>s+recurringMonthly(a),0),salaryRemaining=Math.max(0,monthlyIncome-monthlyExpenses),current=investments.reduce((s,i)=>s+currentValue(i,today),0),progress=Math.min(100,current/GOAL_TARGET*100);
 const points=useMemo(()=>projectGoal(investments,activities,settlements,today),[investments,activities,settlements,today.toDateString()]);
 const target=points.find(p=>p.value>=GOAL_TARGET),expenseReserve=monthlyExpenses,entered=Number(accountBalance||0),investAmount=Math.max(0,entered-expenseReserve),currentSettlement=settlements.find(s=>s.month_start===currentMonth);
 async function saveSettlement(deposited:boolean){if(!userId||!accountBalance)return;setSaving(true);setMessage("");const s=createClient(),payload={user_id:userId,month_start:currentMonth,account_balance:entered,expense_reserve:expenseReserve,invest_amount:investAmount,return_rate:AUTO_REINVEST_RATE,deposited,deposited_at:deposited?new Date().toISOString():null};const{data,error}=await s.from("goal_month_end_settlements").upsert(payload,{onConflict:"user_id,month_start"}).select().single();if(error)setMessage(error.message);else{setSettlements(p=>[data as Settlement,...p.filter(x=>x.month_start!==currentMonth)]);setMessage(deposited?`${money(investAmount)} marked for 8.1% reinvestment.`:"Month-end amount saved.")}setSaving(false)}
 if(loading)return <main className="min-h-screen bg-[#f6f7f9] grid place-items-center text-sm text-slate-500">Loading your Wallet…</main>;
 if(!userId)return <main className="min-h-screen bg-[#f6f7f9] grid place-items-center p-5"><section className="w-full max-w-md rounded-[2rem] bg-white p-8 text-center shadow-sm"><WalletCards className="mx-auto size-12 text-violet-600"/><h1 className="mt-4 text-2xl font-black">Login to view your goal</h1><Link href="/login" className="mt-6 inline-flex w-full justify-center rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white">Login / Sign up</Link></section></main>;
 return <main className="min-h-screen bg-[#f6f7f9] px-3 py-4 text-[#17181b] sm:px-6 sm:py-6"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between px-1"><Link href="/goal" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft size={17}/> Goal</Link><button onClick={load} className="rounded-xl bg-white p-2.5 shadow-sm ring-1 ring-slate-200"><RefreshCw size={16}/></button></header>
 <section className="mt-4 rounded-[1.8rem] bg-white p-5 shadow-sm ring-1 ring-slate-100 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-400">Wallet · Goal</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">₹70 lakh</h1><p className="mt-1 text-sm text-slate-500">Your money path, maturity reinvestment and month-end sweep.</p></div><div className="grid size-14 place-items-center rounded-full bg-violet-50 text-violet-700"><Target size={25}/></div></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-slate-400">Current value</p><p className="mt-1 text-3xl font-black tracking-tight">{money(current)}</p></div><div className="text-right"><p className="text-xs text-slate-400">Progress</p><p className="mt-1 text-xl font-black">{progress.toFixed(1)}%</p></div></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-600" style={{width:`${progress}%`}}/></div></section>
 <section className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-[1.4rem] bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold text-slate-400">Auto-invest rate</p><p className="mt-1 text-2xl font-black">{AUTO_REINVEST_RATE}%</p><p className="mt-1 text-xs text-slate-500">Maturity + monthly surplus</p></div><div className="rounded-[1.4rem] bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold text-slate-400">Monthly surplus</p><p className="mt-1 text-2xl font-black">{money(salaryRemaining)}</p><p className="mt-1 text-xs text-slate-500">Income − recurring expenses</p></div><div className="rounded-[1.4rem] bg-white p-5 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold text-slate-400">₹70L target</p><p className="mt-1 text-2xl font-black">{target?fullDate(target.date):"Not reached"}</p><p className="mt-1 text-xs text-slate-500">First projected month</p></div></section>
 <section className="mt-4 rounded-[1.8rem] bg-white p-5 shadow-sm ring-1 ring-slate-100 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Growth</p><h2 className="mt-1 text-xl font-black">Path to ₹70L</h2></div><div className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700"><TrendingUp size={14}/> 8.1% reinvestment</div></div><div className="mt-5"><Chart points={points}/></div><p className="mt-3 text-xs text-slate-500">Existing investments use their entered rates until maturity. Maturity proceeds then move into the 8.1% pool. Recurring income minus expenses is invested monthly. Unknown maturity amounts are never invented.</p></section>
 <section className="mt-4 rounded-[1.8rem] bg-white p-5 shadow-sm ring-1 ring-slate-100 sm:p-6"><div className="flex items-start gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-violet-50 text-violet-700"><CalendarClock size={21}/></div><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Month-end</p><h2 className="mt-1 text-xl font-black">Account sweep</h2></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${settlementOpen?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{settlementOpen?"Open now":`Opens ${lastDay-4} ${today.toLocaleDateString("en-IN",{month:"short"})}`}</span></div>{!settlementOpen?<div className="mt-5 flex items-center gap-3 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600"><LockKeyhole size={18}/><span>Month-end settlement opens only during the last 5 days of the month.</span></div>:<div className="mt-5"><label className="text-xs font-bold text-slate-500">Amount available in account</label><div className="mt-2 flex items-center rounded-2xl bg-slate-50 px-4"><span className="text-slate-400">₹</span><input inputMode="numeric" value={accountBalance} onChange={e=>setAccountBalance(e.target.value.replace(/[^0-9.]/g,""))} placeholder="Enter month-end balance" className="w-full bg-transparent px-2 py-3.5 text-lg font-black outline-none"/></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">Current-month expenses</p><p className="mt-1 font-black">{money(expenseReserve)}</p></div><div className="rounded-2xl bg-violet-50 p-4"><p className="text-xs text-violet-600">Available to invest</p><p className="mt-1 font-black text-violet-900">{money(investAmount)}</p></div><div className="rounded-2xl bg-emerald-50 p-4"><p className="text-xs text-emerald-600">Return</p><p className="mt-1 font-black text-emerald-900">8.1% p.a.</p></div></div><div className="mt-4 flex gap-2"><button disabled={saving||!accountBalance} onClick={()=>saveSettlement(false)} className="flex-1 rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">Save</button><button disabled={saving||!accountBalance} onClick={()=>saveSettlement(true)} className="flex-1 rounded-2xl bg-violet-600 px-4 py-3 text-sm font-bold text-white">Deposit at 8.1%</button></div>{message&&<p className="mt-3 text-xs font-semibold text-emerald-700">{message}</p>}</div>}{currentSettlement?.deposited&&<div className="mt-4 flex items-center gap-2 rounded-2xl bg-emerald-50 p-3 text-xs font-bold text-emerald-700"><CheckCircle2 size={16}/> {money(Number(currentSettlement.invest_amount))} already marked for 8.1% reinvestment this month.</div>}</div></div></section>
 <section className="mt-4 rounded-[1.8rem] bg-white p-5 shadow-sm ring-1 ring-slate-100 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Accounts</p><h2 className="mt-1 text-xl font-black">Your investments</h2></div><WalletCards className="text-slate-300" size={23}/></div><div className="mt-3 divide-y divide-slate-100">{investments.map(i=><div key={i.id} className="flex items-center justify-between gap-4 py-4"><div className="min-w-0"><p className="truncate text-sm font-black">{i.name}</p><p className="mt-1 text-xs text-slate-500">{i.investment_type} · {Number(i.expected_rate||0)?`${i.expected_rate}% ${i.rate_period.toLowerCase()}`:"No return entered"}{i.maturity_on?` · Matures ${fullDate(dateOnly(i.maturity_on))}`:""}</p></div><p className="shrink-0 text-sm font-black">{money(currentValue(i,today))}</p></div>)}</div></section>
 <p className="px-2 py-5 text-center text-[11px] leading-5 text-slate-400">Projection uses your saved DB data only. Rates are converted correctly by period; future recurring activity changes are applied by their saved start/end dates.</p></div></main>;
}
