"use client";
import Link from "next/link";
import { cloneElement, type FormEvent, type ReactElement, type ReactNode, useEffect, useState } from "react";
import { ArrowLeft, RefreshCw, Save } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";
type Settings={target_amount:number;starting_capital:number;fd_rate:number;emergency_reserve:number};
export default function FinanceSettingsPage(){const [s,setS]=useState<Settings>({target_amount:7000000,starting_capital:0,fd_rate:8.1,emergency_reserve:0}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
async function load(){setLoading(true);const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user){setLoading(false);return}const {data,error}=await c.from("finance_settings").select("target_amount,starting_capital,fd_rate,emergency_reserve").eq("user_id",user.id).maybeSingle();if(error)setError(error.message);if(data)setS({target_amount:Number(data.target_amount),starting_capital:Number(data.starting_capital),fd_rate:Number(data.fd_rate)*100>20?Number(data.fd_rate):Number(data.fd_rate)*100,emergency_reserve:Number(data.emergency_reserve)});setLoading(false)}useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user){setError("Please sign in.");setSaving(false);return}const payload={user_id:user.id,target_amount:s.target_amount,starting_capital:s.starting_capital,fd_rate:Number(s.fd_rate)/100,emergency_reserve:s.emergency_reserve,updated_at:new Date().toISOString()};const {error}=await c.from("finance_settings").upsert(payload,{onConflict:"user_id"});if(error)setError(error.message);else setMessage("Finance settings saved.");setSaving(false)}
if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading settings…</main>;
return <main className="min-h-screen bg-slate-50 px-3 py-5 text-slate-900 sm:px-6"><div className="mx-auto max-w-3xl"><header className="flex items-center justify-between"><Link href="/goal" className="inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-bold ring-1 ring-slate-200"><ArrowLeft size={16}/>Finance</Link><b>Finance settings</b><button onClick={load} className="rounded-xl bg-white p-2.5 ring-1 ring-slate-200"><RefreshCw size={16}/></button></header>{error&&<p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}<form onSubmit={save} className="mt-5 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-xs font-black tracking-[.16em] text-violet-600">CONTROL PANEL</p><h1 className="mt-1 text-2xl font-black">Finance assumptions</h1><p className="mt-2 text-sm text-slate-500">These are your personal planning inputs, not guaranteed market or bank rates.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><F l="Financial target"><input type="number" min="1" value={s.target_amount} onChange={e=>setS({...s,target_amount:Number(e.target.value)})}/></F><F l="Starting capital"><input type="number" min="0" value={s.starting_capital} onChange={e=>setS({...s,starting_capital:Number(e.target.value)})}/></F><F l="Planning return / FD rate %"><input type="number" min="0" step="0.01" value={s.fd_rate} onChange={e=>setS({...s,fd_rate:Number(e.target.value)})}/></F><F l="Emergency reserve"><input type="number" min="0" value={s.emergency_reserve} onChange={e=>setS({...s,emergency_reserve:Number(e.target.value)})}/></F></div><button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-5 py-3 font-bold text-white"><Save size={17}/>{saving?"Saving…":"Save settings"}</button>{message&&<span className="ml-3 text-sm font-semibold text-emerald-700">{message}</span>}</form></div></main>}
function F({l,children}:{l:string;children:ReactNode}){return <label className="block text-xs font-bold">{l}{cloneElement(children as ReactElement<any>,{className:"mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal outline-none"})}</label>}
