"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase-browser";
import { ArrowRight, Brain, CheckCircle2, Clock3, LockKeyhole, RotateCcw, Target } from "lucide-react";
import { DEFAULT_LEARNING_MODE, LEARNING_MODES, LearningMode, modeLabel } from "@/lib/education/learning-modes";

type Question = { id:string; q:string; options:string[]; correct:number; topic:string; why:string };
type Attempt = { topic:string|null; questions:number; correct:number; duration_seconds:number; created_at:string };

const BANK: Question[] = [
 {id:"pct-1",q:"A price rises from ₹400 to ₹460. What is the percentage increase?",options:["10%","12%","15%","20%"],correct:2,topic:"Percentages",why:"The increase is ₹60. 60 ÷ 400 × 100 = 15%."},
 {id:"pct-2",q:"18% of 250 is:",options:["35","40","45","50"],correct:2,topic:"Percentages",why:"250 × 18 ÷ 100 = 45."},
 {id:"ratio-1",q:"A sum is divided in the ratio 3:5. If the total is 64, the smaller share is:",options:["18","24","30","40"],correct:1,topic:"Ratio & Proportion",why:"8 total parts; one part is 8; three parts are 24."},
 {id:"ratio-2",q:"If A:B = 2:3 and B:C = 4:5, A:C is:",options:["2:5","8:15","4:15","3:10"],correct:1,topic:"Ratio & Proportion",why:"Make B common: 8:12 and 12:15, giving 8:15."},
 {id:"work-1",q:"A can complete a job in 12 days. At the same rate, what fraction is completed in 3 days?",options:["1/3","1/4","1/6","1/9"],correct:1,topic:"Time & Work",why:"3 ÷ 12 = 1/4 of the job."},
 {id:"work-2",q:"5 equal-rate workers finish a job in 12 days. 10 workers need:",options:["3 days","6 days","10 days","24 days"],correct:1,topic:"Time & Work",why:"Workers × days stays constant: 5 × 12 = 10 × 6."},
 {id:"avg-1",q:"The average of 12, 18 and 24 is:",options:["16","18","20","22"],correct:1,topic:"Averages",why:"54 ÷ 3 = 18."},
 {id:"reason-1",q:"Which number comes next: 2, 6, 12, 20, 30, ?",options:["36","40","42","44"],correct:2,topic:"Reasoning",why:"Differences are 4, 6, 8, 10, then 12; 30 + 12 = 42."},
];

function readMode(){ if(typeof window === "undefined") return DEFAULT_LEARNING_MODE; const raw=new URLSearchParams(window.location.search).get("mode"); return LEARNING_MODES.some(x=>x.id===raw) ? raw as LearningMode : DEFAULT_LEARNING_MODE; }

export default function StudySession(){
 const supabase=createClient();
 const [user,setUser]=useState<any>(null); const [loading,setLoading]=useState(true); const [attempts,setAttempts]=useState<Attempt[]>([]); const [mistakes,setMistakes]=useState<any[]>([]);
 const [mode,setMode]=useState<LearningMode>(readMode()); const [questions,setQuestions]=useState<Question[]>([]); const [index,setIndex]=useState(0); const [answer,setAnswer]=useState<number|null>(null); const [started,setStarted]=useState<number|null>(null); const [done,setDone]=useState(false); const [score,setScore]=useState(0); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");

 useEffect(()=>{const sync=()=>setMode(readMode());window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync)},[]);
 useEffect(()=>{(async()=>{const {data:{user:u}}=await supabase.auth.getUser();setUser(u);if(u){const [a,m]=await Promise.all([supabase.from("study_attempts").select("topic,questions,correct,duration_seconds,created_at").eq("user_id",u.id).order("created_at",{ascending:false}).limit(200),supabase.from("study_mistakes").select("topic,created_at,resolved_at").eq("user_id",u.id).is("resolved_at",null).limit(100)]);setAttempts(a.data||[]);setMistakes(m.data||[])}setLoading(false)})()},[]);

 const topicPriority=useMemo(()=>{const misses=new Map<string,number>();mistakes.forEach(x=>misses.set(x.topic,(misses.get(x.topic)||0)+1));const stats=new Map<string,{q:number;c:number;last:number}>();attempts.forEach(x=>{if(!x.topic)return;const s=stats.get(x.topic)||{q:0,c:0,last:0};s.q+=x.questions;s.c+=x.correct;s.last=Math.max(s.last,new Date(x.created_at).getTime());stats.set(x.topic,s)});return [...new Set(BANK.map(q=>q.topic))].sort((a,b)=>{const ma=misses.get(a)||0,mb=misses.get(b)||0;if(mb!==ma)return mb-ma;const sa=stats.get(a),sb=stats.get(b);const pa=sa?.q?sa.c/sa.q:0,pb=sb?.q?sb.c/sb.q:0;if(pa!==pb)return pa-pb;return (sa?.last||0)-(sb?.last||0)})},[attempts,mistakes]);

 function buildSession(){let pool=[...BANK];if(mode==="subject_first"){pool=pool.filter(q=>q.topic===topicPriority[0]||q.topic===topicPriority[1]);}else if(mode==="weak_area_first"||mode==="revision_first"){pool.sort((a,b)=>topicPriority.indexOf(a.topic)-topicPriority.indexOf(b.topic));}else if(mode==="assessment_first"||mode==="mock_first"){pool.sort(()=>Math.random()-.5)}else if(mode==="practice_first"){pool.sort((a,b)=>topicPriority.indexOf(a.topic)-topicPriority.indexOf(b.topic));}setQuestions(pool.slice(0,Math.min(8,pool.length)));setIndex(0);setAnswer(null);setScore(0);setDone(false);setStarted(Date.now());setMessage("")}
 useEffect(()=>{if(user&&!loading)buildSession()},[user,loading,mode]);

 async function next(){if(answer===null||!questions[index])return;const current=questions[index];const newScore=score+(answer===current.correct?1:0);setScore(newScore);if(index+1<questions.length){setIndex(index+1);setAnswer(null);return;}const elapsed=started?Math.round((Date.now()-started)/1000):0;setSaving(true);const {data:attempt,error}=await supabase.from("study_attempts").insert({user_id:user.id,target_type:"si",activity_type:"practice",topic:mode==="subject_first"?current.topic:null,questions:questions.length,correct:newScore,score:newScore,duration_seconds:elapsed,metadata:{learning_mode:mode,question_ids:questions.map(q=>q.id),topics:questions.map(q=>q.topic)}}).select("id").single();if(!error&&attempt){const wrong=questions.filter((q,i)=>{if(i<index)return false;return i===index&&answer!==q.correct});if(answer!==current.correct)await supabase.from("study_mistakes").insert({user_id:user.id,attempt_id:attempt.id,topic:current.topic,question:current.q,explanation:current.why})}setSaving(false);setDone(true)}

 if(loading)return <main className="min-h-screen grid place-items-center">Loading your study session…</main>;
 if(!user)return <main className="min-h-screen grid place-items-center px-6"><div className="max-w-md text-center"><LockKeyhole className="mx-auto"/><h1 className="mt-4 text-3xl font-black">Login to start your adaptive session</h1><p className="mt-3 text-sm leading-6 text-black/55">Your attempts, mistakes and progress are private to your account.</p><Link href="/login" className="mt-6 inline-flex rounded-xl bg-black px-5 py-3 text-sm font-black text-white">Login / Sign up</Link></div></main>;
 const q=questions[index];
 return <main className="min-h-screen bg-white text-black"><header className="border-b border-black/10 bg-black text-white"><div className="mx-auto max-w-4xl px-5 py-7"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.18em] text-white/60"><Brain size={16}/> Adaptive Education</div><Link href="/education/modes" className="text-xs font-bold text-white/60 hover:text-white">Change mode</Link></div><h1 className="mt-3 text-3xl font-black">{modeLabel(mode)}</h1><p className="mt-1 text-sm text-white/55">The next questions are selected from your current evidence.</p></div></header>
 <section className="mx-auto max-w-4xl px-5 py-8">
  <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-4"><Target size={16}/><p className="mt-2 text-[10px] font-black uppercase text-black/40">Priority</p><p className="mt-1 font-black">{topicPriority[0]||"Coverage"}</p></div><div className="rounded-xl border p-4"><Clock3 size={16}/><p className="mt-2 text-[10px] font-black uppercase text-black/40">Session</p><p className="mt-1 font-black">{questions.length} questions</p></div><div className="rounded-xl border p-4"><RotateCcw size={16}/><p className="mt-2 text-[10px] font-black uppercase text-black/40">Evidence</p><p className="mt-1 font-black">{attempts.length} attempts saved</p></div></div>
  {done?<div className="rounded-3xl border p-7"><CheckCircle2 size={28}/><p className="mt-4 text-sm font-black uppercase tracking-wider text-black/40">Session complete</p><h2 className="mt-2 text-4xl font-black">{score} / {questions.length}</h2><p className="mt-3 text-sm leading-6 text-black/55">Your result has been saved. The next session can use this evidence to change topic priority.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={buildSession} className="rounded-xl bg-black px-5 py-3 text-sm font-black text-white">Run another session</button><Link href="/study" className="rounded-xl border px-5 py-3 text-sm font-black">Open study dashboard</Link></div></div>:q?<div className="rounded-3xl border p-6 sm:p-8"><div className="flex items-center justify-between text-xs font-black text-black/40"><span>Question {index+1} of {questions.length}</span><span>{q.topic}</span></div><h2 className="mt-7 text-2xl font-black leading-tight">{q.q}</h2><div className="mt-6 grid gap-3">{q.options.map((x,i)=><button key={x} onClick={()=>setAnswer(i)} className={`rounded-xl border p-4 text-left text-sm font-bold ${answer===i?"border-black bg-black text-white":"border-black/10 hover:border-black"}`}>{String.fromCharCode(65+i)}. {x}</button>)}</div><div className="mt-7 flex items-center justify-between gap-4"><span className="text-xs text-black/45">{message}</span><button disabled={answer===null||saving} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-black text-white disabled:opacity-30">{saving?"Saving…":index+1===questions.length?"Finish":"Next"}<ArrowRight size={16}/></button></div></div>:null}
 </section></main>;
}
