export type DeveloperToolSeo = {
  slug: string;
  name: string;
  category: string;
  description: string;
  keywords: string[];
  useCases: string[];
};

export const developerToolSeo: DeveloperToolSeo[] = [
  { slug: "json-formatter", name: "JSON Formatter", category: "JSON & Data", description: "Format, validate, and pretty-print JSON online with a fast browser-based developer tool.", keywords: ["json formatter", "json beautifier", "format json online", "json validator"], useCases: ["Format minified JSON", "Spot invalid JSON structure", "Pretty-print API responses"] },
  { slug: "json-minifier", name: "JSON Minifier", category: "JSON & Data", description: "Minify JSON online by removing unnecessary whitespace while preserving the data.", keywords: ["json minifier", "minify json", "compress json online"], useCases: ["Reduce JSON payload size", "Prepare compact API data", "Clean generated JSON"] },
  { slug: "json-to-typescript", name: "JSON to TypeScript", category: "JSON & Data", description: "Convert JSON examples into TypeScript interfaces quickly in your browser.", keywords: ["json to typescript", "json to ts", "typescript interface generator"], useCases: ["Create interfaces from API responses", "Prototype TypeScript models", "Speed up frontend development"] },
  { slug: "json-to-csv", name: "JSON to CSV", category: "JSON & Data", description: "Convert arrays of JSON objects into CSV data for spreadsheets, scripts, and data workflows.", keywords: ["json to csv", "json csv converter", "convert json to csv"], useCases: ["Export API data", "Prepare spreadsheet imports", "Convert structured records"] },
  { slug: "yaml-to-json", name: "YAML to JSON", category: "JSON & Data", description: "Convert simple YAML configuration data into readable JSON in your browser.", keywords: ["yaml to json", "yaml json converter", "convert yaml"], useCases: ["Convert configuration snippets", "Move data between formats", "Inspect YAML values"] },
  { slug: "base64-encode", name: "Base64 Encoder", category: "Encoders", description: "Encode UTF-8 text to Base64 locally without sending your data to a server.", keywords: ["base64 encoder", "base64 encode online", "text to base64"], useCases: ["Encode API values", "Create data URLs", "Prepare encoded payloads"] },
  { slug: "base64-decode", name: "Base64 Decoder", category: "Encoders", description: "Decode Base64 text back to readable UTF-8 text directly in your browser.", keywords: ["base64 decoder", "base64 decode online", "decode base64"], useCases: ["Inspect encoded strings", "Decode API payloads", "Read Base64 text"] },
  { slug: "url-encode", name: "URL Encoder", category: "Encoders", description: "Percent-encode URLs, query values, and text for safe URL usage.", keywords: ["url encoder", "url encode online", "percent encode"], useCases: ["Encode query parameters", "Build safe URLs", "Encode URL components"] },
  { slug: "url-decode", name: "URL Decoder", category: "Encoders", description: "Decode percent-encoded URL strings and query values quickly.", keywords: ["url decoder", "url decode online", "percent decode"], useCases: ["Read encoded URLs", "Inspect query parameters", "Decode URL components"] },
  { slug: "jwt-decoder", name: "JWT Decoder & Inspector", category: "Security", description: "Decode JWT headers and payloads locally and inspect token claims. Signature verification is not performed.", keywords: ["jwt decoder", "jwt inspector", "decode jwt online", "jwt parser"], useCases: ["Inspect JWT claims", "Debug authentication tokens", "Understand token headers"] },
  { slug: "sha256-hash", name: "SHA-256 Hash Generator", category: "Security", description: "Generate a SHA-256 hash from text using browser cryptography.", keywords: ["sha256 generator", "sha-256 hash", "sha256 online"], useCases: ["Create content digests", "Verify deterministic hashes", "Test cryptographic workflows"] },
  { slug: "basic-auth-header", name: "Basic Auth Header Generator", category: "Security", description: "Generate an HTTP Basic Authorization header from a username and password.", keywords: ["basic auth header", "authorization basic generator", "http basic auth"], useCases: ["Test API requests", "Build Authorization headers", "Debug HTTP authentication"] },
  { slug: "uuid-generator", name: "UUID v4 Generator", category: "Generators", description: "Generate cryptographically random UUID v4 identifiers instantly in your browser.", keywords: ["uuid generator", "uuid v4 generator", "random uuid"], useCases: ["Create database IDs", "Generate test identifiers", "Create unique request IDs"] },
  { slug: "random-string-generator", name: "Random String Generator", category: "Generators", description: "Generate random alphanumeric strings for testing, fixtures, and development workflows.", keywords: ["random string generator", "random text generator", "string generator"], useCases: ["Create test data", "Generate fixtures", "Create random identifiers"] },
  { slug: "query-string-parser", name: "Query String Parser", category: "Web & URL", description: "Parse URL query parameters into structured JSON for easier debugging and development.", keywords: ["query string parser", "url query parser", "query parameter parser"], useCases: ["Inspect URLs", "Debug query parameters", "Convert query strings to JSON"] },
  { slug: "http-header-parser", name: "HTTP Header Parser", category: "API & Network", description: "Parse raw HTTP headers into structured JSON for API and web debugging.", keywords: ["http header parser", "headers parser", "http headers online"], useCases: ["Inspect response headers", "Debug API requests", "Convert headers to JSON"] },
  { slug: "curl-builder", name: "cURL Builder", category: "API & Network", description: "Create a cURL GET request from a URL for quick API testing and debugging.", keywords: ["curl builder", "curl command generator", "api curl generator"], useCases: ["Generate cURL commands", "Test API endpoints", "Document simple requests"] },
  { slug: "html-escape", name: "HTML Escape Tool", category: "Web & URL", description: "Escape HTML special characters safely for source code, templates, and debugging.", keywords: ["html escape", "html encoder", "escape html online"], useCases: ["Escape HTML snippets", "Prepare safe text", "Debug encoded markup"] },
  { slug: "html-unescape", name: "HTML Unescape Tool", category: "Web & URL", description: "Decode common HTML entities back into readable characters.", keywords: ["html unescape", "html decoder", "decode html entities"], useCases: ["Decode HTML entities", "Inspect encoded content", "Clean copied markup"] },
  { slug: "regex-tester", name: "Regex Tester", category: "Text & Regex", description: "Test regular expressions against text and inspect matches directly in your browser.", keywords: ["regex tester", "regex test online", "regular expression tester"], useCases: ["Test patterns", "Debug regex", "Inspect matches"] },
  { slug: "text-diff", name: "Text Diff Tool", category: "Text & Regex", description: "Compare two blocks of text and identify line-level changes quickly.", keywords: ["text diff", "text comparison tool", "diff checker"], useCases: ["Compare configuration", "Review text changes", "Debug output differences"] },
  { slug: "slug-generator", name: "Slug Generator", category: "Text & Regex", description: "Convert titles and phrases into clean, readable URL slugs for websites and content.", keywords: ["slug generator", "url slug generator", "seo slug generator"], useCases: ["Create SEO-friendly slugs", "Clean article URLs", "Normalize titles"] },
  { slug: "text-counter", name: "Word & Character Counter", category: "Text & Regex", description: "Count words, characters, characters without spaces, and lines instantly.", keywords: ["word counter", "character counter", "text counter"], useCases: ["Check content length", "Count words", "Measure text"] },
  { slug: "unix-timestamp-converter", name: "Unix Timestamp Converter", category: "Time & Converters", description: "Convert Unix timestamps into ISO 8601, UTC, and millisecond values.", keywords: ["unix timestamp converter", "timestamp converter", "epoch converter"], useCases: ["Debug timestamps", "Convert API dates", "Inspect epoch values"] },
  { slug: "number-base-converter", name: "Number Base Converter", category: "Time & Converters", description: "Convert integers between binary, octal, decimal, and hexadecimal representations.", keywords: ["number base converter", "binary converter", "hex converter", "decimal converter"], useCases: ["Convert binary values", "Inspect hexadecimal", "Learn number systems"] },
  { slug: "meta-tag-generator", name: "Meta Tag Generator", category: "SEO & Website", description: "Generate a practical HTML meta tag block for titles, descriptions, Open Graph, and robots directives.", keywords: ["meta tag generator", "seo meta tag generator", "og meta tags"], useCases: ["Create SEO metadata", "Prepare Open Graph tags", "Improve page snippets"] },
  { slug: "robots-txt-generator", name: "Robots.txt Generator", category: "SEO & Website", description: "Generate a simple robots.txt file with crawler rules and an optional sitemap URL.", keywords: ["robots txt generator", "robots.txt generator", "robots file generator"], useCases: ["Create crawler rules", "Publish a sitemap reference", "Set basic crawl access"] },
];

export const developerToolBySlug = Object.fromEntries(developerToolSeo.map((tool) => [tool.slug, tool]));

export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://targetbud.vercel.app";
