"use client";

import { useEffect, useMemo, useState } from "react";
import { Braces, Check, ChevronRight, Clipboard, Code2, Download, FileJson, Hash, Link2, LockKeyhole, Menu, Play, RefreshCw, Search, ShieldCheck, Sparkles, Type, X, WandSparkles, Webhook, Regex, Clock3, FileCode2 } from "lucide-react";

type Tool = { id:string; name:string; category:string; description:string; placeholder:string; run:(input:string)=>string; };

const b64e=(v:string)=>{try{return btoa(unescape(encodeURIComponent(v)))}catch{return "Unable to encode input."}};
const b64d=(v:string)=>{try{return decodeURIComponent(escape(atob(v.trim())))}catch{return "Invalid Base64 input."}};
const parseJson=(v:string)=>{try{return JSON.parse(v)}catch{throw new Error("Invalid JSON. Check quotes, commas, brackets and braces.")}};
const formatJson=(v:string)=>JSON.stringify(parseJson(v),null,2);
const minJson=(v:string)=>JSON.stringify(parseJson(v));
const jsonToTs=(v:string)=>{const x=parseJson(v); const type=(a:any,n="Root"):string=>{if(a===null)return "null";if(Array.isArray(a))return a.length?`${type(a[0],n)}[]`:"unknown[]";if(typeof a==="object"){return `interface ${n} {\n${Object.entries(a).map(([k,val])=>`  ${k}: ${type(val,k.replace(/[^a-zA-Z0-9]/g,"")||"Value")};`).join("\n")}\n}`}return typeof a==="number"?(Number.isInteger(a)?"number":"number"):typeof a};return type(x)};
const jsonCsv=(v:string)=>{const x=parseJson(v);const rows=Array.isArray(x)?x:[x];if(!rows.length)return "";const keys=Array.from(new Set(rows.flatMap((r:any)=>typeof r==="object"&&r?Object.keys(r):[])));const esc=(a:any)=>`"${String(a??"").replace(/"/g,'""')}"`;return [keys.map(esc).join(","),...rows.map((r:any)=>keys.map(k=>esc(typeof r?.[k]==="object"?JSON.stringify(r[k]):r?.[k])).join(","))].join("\n")};
const yamlJson=(v:string)=>{try{const o:any={};v.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).forEach(s=>{const i=s.indexOf(":");if(i>0){const k=s.slice(0,i).trim();let val=s.slice(i+1).trim();if(val==="true"||val==="false")o[k]=val==="true";else if(!Number.isNaN(Number(val))&&val!=="")o[k]=Number(val);else o[k]=val.replace(/^['"]|['"]$/g,"")}});return JSON.stringify(o,null,2)}catch{return "Unable to parse simple YAML."}};
const urlE=(v:string)=>encodeURIComponent(v);const urlD=(v:string)=>{try{return decodeURIComponent(v)}catch{return "Invalid URL encoding."}};
const jwt=(v:string)=>{try{const p=v.trim().split(".");if(p.length!==3)throw 0;const decode=(s:string)=>JSON.parse(atob(s.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(s.length/4)*4,"=")));return `Header\n${JSON.stringify(decode(p[0]),null,2)}\n\nPayload\n${JSON.stringify(decode(p[1]),null,2)}\n\nNOTE: This inspector decodes the token; it does not verify the signature.`}catch{return "Invalid JWT. Expected three valid base64url segments."}};
const query=(v:string)=>JSON.stringify(Object.fromEntries(new URLSearchParams(v.trim().replace(/^\?/,""))),null,2);
const htmlE=(v:string)=>v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");
const htmlD=(v:string)=>v.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,"&");
const slug=(v:string)=>v.toLowerCase().trim().replace(/[^\w\s-]/g,"").replace(/[\s_-]+/g,"-").replace(/^-+|-+$/g,"");
const textCount=(v:string)=>`Words: ${(v.trim().match(/\S+/g)||[]).length}\nCharacters: ${v.length}\nCharacters without spaces: ${v.replace(/\s/g,"").length}\nLines: ${v?v.split(/\r?\n/).length:0}`;
const regex=(v:string)=>{const i=v.indexOf("\n");if(i<0)return "Enter a pattern on line 1 and test text below it.\nExample:\n/^hello/i\nhello world";const p=v.slice(0,i),t=v.slice(i+1);try{const m=p.match(/^\/(.*)\/([dgimsuvy]*)$/);const r=m?new RegExp(m[1],m[2]):new RegExp(p);const hits=[...t.matchAll(new RegExp(r.source,r.flags.includes("g")?r.flags:r.flags+"g"))];return `Matches: ${hits.length}\n\n${hits.map((x,n)=>`${n+1}. ${x[0]}${x.index!==undefined?` @ ${x.index}`:""}`).join("\n")||"No matches."}`}catch{return "Invalid regular expression."}};
const diff=(v:string)=>{const [a,b]=v.split(/\n---+\n/);if(b===undefined)return "Put two texts separated by a line containing ---";const A=a.split(/\r?\n/),B=b.split(/\r?\n/);return B.map((line,i)=>line===A[i]?`  ${line}`:`- ${A[i]??""}\n+ ${line}`).join("\n")};
const unix=(v:string)=>{const n=Number(v.trim());if(!Number.isFinite(n))return "Enter a Unix timestamp.";const d=new Date(n<1e12?n*1000:n);return `ISO 8601: ${d.toISOString()}\nUTC: ${d.toUTCString()}\nMilliseconds: ${d.getTime()}`};
const base=(v:string)=>{const [n,b]=v.trim().split(/\s+/);const x=parseInt(n,10),radix=parseInt(b||"10",10);if(!Number.isFinite(x)||!Number.isInteger(radix)||radix<2||radix>36)return "Enter: number base (2–36), e.g. 255 16";return [2,8,10,16].map(r=>`Base ${r}: ${x.toString(r)}`).join("\n")};
const headers=(v:string)=>{const o:any={};v.split(/\r?\n/).forEach(l=>{const i=l.indexOf(":");if(i>0)o[l.slice(0,i).trim()]=l.slice(i+1).trim()});return JSON.stringify(o,null,2)};
const curl=(v:string)=>{try{const u=new URL(v.trim());return `curl -X GET '${u.toString()}' -H 'Accept: application/json'`}catch{return "Enter a valid URL."}};
const basic=(v:string)=>{const i=v.indexOf(":");if(i<1)return "Enter username:password";return `Authorization: Basic ${btoa(v.slice(0,i)+":"+v.slice(i+1))}`};
const meta=(v:string)=>`<title>${v||"Page title"}</title>\n<meta name="description" content="${v||"Description"}">\n<meta property="og:title" content="${v||"Page title"}">\n<meta property="og:description" content="${v||"Description"}">\n<meta name="robots" content="index,follow">`;
const robots=(v:string)=>`User-agent: *\nAllow: /\n${v?`Sitemap: ${v.replace(/\/$/,"")}/sitemap.xml`:"# Add your sitemap URL here"}`;
const tools:Tool[]=[
{id:"json-format",name:"JSON Formatter",category:"JSON & Data",description:"Format and validate JSON with readable indentation.",placeholder:'{\n  "name": "TargetBud",\n  "active": true\n}',run:formatJson},
{id:"json-minify",name:"JSON Minifier",category:"JSON & Data",description:"Minify valid JSON without changing its data.",placeholder:'{ "name": "TargetBud", "active": true }',run:minJson},
{id:"json-ts",name:"JSON → TypeScript",category:"JSON & Data",description:"Generate a TypeScript interface from JSON.",placeholder:'{"name":"TargetBud","active":true}',run:jsonToTs},
{id:"json-csv",name:"JSON → CSV",category:"JSON & Data",description:"Convert an array of JSON objects to CSV.",placeholder:'[{"name":"Ada","role":"Developer"}]',run:jsonCsv},
{id:"yaml-json",name:"YAML → JSON",category:"JSON & Data",description:"Convert simple key-value YAML into JSON.",placeholder:"name: TargetBud\nactive: true",run:yamlJson},
{id:"base64",name:"Base64 Encode",category:"Encoders",description:"Encode UTF-8 text locally as Base64.",placeholder:"Text to encode…",run:b64e},
{id:"base64-decode",name:"Base64 Decode",category:"Encoders",description:"Decode Base64 into UTF-8 text.",placeholder:"VGFyZ2V0QnVk",run:b64d},
{id:"url-encode",name:"URL Encode",category:"Encoders",description:"Percent-encode text for URLs and query values.",placeholder:"hello world?",run:urlE},
{id:"url-decode",name:"URL Decode",category:"Encoders",description:"Decode percent-encoded text.",placeholder:"hello%20world%3F",run:urlD},
{id:"jwt",name:"JWT Inspector",category:"Security",description:"Decode JWT header and payload locally; signature is not verified.",placeholder:"Paste a JWT…",run:jwt},
{id:"sha256",name:"SHA-256 Hash",category:"Security",description:"Create a SHA-256 digest in the browser.",placeholder:"Text to hash…",run:(v)=>"Use the browser crypto API to hash this input. Run is available in supported browsers."},
{id:"basic-auth",name:"Basic Auth Header",category:"Security",description:"Create an HTTP Basic Authorization header.",placeholder:"username:password",run:basic},
{id:"uuid",name:"UUID v4 Generator",category:"Generators",description:"Generate a cryptographically random UUID v4.",placeholder:"No input required",run:()=>crypto.randomUUID()},
{id:"random",name:"Random String",category:"Generators",description:"Generate a random alphanumeric string. Enter a length from 1–256.",placeholder:"32",run:(v)=>{const n=Math.min(256,Math.max(1,parseInt(v)||32));const chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";const a=new Uint32Array(n);crypto.getRandomValues(a);return Array.from(a,x=>chars[x%chars.length]).join("")}},
{id:"query",name:"Query String Parser",category:"Web & URL",description:"Convert URL query parameters into JSON.",placeholder:"?name=TargetBud&mode=tools",run:query},
{id:"headers",name:"HTTP Header Parser",category:"API & Network",description:"Parse raw HTTP headers into JSON.",placeholder:"Content-Type: application/json\nAccept: */*",run:headers},
{id:"curl",name:"cURL Builder",category:"API & Network",description:"Start a cURL GET request from a URL.",placeholder:"https://api.example.com/users",run:curl},
{id:"html-escape",name:"HTML Escape",category:"Web & URL",description:"Escape special HTML characters.",placeholder:"<section>Hello</section>",run:htmlE},
{id:"html-decode",name:"HTML Unescape",category:"Web & URL",description:"Decode common HTML entities.",placeholder:"&lt;section&gt;Hello&lt;/section&gt;",run:htmlD},
{id:"regex",name:"Regex Tester",category:"Text & Regex",description:"Test a regular expression against text. Put the pattern on line 1 and text below.",placeholder:"/TargetBud/gi\nTargetBud developer tools",run:regex},
{id:"diff",name:"Text Diff",category:"Text & Regex",description:"Compare two line-based texts locally.",placeholder:"Original text\nline two\n---\nOriginal text\nchanged line",run:diff},
{id:"slug",name:"Slug Generator",category:"Text & Regex",description:"Convert a title into a clean URL slug.",placeholder:"My Developer Tools Page",run:slug},
{id:"counter",name:"Text Counter",category:"Text & Regex",description:"Count words, characters and lines instantly.",placeholder:"Type or paste text…",run:textCount},
{id:"timestamp",name:"Unix Timestamp",category:"Time & Converters",description:"Convert a Unix timestamp to readable UTC and ISO time.",placeholder:"1757548800",run:unix},
{id:"number-base",name:"Number Base Converter",category:"Time & Converters",description:"Convert an integer into common number bases.",placeholder:"255 10",run:base},
{id:"meta",name:"Meta Tag Generator",category:"SEO & Website",description:"Generate a minimal SEO and Open Graph meta block.",placeholder:"TargetBud Developer Tools",run:meta},
{id:"robots",name:"Robots.txt Generator",category:"SEO & Website",description:"Generate a simple robots.txt file.",placeholder:"https://example.com",run:robots},
];
const categories=["All tools","JSON & Data","Encoders","Security","Generators","Web & URL","API & Network","Text & Regex","Time & Converters","SEO & Website"];
const icons:any={"All tools":WandSparkles,"JSON & Data":Braces,Encoders:Link2,Security:LockKeyhole,Generators:Sparkles,"Web & URL":Code2,"API & Network":Webhook,"Text & Regex":Regex,"Time & Converters":Clock3,"SEO & Website":FileCode2};

export default function DeveloperTools(){
const [q,setQ]=useState("");const [cat,setCat]=useState("All tools");const [selected,setSelected]=useState("json-format");const [input,setInput]=useState(tools[0].placeholder);const [output,setOutput]=useState("");const [copied,setCopied]=useState(false);const [mobile,setMobile]=useState(false);const [favorites,setFavorites]=useState<string[]>([]);const [recent,setRecent]=useState<string[]>([]);
const filtered=useMemo(()=>tools.filter(t=>(cat==="All tools"||t.category===cat)&&`${t.name} ${t.category} ${t.description}`.toLowerCase().includes(q.toLowerCase())),[q,cat]);const current=tools.find(t=>t.id===selected)||tools[0];
useEffect(()=>{try{setFavorites(JSON.parse(localStorage.getItem("tb-dev-favorites")||"[]"));setRecent(JSON.parse(localStorage.getItem("tb-dev-recent")||"[]"))}catch{}},[]);
function choose(id:string){const t=tools.find(x=>x.id===id);if(!t)return;setSelected(id);setInput(t.placeholder);setOutput("");setCopied(false);setMobile(false);const r=[id,...recent.filter(x=>x!==id)].slice(0,6);setRecent(r);localStorage.setItem("tb-dev-recent",JSON.stringify(r))}
function run(){try{setOutput(current.run(input));}catch(e:any){setOutput(e?.message||"Unable to process input.")}setCopied(false)}
async function copy(){if(!output)return;await navigator.clipboard?.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),1400)}
function download(){if(!output)return;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([output],{type:"text/plain"}));a.download=`${current.id}-output.txt`;a.click()}
function toggleFav(){const next=favorites.includes(current.id)?favorites.filter(x=>x!==current.id):[...favorites,current.id];setFavorites(next);localStorage.setItem("tb-dev-favorites",JSON.stringify(next))}
return <main className="min-h-screen bg-white text-[#111]"><div className="mx-auto max-w-[1540px] px-4 py-5 sm:px-6 lg:px-8">
<header className="border-b border-[#e5e5e5] pb-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-[#777]"><Code2 className="size-4"/>TargetBud Developer Tools</div><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">Developer workspace</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#666]">A focused toolkit for JSON, APIs, encoding, security, web development, text, converters and SEO.</p></div><div className="flex items-center gap-2 rounded-full border border-[#ddd] px-3 py-2 text-xs font-semibold text-[#555]"><ShieldCheck className="size-4"/>Local-first</div></div></header>
<div className="mt-5 flex gap-5"><aside className="hidden w-[255px] shrink-0 lg:block"><div className="sticky top-5"><div className="mb-3 flex justify-between px-1"><span className="text-xs font-bold uppercase tracking-wider text-[#777]">Tool directory</span><span className="text-xs text-[#999]">{tools.length}</span></div><div className="relative mb-3"><Search className="absolute left-3 top-3 size-4 text-[#999]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools" className="h-10 w-full rounded-lg border border-[#ddd] bg-[#fafafa] pl-9 pr-3 text-sm outline-none focus:border-[#111]"/></div><div className="space-y-1">{categories.map(c=>{const I=icons[c];return <button key={c} onClick={()=>setCat(c)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium ${cat===c?"bg-[#111] text-white":"text-[#555] hover:bg-[#f3f3f3]"}`}><I className="size-4"/><span>{c}</span><span className="ml-auto text-xs opacity-50">{c==="All tools"?tools.length:tools.filter(t=>t.category===c).length}</span></button>})}</div>{recent.length>0&&<div className="mt-7 border-t border-[#eee] pt-5"><div className="mb-2 px-1 text-xs font-bold uppercase tracking-wider text-[#777]">Recent</div>{recent.map(id=>{const t=tools.find(x=>x.id===id);return t?<button key={id} onClick={()=>choose(id)} className="block w-full truncate rounded px-2 py-2 text-left text-xs text-[#666] hover:bg-[#f5f5f5]">{t.name}</button>:null})}</div>}</div></aside>
<section className="min-w-0 flex-1"><div className="mb-4 flex gap-2 lg:hidden"><button onClick={()=>setMobile(!mobile)} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#ddd] px-3 text-sm font-semibold"><Menu className="size-4"/>Tools</button><div className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-[#999]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tools" className="h-10 w-full rounded-lg border border-[#ddd] pl-9 pr-3 text-sm outline-none focus:border-[#111]"/></div></div>{mobile&&<div className="mb-4 rounded-xl border border-[#ddd] bg-[#fafafa] p-2 lg:hidden"><div className="flex justify-between px-2 py-1"><b className="text-xs uppercase tracking-wider text-[#777]">Choose tool</b><button onClick={()=>setMobile(false)}><X className="size-4"/></button></div>{filtered.map(t=><button key={t.id} onClick={()=>choose(t.id)} className={`block w-full rounded-lg px-3 py-2 text-left text-sm ${selected===t.id?"bg-[#111] text-white":"hover:bg-white"}`}>{t.name}<span className="ml-2 text-xs opacity-50">{t.category}</span></button>)}</div>}
<div className="mb-4 flex flex-wrap items-center gap-2 text-xs text-[#777]"><span>Developer Tools</span><ChevronRight className="size-3"/><span>{current.category}</span><ChevronRight className="size-3"/><b className="text-[#222]">{current.name}</b></div>
<div className="overflow-hidden rounded-2xl border border-[#ddd] bg-white shadow-[0_10px_35px_rgba(0,0,0,.06)]"><div className="border-b border-[#e8e8e8] px-4 py-4 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-lg border border-[#ddd] bg-[#fafafa]"><Hash className="size-4"/></div><div><h2 className="text-lg font-bold">{current.name}</h2><p className="text-xs text-[#777]">{current.category}</p></div></div><p className="mt-3 max-w-2xl text-sm text-[#666]">{current.description}</p></div><button onClick={toggleFav} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${favorites.includes(current.id)?"bg-[#111] text-white":"border-[#ddd] text-[#555]"}`}>{favorites.includes(current.id)?"★ Saved":"☆ Save tool"}</button></div></div>
<div className="border-b border-[#eee] bg-[#fafafa] px-4 py-3 sm:px-6"><div className="flex flex-wrap gap-2">{filtered.slice(0,8).map(t=><button key={t.id} onClick={()=>choose(t.id)} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${selected===t.id?"border-[#111] bg-[#111] text-white":"border-[#ddd] bg-white text-[#666] hover:border-[#999]"}`}>{t.name}</button>)}</div></div>
<div className="p-4 sm:p-6"><div className="grid gap-4 xl:grid-cols-2"><div className="overflow-hidden rounded-xl border border-[#dcdcdc] bg-[#fafafa]"><div className="flex items-center justify-between border-b border-[#e5e5e5] px-3 py-2.5"><div><b className="text-xs uppercase tracking-wider text-[#555]">Input</b><span className="ml-2 text-[11px] text-[#999]">{input.length} chars</span></div><button onClick={()=>setInput(current.placeholder)} className="text-xs font-semibold text-[#666]">Reset</button></div><textarea value={input} onChange={e=>setInput(e.target.value)} spellCheck={false} className="min-h-[380px] w-full resize-y bg-[#fafafa] p-4 font-mono text-[13px] leading-6 outline-none" placeholder={current.placeholder}/></div><div className="overflow-hidden rounded-xl border border-[#dcdcdc] bg-[#fafafa]"><div className="flex items-center justify-between border-b border-[#e5e5e5] px-3 py-2.5"><div><b className="text-xs uppercase tracking-wider text-[#555]">Output</b><span className="ml-2 text-[11px] text-[#999]">{output.length} chars</span></div><div className="flex gap-1"><button disabled={!output} onClick={copy} className="rounded-md p-1.5 hover:bg-[#eee] disabled:opacity-30" title="Copy"><Clipboard className="size-4"/></button><button disabled={!output} onClick={download} className="rounded-md p-1.5 hover:bg-[#eee] disabled:opacity-30" title="Download"><Download className="size-4"/></button></div></div><pre className="min-h-[380px] max-h-[600px] overflow-auto whitespace-pre-wrap break-words bg-[#fafafa] p-4 font-mono text-[13px] leading-6 text-[#222]">{output||"Output will appear here after you run the tool."}</pre></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={run} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#111] px-4 text-sm font-semibold text-white hover:bg-black"><Play className="size-4"/>Run tool</button><button onClick={()=>{setInput("");setOutput("")}} className="inline-flex h-10 items-center gap-2 rounded-lg border border-[#ddd] px-4 text-sm font-semibold text-[#555] hover:bg-[#f5f5f5]"><RefreshCw className="size-4"/>Clear</button></div>{copied&&<span className="flex items-center gap-1 text-xs font-semibold text-[#555]"><Check className="size-4"/>Copied</span>}<span className="text-xs text-[#888]">No input is sent to a server by this workspace.</span></div></div></div>
<div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-[#e5e5e5] p-4"><FileJson className="mb-3 size-4"/><b className="text-sm">Fast workflows</b><p className="mt-1 text-xs leading-5 text-[#777]">Search, switch and run tools without leaving the workspace.</p></div><div className="rounded-xl border border-[#e5e5e5] p-4"><ShieldCheck className="mb-3 size-4"/><b className="text-sm">Privacy by default</b><p className="mt-1 text-xs leading-5 text-[#777]">Implemented utilities process data in the browser where possible.</p></div><div className="rounded-xl border border-[#e5e5e5] p-4"><WandSparkles className="mb-3 size-4"/><b className="text-sm">Built to scale</b><p className="mt-1 text-xs leading-5 text-[#777]">The directory is structured for adding more specialized tools without clutter.</p></div></div>
</section></div></div></main>;
}
