"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState, type ReactNode } from "react";
import { CalendarClock, Edit3, Link2, LogIn, LogOut, Plus, TrendingUp, WalletCards, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Investment = {
  id: string; name: string; investment_type: string; principal_amount: number; expected_rate: number;
  rate_period: "Monthly" | "Yearly"; invested_on: string; maturity_on: string | null;
  monthly_addition: number; current_value: number | null; contribution_type: "Monthly" | "On maturity";
  funding_source: "Salary" | "Other"; funding_activity_id: string | null;
};
type Activity = {
  id: string; flow_type: "income" | "expense"; amount: number; source: string | null;
  flow_date: string; note: string | null; is_recurring: boolean; recurrence: string;
  recurrence_end: string | null; category: string | null;
};
type Modal = "projection" | "salary" | "activityForm" | "investments" | "investmentForm" | null;
type DurationUnit = "Days" | "Months" | "Years";

const TARGET = 7000000;
const RETURN_TYPES = new Set(["FD", "RD", "SIP", "Mutual Fund", "PPF"]);
const INVESTMENT_TYPES = ["Cash / Uninvested", "FD", "RD", "SIP", "Mutual Fund", "PPF", "Stock", "Gold Scheme", "Physical Gold", "Chit Fund", "Other"];
const INCOME_CATEGORIES = ["Salary", "Business income", "Freelance", "Rental income", "Other income"];
const EXPENSE_CATEGORIES = ["EMI", "Rent", "Electricity", "Water", "Gas", "Internet", "Mobile", "Insurance", "School / Education", "Groceries", "Fuel / Transport", "Medical", "Subscriptions", "Other expense"];

function money(value:number){return `₹${Math.round(Math.max(0,value)).toLocaleString("en-IN")}`}
function dateText(value:string|null){return value?new Date(`${value}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"—"}
function dayDiff(from:Date,to:Date){return Math.max(0,Math.floor((to.getTime()-from.getTime())/86400000))}
function daysInMonth(d:Date){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function daysInYear(d:Date){return new Date(d.getFullYear(),1,29).getDate()===29?366:365}
function addMonths(d:Date,n:number){const x=new Date(d);const day=x.getDate();x.setDate(1);x.setMonth(x.getMonth()+n);x.setDate(Math.min(day,daysInMonth(x)));return x}
function addDuration(start:string,count:number,unit:DurationUnit){const d=new Date(`${start}T00:00:00`);if(!Number.isFinite(count)||count<=0)return"";if(unit==="Days")d.setDate(d.getDate()+count);else if(unit==="Months")return addMonths(d,count).toISOString().slice(0,10);else d.setFullYear(d.getFullYear()+count);return d.toISOString().slice(0,10)}
function monthlyEquivalent(a:Activity){const n=Number(a.amount||0);return a.recurrence==="Weekly"?n*52/12:a.recurrence==="Yearly"?n/12:n}
function monthlyRate(i:Investment){if(!RETURN_TYPES.has(i.investment_type)||Number(i.expected_rate||0)<=0)return 0;const r=Number(i.expected_rate)/100;return i.rate_period==="Monthly"?r:Math.pow(1+r,1/12)-1}
function accrual(i:Investment,today:Date){
 const start=new Date(`${i.invested_on}T00:00:00`),maturity=i.maturity_on?new Date(`${i.maturity_on}T00:00:00`):null,end=maturity&&maturity<today?maturity:today,principal=Number(i.principal_amount||0),payment=Number(i.monthly_addition||0),days=dayDiff(start,end);
 if(start>end)return{value:principal,earned:0,days:0,daily:0,contributions:0};
 let value=principal,contributions=0,cursor=new Date(start),next=i.contribution_type==="Monthly"?addMonths(start,1):null;
 while(cursor<end){const nextDay=new Date(cursor);nextDay.setDate(nextDay.getDate()+1);if(RETURN_TYPES.has(i.investment_type)&&Number(i.expected_rate||0)>0){const dailyRate=i.rate_period==="Monthly"?Number(i.expected_rate)/100/daysInMonth(cursor):Number(i.expected_rate)/100/daysInYear(cursor);value+=value*dailyRate}if(next&&nextDay>=next&&next<=end){value+=payment;contributions+=payment;next=addMonths(next,1)}cursor=nextDay}
 const override=maturity&&maturity<today&&i.current_value!=null?Number(i.current_value):null;const finalValue=override??value;const earned=Math.max(0,finalValue-principal-contributions);return{value:finalValue,earned,days,daily:days?earned/days:0,contributions};
}
function monthLabel(d:Date){return d.toLocaleDateString("en-IN",{month:"short",year:"numeric"})}
function emptyActivity(){return{flow_type:"income" as "income"|"expense",category:"Salary",source:"Salary",amount:"",flow_date:new Date().toISOString().slice(0,10),recurrence:"Monthly",recurrence_end:"",note:""}}
function emptyInvestment(){return{name:"",investment_type:"FD",principal_amount:"",expected_rate:"",rate_period:"Yearly" as "Monthly"|"Yearly",invested_on:new Date().toISOString().slice(0,10),duration:"",duration_unit:"Months" as DurationUnit,monthly_addition:"",contribution_type:"Monthly" as "Monthly"|"On maturity",current_value:"",funding_source:"Salary" as "Salary"|"Other",funding_activity_id:""}}

export default function GoalShell(){
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[investments,setInvestments]=useState<Investment[]>([]),[activities,setActivities]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[modal,setModal]=useState<Modal>(null),[editingInvestmentId,setEditingInvestmentId]=useState<string|null>(null),[editingActivityId,setEditingActivityId]=useState<string|null>(null),[activityForm,setActivityForm]=useState(emptyActivity()),[investmentForm,setInvestmentForm]=useState(emptyInvestment());
 async function load(){const s=createClient();const{data:{user}}=await s.auth.getUser();setUserId(user?.id??null);setEmail(user?.email??null);if(!user){setInvestments([]);setActivities([]);setLoading(false);return}const[{data:inv},{data:act}]=await Promise.all([s.from("goal_investments").select("*").order("invested_on",{ascending:true}),s.from("cash_flows").select("*").eq("is_recurring",true).order("flow_date",{ascending:true})]);setInvestments((inv??[])as Investment[]);setActivities((act??[])as Activity[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const today=new Date();
 const calculated=useMemo(()=>investments.map(i=>({investment:i,calc:accrual(i,today)})),[investments,today.toDateString()]);
 const current=calculated.reduce((s,x)=>s+x.calc.value,0),remaining=Math.max(TARGET-current,0),progress=Math.min(current/TARGET*100,100),monthlyContribution=investments.reduce((s,i)=>s+(i.contribution_type==="Monthly"?Number(i.monthly_addition||0):0),0),growth=calculated.reduce((s,x)=>s+x.calc.earned,0);
 const recurringIncome=activities.filter(a=>a.flow_type==="income").reduce((s,a)=>s+monthlyEquivalent(a),0),recurringExpense=activities.filter(a=>a.flow_type==="expense").reduce((s,a)=>s+monthlyEquivalent(a),0),salaryIncome=activities.filter(a=>a.flow_type==="income"&&a.category==="Salary").reduce((s,a)=>s+monthlyEquivalent(a),0),salaryInvested=investments.filter(i=>i.funding_source==="Salary"&&i.contribution_type==="Monthly").reduce((s,i)=>s+Number(i.monthly_addition||0),0),salaryLeft=salaryIncome-recurringExpense-salaryInvested;
 const projection=useMemo(()=>{if(current>=TARGET)return{rows:[{month:monthLabel(today),value:TARGET}],months:0,can:true};if(!investments.length||monthlyContribution<=0)return{rows:[{month:monthLabel(today),value:current}],months:null,can:false};let balances=investments.map(i=>({value:accrual(i,today).value,payment:i.contribution_type==="Monthly"?Number(i.monthly_addition||0):0,rate:monthlyRate(i)}));const rows=[{month:monthLabel(today),value:current}];for(let m=1;m<=600;m++){const d=addMonths(today,m);balances=balances.map(b=>({...b,value:b.value*(1+b.rate)+b.payment}));const value=Math.min(TARGET,balances.reduce((s,b)=>s+b.value,0));rows.push({month:monthLabel(d),value});if(value>=TARGET)return{rows,months:m,can:true}}return{rows,months:null,can:true}},[current,monthlyContribution,investments,today.toDateString()]);
 const completion=projection.months===0?"Goal reached":projection.months?projection.rows[projection.rows.length-1].month:"Cannot calculate";
 function openNewActivity(type:"income"|"expense"){setEditingActivityId(null);setActivityForm({...emptyActivity(),flow_type:type,category:type==="income"?"Salary":"EMI",source:type==="income"?"Salary":"EMI"});setModal("activityForm")}
 function openEditActivity(a:Activity){setEditingActivityId(a.id);setActivityForm({flow_type:a.flow_type,category:a.category||(a.flow_type==="income"?"Salary":"EMI"),source:a.source||a.category||"",amount:String(a.amount),flow_date:a.flow_date,recurrence:a.recurrence,recurrence_end:a.recurrence_end||"",note:a.note||""});setModal("activityForm")}
 function openNewInvestment(){setEditingInvestmentId(null);setInvestmentForm(emptyInvestment());setModal("investmentForm")}
 function openEditInvestment(i:Investment){const start=new Date(`${i.invested_on}T00:00:00`),maturity=i.maturity_on?new Date(`${i.maturity_on}T00:00:00`):null;let duration="",unit:DurationUnit="Months";if(maturity){const months=(maturity.getFullYear()-start.getFullYear())*12+maturity.getMonth()-start.getMonth();if(months>0&&addMonths(start,months).toDateString()===maturity.toDateString()){duration=months%12===0?String(months/12):String(months);unit=months%12===0?"Years":"Months"}else{duration=String(dayDiff(start,maturity));unit="Days"}}setEditingInvestmentId(i.id);setInvestmentForm({name:i.name,investment_type:i.investment_type,principal_amount:String(i.principal_amount),expected_rate:String(i.expected_rate||""),rate_period:i.rate_period||"Yearly",invested_on:i.invested_on,duration,duration_unit:unit,monthly_addition:String(i.monthly_addition||""),contribution_type:i.contribution_type||"Monthly",current_value:i.current_value==null?"":String(i.current_value),funding_source:i.funding_source||"Other",funding_activity_id:i.funding_activity_id||""});setModal("investmentForm")}
 async function saveActivity(e:FormEvent){e.preventDefault();if(!userId||!Number(activityForm.amount))return;setSaving(true);const payload={user_id:userId,flow_type:activityForm.flow_type,amount:Number(activityForm.amount),source:activityForm.source.trim()||activityForm.category,flow_date:activityForm.flow_date,note:activityForm.note.trim()||null,is_recurring:true,recurrence:activityForm.recurrence,recurrence_end:activityForm.recurrence_end||null,category:activityForm.category};const s=createClient();const r=editingActivityId?await s.from("cash_flows").update(payload).eq("id",editingActivityId).eq("user_id",userId).select().single():await s.from("cash_flows").insert(payload).select().single();setSaving(false);if(!r.error&&r.data){setActivities(p=>editingActivityId?p.map(x=>x.id===editingActivityId?r.data as Activity:x):[...p,r.data as Activity]);setEditingActivityId(null);setModal("salary")}}
 async function saveInvestment(e:FormEvent){e.preventDefault();if(!userId||!investmentForm.name.trim()||!Number(investmentForm.principal_amount))return;setSaving(true);const supportsReturn=RETURN_TYPES.has(investmentForm.investment_type);const maturity=addDuration(investmentForm.invested_on,Number(investmentForm.duration),investmentForm.duration_unit);const payload={user_id:userId,name:investmentForm.name.trim(),investment_type:investmentForm.investment_type,principal_amount:Number(investmentForm.principal_amount),expected_rate:supportsReturn?Number(investmentForm.expected_rate)||0:0,rate_period:investmentForm.rate_period,invested_on:investmentForm.invested_on,maturity_on:maturity||null,monthly_addition:Number(investmentForm.monthly_addition)||0,current_value:investmentForm.current_value?Number(investmentForm.current_value):null,contribution_type:investmentForm.contribution_type,funding_source:investmentForm.funding_source,funding_activity_id:investmentForm.funding_source==="Salary"?(investmentForm.funding_activity_id||null):null};const s=createClient();const r=editingInvestmentId?await s.from("goal_investments").update(payload).eq("id",editingInvestmentId).eq("user_id",userId).select().single():await s.from("goal_investments").insert(payload).select().single();setSaving(false);if(!r.error&&r.data){setInvestments(p=>editingInvestmentId?p.map(x=>x.id===editingInvestmentId?r.data as Investment:x):[...p,r.data as Investment]);setEditingInvestmentId(null);setModal("investments")}}
 async function removeActivity(id:string){const{error}=await createClient().from("cash_flows").delete().eq("id",id).eq("user_id",userId);if(!error)setActivities(p=>p.filter(x=>x.id!==id))}
 async function removeInvestment(id:string){const{error}=await createClient().from("goal_investments").delete().eq("id",id).eq("user_id",userId);if(!error)setInvestments(p=>p.filter(x=>x.id!==id))}
 async function logout(){await createClient().auth.signOut();window.location.href="/goal"}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading your goal…</main>;
 if(!userId)return <main className="min-h-screen grid place-items-center bg-slate-50 p-4"><section className="w-full max-w-md rounded-[2rem] bg-white p-8 text-center shadow-xl ring-1 ring-slate-200"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-violet-50 text-violet-600"><span className="text-3xl font-black">₹</span></div><h1 className="mt-5 text-3xl font-black">Your ₹70 lakh goal</h1><p className="mt-3 text-slate-500">Login to keep your goal private.</p><Link href="/login" className="mt-7 inline-flex w-full justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white"><LogIn size={18}/>Login / Sign up</Link></section></main>;
 return <main className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-6 sm:py-6"><div className="mx-auto max-w-6xl"><header className="mb-4 flex items-center justify-between rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-slate-200"><Link href="/" className="flex items-center gap-2 font-black"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-white">T</span>TargetBud</Link><div className="flex items-center gap-2"><span className="hidden text-xs text-slate-500 sm:block">{email}</span><button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><LogOut size={16}/>Logout</button></div></header>
 <section className="rounded-[2rem] bg-white p-5 shadow-[0_20px_60px_rgba(15,23,42,.08)] ring-1 ring-slate-200 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-5"><button onClick={()=>setModal("projection")} className="grid size-32 shrink-0 place-items-center rounded-full bg-violet-50 transition hover:scale-[1.03] hover:shadow-lg"><div className="text-center"><b className="text-2xl">{progress.toFixed(1)}%</b><p className="text-[11px] font-bold text-slate-400">complete</p><p className="mt-1 text-[10px] font-bold text-violet-600">View graph</p></div></button><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">MY TARGET</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">₹70 lakh</h1><p className="mt-1 text-sm text-slate-500">Your investment path to ₹70 lakh.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setModal("salary")} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 font-bold"><CalendarClock size={19}/>Salary & recurring</button><button onClick={()=>setModal("investments")} className="inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white"><WalletCards size={19}/>Investments</button></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current value" value={money(current)} hint="Calculated till today"/><Metric label="Remaining" value={money(remaining)} hint="To ₹70 lakh"/><Metric label="Monthly contribution" value={money(monthlyContribution)} hint="Across investments"/><Metric label="Growth earned" value={money(growth)} hint="Till today"/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary label="Monthly salary" value={money(salaryIncome)}/><Summary label="Invested from salary" value={money(salaryInvested)}/><Summary label="Salary left" value={money(salaryLeft)}/></div></section>
 {modal&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-900/30 backdrop-blur-sm sm:items-center" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-t-[2rem] bg-white p-5 shadow-2xl ring-1 ring-slate-200 sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">{modal==="projection"?"70 LAKH PROJECTION":modal==="salary"||modal==="activityForm"?"SALARY MANAGEMENT":"INVESTMENTS"}</p><h2 className="mt-1 text-2xl font-black">{modal==="projection"?"How you reach ₹70 lakh":modal==="salary"?"Salary, EMI & bills":modal==="activityForm"?"Recurring activity":modal==="investmentForm"?(editingInvestmentId?"Edit investment":"Add investment"):"Your investments"}</h2></div><button onClick={()=>setModal(null)} className="grid size-10 place-items-center rounded-xl bg-slate-100"><X size={19}/></button></div>
 {modal==="projection"&&<div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Current" value={money(current)}/><Summary label="Monthly contribution" value={money(monthlyContribution)}/><Summary label="Estimated reach" value={completion}/></div>{projection.can?<ProjectionGraph rows={projection.rows} target={TARGET}/>:<EmptyNotice text="Cannot calculate yet — add a monthly investment contribution."/>}</div>}
 {modal==="salary"&&<div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-4"><Summary label="Salary" value={money(salaryIncome)}/><Summary label="Recurring expenses" value={money(recurringExpense)}/><Summary label="Invested from salary" value={money(salaryInvested)}/><Summary label="Left" value={money(salaryLeft)}/></div><div className="flex flex-wrap gap-2"><button onClick={()=>openNewActivity("income")} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white"><Plus size={18}/>Add income</button><button onClick={()=>openNewActivity("expense")} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 font-bold"><Plus size={18}/>Add expense</button></div><div className="rounded-2xl border border-violet-100 bg-violet-50 p-4"><p className="text-xs font-bold tracking-[.15em] text-violet-600">SALARY ALLOCATION</p><p className="mt-1 font-bold">{money(salaryIncome)} salary − {money(recurringExpense)} recurring expenses − {money(salaryInvested)} salary-funded investments = <span className="text-violet-700">{money(salaryLeft)} left</span></p></div><div className="space-y-2">{activities.length===0?<EmptyNotice text="No recurring activity recorded yet."/>:activities.map(a=><article key={a.id} className="flex items-center justify-between gap-3 rounded-2xl border border-slate-200 p-4"><div><div className="flex flex-wrap items-center gap-2"><b>{a.source||a.category||"Activity"}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{a.category||"Other"}</span><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-bold text-violet-700">{a.recurrence}</span></div><p className="mt-1 text-xs text-slate-500">{dateText(a.flow_date)}{a.recurrence_end?` · Ends ${dateText(a.recurrence_end)}`:""}</p></div><div className="flex items-center gap-3"><b className={a.flow_type==="income"?"text-emerald-600":"text-rose-600"}>{a.flow_type==="income"?"+":"−"}{money(a.amount)}</b><button onClick={()=>openEditActivity(a)} className="text-violet-700"><Edit3 size={15}/></button><button onClick={()=>removeActivity(a.id)} className="text-xs font-bold text-rose-600">Delete</button></div></article>)}</div></div>}
 {modal==="activityForm"&&<form onSubmit={saveActivity} className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setActivityForm(f=>({...f,flow_type:"income",category:"Salary",source:"Salary"}))} className={`rounded-2xl p-4 text-left ring-1 ${activityForm.flow_type==="income"?"bg-violet-50 ring-violet-200":"bg-slate-50 ring-slate-200"}`}><b>Income</b><p className="text-xs text-slate-500">Salary, business, freelance or rental</p></button><button type="button" onClick={()=>setActivityForm(f=>({...f,flow_type:"expense",category:"EMI",source:"EMI"}))} className={`rounded-2xl p-4 text-left ring-1 ${activityForm.flow_type==="expense"?"bg-violet-50 ring-violet-200":"bg-slate-50 ring-slate-200"}`}><b>Expense</b><p className="text-xs text-slate-500">EMI, rent, bills and regular spending</p></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Category"><select value={activityForm.category} onChange={e=>setActivityForm(f=>({...f,category:e.target.value,source:e.target.value}))} className="tb-field">{(activityForm.flow_type==="income"?INCOME_CATEGORIES:EXPENSE_CATEGORIES).map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Name / source"><input required value={activityForm.source} onChange={e=>setActivityForm(f=>({...f,source:e.target.value}))} className="tb-field"/></Field><Field label="Amount"><input required type="number" min="0" value={activityForm.amount} onChange={e=>setActivityForm(f=>({...f,amount:e.target.value}))} className="tb-field"/></Field><Field label="Repeats"><select value={activityForm.recurrence} onChange={e=>setActivityForm(f=>({...f,recurrence:e.target.value}))} className="tb-field"><option>Monthly</option><option>Weekly</option><option>Yearly</option></select></Field><Field label="Starts"><input required type="date" value={activityForm.flow_date} onChange={e=>setActivityForm(f=>({...f,flow_date:e.target.value}))} className="tb-field"/></Field><Field label="Ends on (optional)"><input type="date" min={activityForm.flow_date} value={activityForm.recurrence_end} onChange={e=>setActivityForm(f=>({...f,recurrence_end:e.target.value}))} className="tb-field"/></Field></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setModal("salary")} className="rounded-xl border px-4 py-3 font-bold">Back</button><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">{saving?"Saving…":editingActivityId?"Save changes":"Add activity"}</button></div></form>}
 {modal==="investments"&&<div className="mt-6 space-y-4"><div className="flex flex-wrap gap-2"><button onClick={openNewInvestment} className="inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white"><Plus size={18}/>Add investment</button><span className="rounded-xl bg-slate-100 px-4 py-3 text-sm font-bold">{money(monthlyContribution)} / month</span></div>{investments.length===0?<EmptyNotice text="No investments recorded yet."/>:investments.map(i=>{const r=calculated.find(x=>x.investment.id===i.id);return <article key={i.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>{i.name}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{i.investment_type}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${i.funding_source==="Salary"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{i.funding_source==="Salary"?"From salary":"Other money"}</span></div><p className="mt-1 text-xs text-slate-500">{dateText(i.invested_on)} · {i.contribution_type}</p></div><button onClick={()=>openEditInvestment(i)} className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-violet-700"><Edit3 size={14}/>Edit</button></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Current" value={money(r?.calc.value??i.current_value??i.principal_amount)}/><Mini label="Principal" value={money(i.principal_amount)}/><Mini label="Earned" value={money(r?.calc.earned??0)}/><Mini label="Monthly" value={money(i.monthly_addition)}/></div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>{i.funding_source==="Salary"?"Counts in Invested from salary":"Not deducted from salary"}</span><button onClick={()=>removeInvestment(i.id)} className="font-bold text-rose-600">Delete</button></div></article>})}</div>}
 {modal==="investmentForm"&&<form onSubmit={saveInvestment} className="mt-6 space-y-5"><div className="rounded-2xl bg-violet-50 p-4"><Field label="Investment type"><select value={investmentForm.investment_type} onChange={e=>setInvestmentForm(f=>({...f,investment_type:e.target.value}))} className="tb-field mt-1">{INVESTMENT_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><input required value={investmentForm.name} onChange={e=>setInvestmentForm(f=>({...f,name:e.target.value}))} className="tb-field"/></Field><Field label="Principal / amount invested"><input required type="number" min="0" value={investmentForm.principal_amount} onChange={e=>setInvestmentForm(f=>({...f,principal_amount:e.target.value}))} className="tb-field"/></Field></div>{RETURN_TYPES.has(investmentForm.investment_type)&&<div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold tracking-[.16em] text-slate-400">RETURN</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Rate"><input type="number" min="0" step="0.01" value={investmentForm.expected_rate} onChange={e=>setInvestmentForm(f=>({...f,expected_rate:e.target.value}))} className="tb-field"/></Field><Field label="Rate period"><select value={investmentForm.rate_period} onChange={e=>setInvestmentForm(f=>({...f,rate_period:e.target.value as "Monthly"|"Yearly"}))} className="tb-field"><option>Yearly</option><option>Monthly</option></select></Field></div></div>}
 <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold tracking-[.16em] text-slate-400">CONTRIBUTION</p><div className="mt-3 grid gap-4 sm:grid-cols-2"><Field label="Payment pattern"><select value={investmentForm.contribution_type} onChange={e=>setInvestmentForm(f=>({...f,contribution_type:e.target.value as "Monthly"|"On maturity"}))} className="tb-field"><option>Monthly</option><option>On maturity</option></select></Field><Field label="Contribution amount"><input type="number" min="0" value={investmentForm.monthly_addition} onChange={e=>setInvestmentForm(f=>({...f,monthly_addition:e.target.value}))} className="tb-field"/></Field></div></div>
 <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><p className="text-xs font-bold tracking-[.16em] text-slate-400">TIME PERIOD</p><div className="mt-3 grid gap-4 sm:grid-cols-3"><Field label="Start date"><input required type="date" value={investmentForm.invested_on} onChange={e=>setInvestmentForm(f=>({...f,invested_on:e.target.value}))} className="tb-field"/></Field><Field label="Duration"><input type="number" min="1" value={investmentForm.duration} onChange={e=>setInvestmentForm(f=>({...f,duration:e.target.value}))} className="tb-field"/></Field><Field label="Unit"><select value={investmentForm.duration_unit} onChange={e=>setInvestmentForm(f=>({...f,duration_unit:e.target.value as DurationUnit}))} className="tb-field"><option>Days</option><option>Months</option><option>Years</option></select></Field></div>{investmentForm.duration&&<p className="mt-3 rounded-xl bg-white p-3 text-sm font-bold text-violet-700 ring-1 ring-slate-200">Matures {dateText(addDuration(investmentForm.invested_on,Number(investmentForm.duration),investmentForm.duration_unit))}</p>}</div>
 <div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold tracking-[.16em] text-slate-400">FUNDING SOURCE</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setInvestmentForm(f=>({...f,funding_source:"Salary",funding_activity_id:f.funding_activity_id||salaryActivities[0]?.id||""}))} className={`rounded-2xl p-4 text-left ring-1 ${investmentForm.funding_source==="Salary"?"bg-emerald-50 ring-emerald-200":"bg-slate-50 ring-slate-200"}`}><div className="flex items-center gap-2 font-bold"><Link2 size={18}/>Salary</div><p className="mt-1 text-xs text-slate-500">This monthly contribution is shown as invested from salary.</p></button><button type="button" onClick={()=>setInvestmentForm(f=>({...f,funding_source:"Other",funding_activity_id:""}))} className={`rounded-2xl p-4 text-left ring-1 ${investmentForm.funding_source==="Other"?"bg-violet-50 ring-violet-200":"bg-slate-50 ring-slate-200"}`}><div className="flex items-center gap-2 font-bold"><WalletCards size={18}/>Other money</div><p className="mt-1 text-xs text-slate-500">Keep this contribution outside salary.</p></button></div>{investmentForm.funding_source==="Salary"&&salaryActivities.length>0&&<Field label="Which salary activity"><select value={investmentForm.funding_activity_id} onChange={e=>setInvestmentForm(f=>({...f,funding_activity_id:e.target.value}))} className="tb-field mt-3"><option value="">Salary (general)</option>{salaryActivities.map(a=><option key={a.id} value={a.id}>{a.source||"Salary"} · {money(monthlyEquivalent(a))}/month</option>)}</select></Field>}</div>
 <div className="flex justify-end gap-2"><button type="button" onClick={()=>setModal("investments")} className="rounded-xl border px-4 py-3 font-bold">Back</button><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">{saving?"Saving…":editingInvestmentId?"Save changes":"Add investment"}</button></div></form>}
 </section></div>}
 </div></main>
}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p><p className="text-[11px] text-slate-400">{hint}</p></div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><p className="text-[10px] font-bold text-slate-400">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-bold text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span>{children}</label>}
function EmptyNotice({text}:{text:string}){return <div className="rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">{text}</div>}
function ProjectionGraph({rows,target}:{rows:{month:string;value:number}[];target:number}){const width=1000,height=430,padX=55,padY=35,plotW=width-padX*2,plotH=height-padY-55,points=rows.map((r,i)=>({x:padX+(rows.length===1?plotW/2:i/(rows.length-1)*plotW),y:padY+plotH-(r.value/target)*plotH,...r})),line=points.map((p,i)=>`${i===0?"M":"L"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" "),last=points[points.length-1];return <div className="overflow-hidden rounded-3xl border border-slate-200 bg-slate-50 p-3 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-violet-600">₹70 LAKH PATH</p><p className="mt-1 text-sm text-slate-500">Current value → target</p></div><span className="rounded-full bg-white px-3 py-1.5 text-xs font-bold ring-1 ring-slate-200">{money(last?.value??0)}</span></div><div className="mt-5 overflow-x-auto"><div className="min-w-[720px]"><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full"><line x1={padX} x2={width-padX} y1={padY} y2={padY} stroke="currentColor" strokeDasharray="8 8" className="text-violet-300"/><text x={width-padX} y={padY+18} textAnchor="end" className="fill-violet-600 text-[16px] font-bold">₹70L target</text><line x1={padX} x2={padX} y1={padY} y2={padY+plotH} stroke="currentColor" className="text-slate-200"/><line x1={padX} x2={width-padX} y1={padY+plotH} y2={padY+plotH} stroke="currentColor" className="text-slate-200"/><path d={`${line} L${last?.x??padX},${padY+plotH} L${points[0]?.x??padX},${padY+plotH} Z`} className="fill-violet-100"/><path d={line} fill="none" stroke="currentColor" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" className="text-violet-600"/><circle cx={points[0]?.x??padX} cy={points[0]?.y??padY+plotH} r="7" className="fill-violet-600 stroke-white" strokeWidth="3"/><circle cx={last?.x??padX} cy={last?.y??padY+plotH} r="7" className="fill-violet-600 stroke-white" strokeWidth="3"/><text x={padX} y={height-14} className="fill-slate-400 text-[15px] font-bold">{rows[0]?.month}</text><text x={width-padX} y={height-14} textAnchor="end" className="fill-slate-400 text-[15px] font-bold">{rows[rows.length-1]?.month}</text></svg></div></div></div>}
