"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CalendarClock, ChevronRight, CircleDollarSign, LogIn, LogOut, Plus, TrendingUp, WalletCards, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Investment={id:string;name:string;investment_type:string;principal_amount:number;expected_rate:number;rate_period:"Monthly"|"Yearly";invested_on:string;maturity_on:string|null;monthly_addition:number;current_value:number|null;contribution_type:"Monthly"|"On maturity"};
type Activity={id:string;flow_type:"income"|"expense";amount:number;source:string|null;flow_date:string;note:string|null;is_recurring:boolean;recurrence:string;recurrence_end:string|null;category:string|null};
const TARGET=7000000;
const INTEREST_TYPES=new Set(["FD","RD","SIP","Mutual Fund","PPF"]);
const CATEGORIES=["Salary","Business income","Freelance","Rental income","Other income","EMI","Rent","Electricity","Water","Gas","Internet","Mobile","Insurance","School / Education","Groceries","Fuel / Transport","Medical","Subscriptions","Other"];
function money(v:number){return `₹${Math.round(Math.max(0,v)).toLocaleString("en-IN")}`}
function dateText(v:string|null){return v?new Date(`${v}T00:00:00`).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"—"}
function addMonths(d:Date,n:number){const x=new Date(d);x.setMonth(x.getMonth()+n);return x}
function monthLabel(d:Date){return d.toLocaleDateString("en-IN",{month:"short",year:"numeric"})}
function monthlyRate(i:Investment){if(!INTEREST_TYPES.has(i.investment_type)||Number(i.expected_rate||0)<=0)return 0;const r=Number(i.expected_rate)/100;return i.rate_period==="Monthly"?r:Math.pow(1+r,1/12)-1}
function currentValue(i:Investment,today:Date){const principal=Number(i.current_value??i.principal_amount??0);return principal}
function monthlyEquivalent(a:Activity){const n=Number(a.amount||0);if(a.recurrence==="Weekly")return n*52/12;if(a.recurrence==="Yearly")return n/12;return n}

export default function GoalShell(){
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[investments,setInvestments]=useState<Investment[]>([]),[activities,setActivities]=useState<Activity[]>([]),[loading,setLoading]=useState(true),[modal,setModal]=useState<"projection"|"activity"|"addActivity"|null>(null),[saving,setSaving]=useState(false);
 const [form,setForm]=useState({flow_type:"income" as "income"|"expense",category:"Salary",source:"Salary",amount:"",flow_date:new Date().toISOString().slice(0,10),recurrence:"Monthly",recurrence_end:"",note:""});
 async function load(){const s=createClient(),{data:{user}}=await s.auth.getUser();setUserId(user?.id??null);setEmail(user?.email??null);if(user){const [{data:inv},{data:act}]=await Promise.all([s.from("goal_investments").select("*").order("invested_on",{ascending:true}),s.from("cash_flows").select("*").eq("is_recurring",true).order("flow_date",{ascending:true})]);setInvestments((inv??[]) as Investment[]);setActivities((act??[]) as Activity[])}else{setInvestments([]);setActivities([])}setLoading(false)}
 useEffect(()=>{load()},[]);
 const today=new Date();
 const current=investments.reduce((s,i)=>s+currentValue(i,today),0),monthly=investments.reduce((s,i)=>s+(i.contribution_type==="Monthly"?Number(i.monthly_addition||0):0),0),remaining=Math.max(TARGET-current,0),progress=Math.min(current/TARGET*100,100);
 const recurringIncome=activities.filter(a=>a.flow_type==="income").reduce((s,a)=>s+monthlyEquivalent(a),0),recurringExpense=activities.filter(a=>a.flow_type==="expense").reduce((s,a)=>s+monthlyEquivalent(a),0),cashLeft=recurringIncome-recurringExpense;
 const projection=useMemo(()=>{if(current>=TARGET)return{rows:[{month:monthLabel(today),value:TARGET}],months:0,can:true};if(monthly<=0)return{rows:[{month:monthLabel(today),value:current}],months:null,can:false};let balances=investments.map(i=>({value:currentValue(i,today),payment:i.contribution_type==="Monthly"?Number(i.monthly_addition||0):0,rate:monthlyRate(i)}));const rows=[{month:monthLabel(today),value:current}];for(let m=1;m<=600;m++){const d=addMonths(today,m);balances=balances.map(b=>({value:b.value*(1+b.rate)+b.payment,payment:b.payment,rate:b.rate}));const value=Math.min(TARGET,balances.reduce((s,b)=>s+b.value,0));rows.push({month:monthLabel(d),value});if(value>=TARGET)return{rows,months:m,can:true}}return{rows,months:null,can:true}},[current,monthly,investments]);
 const completion=projection.months===0?"Goal reached":projection.months?projection.rows[projection.rows.length-1].month:"Cannot calculate";
 async function addActivity(){if(!userId||!Number(form.amount))return;setSaving(true);const s=createClient();const {data,error}=await s.from("cash_flows").insert({user_id:userId,flow_type:form.flow_type,amount:Number(form.amount),source:form.source.trim()||form.category,flow_date:form.flow_date,note:form.note.trim()||null,is_recurring:true,recurrence:form.recurrence,recurrence_end:form.recurrence_end||null,category:form.category}).select().single();setSaving(false);if(!error&&data){setActivities(p=>[...p,data as Activity].sort((a,b)=>a.flow_date.localeCompare(b.flow_date)));setForm({...form,amount:"",note:"",recurrence_end:""});setModal("activity")}}
 async function removeActivity(id:string){const {error}=await createClient().from("cash_flows").delete().eq("id",id).eq("user_id",userId);if(!error)setActivities(p=>p.filter(a=>a.id!==id))}
 async function logout(){await createClient().auth.signOut();window.location.href="/goal"}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading your goal…</main>;
 if(!userId)return <main className="min-h-screen grid place-items-center bg-slate-50 p-4"><section className="w-full max-w-md rounded-[2rem] bg-white p-8 text-center shadow-xl ring-1 ring-slate-200"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-violet-50 text-violet-600"><CircleDollarSign/></div><p className="mt-5 text-xs font-bold tracking-[.2em] text-violet-600">TARGETBUD</p><h1 className="mt-2 text-3xl font-black">Your ₹70 lakh goal</h1><p className="mt-3 text-slate-500">Login to keep your goal private.</p><Link href="/login" className="mt-7 inline-flex w-full justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white"><LogIn size={18}/>Login / Sign up</Link></section></main>;
 return <main className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-6 sm:py-6"><div className="mx-auto max-w-6xl"><header className="mb-4 flex items-center justify-between rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-slate-200"><Link href="/" className="flex items-center gap-2 font-black"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-white">T</span>TargetBud</Link><button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><LogOut size={16}/>Logout</button></header>
 <section className="rounded-[2rem] bg-white p-5 shadow-[0_20px_60px_rgba(15,23,42,.08)] ring-1 ring-slate-200 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-5"><button onClick={()=>setModal("projection")} aria-label="Open ₹70 lakh projection" className="relative grid size-32 shrink-0 place-items-center rounded-full bg-violet-50 transition hover:scale-[1.03] hover:shadow-lg"><div className="text-center"><b className="text-2xl">{progress.toFixed(1)}%</b><p className="text-[11px] font-bold text-slate-400">complete</p><p className="mt-1 text-[10px] font-bold text-violet-600">View graph</p></div></button><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">MY TARGET</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">₹70 lakh</h1><p className="mt-1 text-sm text-slate-500">Your investment path to ₹70 lakh.</p></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setModal("activity")} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 py-3.5 font-bold"><CalendarClock size={19}/>Salary & recurring activity</button><Link href="/goal/activity" className="inline-flex items-center gap-2 rounded-2xl border border-violet-200 bg-violet-50 px-5 py-3.5 font-bold text-violet-700">Full manager<ChevronRight size={17}/></Link></div></div>
 <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Current value" value={money(current)} hint="Recorded investments"/><Metric label="Remaining" value={money(remaining)} hint="To ₹70 lakh"/><Metric label="Monthly addition" value={money(monthly)} hint="Investment contributions"/><Metric label="Completion" value={completion} hint="Investment projection"/></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary label="Recurring income / month" value={money(recurringIncome)}/><Summary label="Recurring expenses / month" value={money(recurringExpense)}/><Summary label="Balance / month" value={money(cashLeft)}/></div></section>
 {modal&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/25 p-3 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-[2rem] bg-white p-5 shadow-2xl ring-1 ring-slate-200 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">{modal==="projection"?"70 LAKH PROJECTION":"RECURRING ACTIVITY"}</p><h2 className="mt-1 text-2xl font-black">{modal==="projection"?"How you reach ₹70 lakh":"Salary, EMI & bills"}</h2></div><button onClick={()=>setModal(null)} className="grid size-10 place-items-center rounded-xl bg-slate-100"><X size={19}/></button></div>
 {modal==="projection"?<div className="mt-6"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Current" value={money(current)}/><Summary label="Monthly contribution" value={money(monthly)}/><Summary label="Estimated reach" value={completion}/></div>{projection.can?<ProjectionGraph rows={projection.rows} target={TARGET}/>:<div className="mt-5 rounded-2xl bg-amber-50 p-5 text-center text-sm text-amber-800">Cannot calculate yet — add a monthly investment contribution.</div>}<p className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Only recorded investment value, monthly contributions and return rates you entered are used. Salary, expenses and bills do not affect this graph.</p></div>:<div className="mt-6"><div className="grid gap-3 sm:grid-cols-3"><Summary label="Income / month" value={money(recurringIncome)}/><Summary label="Expenses / month" value={money(recurringExpense)}/><Summary label="Balance / month" value={money(cashLeft)}/></div><button onClick={()=>setModal("addActivity")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-3 font-bold text-white"><Plus size={18}/>Add recurring activity</button><div className="mt-4 space-y-2">{activities.length===0?<p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No recurring salary, EMI or bills recorded yet.</p>:activities.map(a=><article key={a.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><b>{a.source||a.category}</b><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{a.category||"Other"}</span><span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-bold text-violet-700">{a.recurrence}</span></div><p className="mt-1 text-xs text-slate-500">Starts {dateText(a.flow_date)}{a.recurrence_end?` · Ends ${dateText(a.recurrence_end)}`:""}</p></div><button onClick={()=>removeActivity(a.id)} className="text-xs font-bold text-rose-600">Delete</button></div><p className={`mt-3 text-xl font-black ${a.flow_type==="income"?"text-emerald-600":"text-rose-600"}`}>{a.flow_type==="income"?"+":"−"}{money(a.amount)} <span className="text-xs text-slate-400">/ {a.recurrence.toLowerCase().replace("ly","")}</span></p></article>)}</div></div>}
 {modal==="addActivity"&&<form onSubmit={e=>{e.preventDefault();addActivity()}} className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setForm(f=>({...f,flow_type:"income",category:"Salary",source:"Salary"}))} className={`rounded-2xl p-4 text-left ring-1 ${form.flow_type==="income"?"bg-violet-50 ring-violet-200":"bg-slate-50 ring-slate-200"}`}><b>Income</b><p className="text-xs text-slate-500">Salary, business, freelance or rental</p></button><button type="button" onClick={()=>setForm(f=>({...f,flow_type:"expense",category:"EMI",source:"EMI"}))} className={`rounded-2xl p-4 text-left ring-1 ${form.flow_type==="expense"?"bg-violet-50 ring-violet-200":"bg-slate-50 ring-slate-200"}`}><b>Expense</b><p className="text-xs text-slate-500">EMI, bills, rent and regular spending</p></button></div><label className="block text-xs font-bold">Category<select value={form.category} onChange={e=>setForm(f=>({...f,category:e.target.value,source:e.target.value}))} className="tb-field mt-1">{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="block text-xs font-bold">Name / source<input required value={form.source} onChange={e=>setForm(f=>({...f,source:e.target.value}))} className="tb-field mt-1"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold">Amount<input required type="number" min="0" value={form.amount} onChange={e=>setForm(f=>({...f,amount:e.target.value}))} placeholder="₹ amount" className="tb-field mt-1"/></label><label className="block text-xs font-bold">Repeats<select value={form.recurrence} onChange={e=>setForm(f=>({...f,recurrence:e.target.value}))} className="tb-field mt-1"><option>Monthly</option><option>Weekly</option><option>Yearly</option></select></label><label className="block text-xs font-bold">Starts<input required type="date" value={form.flow_date} onChange={e=>setForm(f=>({...f,flow_date:e.target.value}))} className="tb-field mt-1"/></label><label className="block text-xs font-bold">Ends on (optional)<input type="date" min={form.flow_date} value={form.recurrence_end} onChange={e=>setForm(f=>({...f,recurrence_end:e.target.value}))} className="tb-field mt-1"/></label></div><label className="block text-xs font-bold">Note<input value={form.note} onChange={e=>setForm(f=>({...f,note:e.target.value}))} className="tb-field mt-1"/></label><div className="flex justify-end gap-2"><button type="button" onClick={()=>setModal("activity")} className="rounded-xl border px-4 py-3 font-bold">Back</button><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">{saving?"Saving…":"Add recurring activity"}</button></div></form>}
 </section></div>}
 </div></main>
}
function Metric({label,value,hint}:{label:string;value:string;hint:string}){return <div className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p><p className="text-[11px] text-slate-400">{hint}</p></div>}
function Summary({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><p className="text-[10px] font-bold text-slate-400">{label}</p><p className="mt-1 text-lg font-black">{value}</p></div>}
function ProjectionGraph({rows,target}:{rows:{month:string;value:number}[];target:number}){const width=1000,height=430,padX=55,padY=35,plotW=width-padX*2,plotH=height-padY-55,max=target,points=rows.map((r,i)=>({x:padX+(rows.length===1?plotW/2:(i/(rows.length-1))*plotW),y:padY+plotH-(r.value/max)*plotH,...r})),line=points.map((p,i)=>`${i===0?"M":"L"}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(" "),targetY=padY,last=points[points.length-1];return <div className="mt-5 overflow-hidden rounded-3xl border border-slate-200 bg-slate-50 p-3 sm:p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-violet-600">₹70 LAKH PATH</p><p className="mt-1 text-sm text-slate-500">Current value → target</p></div><span className="rounded-full bg-white px-3 py-1.5 text-xs font-bold ring-1 ring-slate-200">{money(last?.value??0)}</span></div><div className="relative aspect-[2.2/1] min-h-[250px] w-full"><svg viewBox={`0 0 ${width} ${height}`} className="h-full w-full" role="img" aria-label="Projection to 70 lakh"><line x1={padX} x2={width-padX} y1={targetY} y2={targetY} stroke="currentColor" strokeDasharray="8 8" className="text-violet-300"/><text x={width-padX} y={targetY+18} textAnchor="end" className="fill-violet-600 text-[16px] font-bold">₹70L target</text><line x1={padX} x2={padX} y1={padY} y2={padY+plotH} stroke="currentColor" className="text-slate-200"/><line x1={padX} x2={width-padX} y1={padY+plotH} y2={padY+plotH} stroke="currentColor" className="text-slate-200"/><path d={`${line} L${last?.x??padX},${padY+plotH} L${points[0]?.x??padX},${padY+plotH} Z`} className="fill-violet-100"/><path d={line} fill="none" stroke="currentColor" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round" className="text-violet-600"/><circle cx={points[0]?.x??padX} cy={points[0]?.y??padY+plotH} r="7" className="fill-violet-600 stroke-white" strokeWidth="3"/><circle cx={last?.x??padX} cy={last?.y??padY+plotH} r="7" className="fill-violet-600 stroke-white" strokeWidth="3"/><text x={padX} y={height-14} className="fill-slate-400 text-[15px] font-bold">{rows[0]?.month}</text><text x={width-padX} y={height-14} textAnchor="end" className="fill-slate-400 text-[15px] font-bold">{rows[rows.length-1]?.month}</text></svg></div></div>}
