"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, ChevronRight, CircleDollarSign, Edit3, LogIn, LogOut, Plus, TrendingUp, WalletCards, X } from "lucide-react";
import { createClient } from "@/lib/supabase-browser";

type Investment={id:string;name:string;investment_type:string;principal_amount:number;expected_rate:number;rate_type:"Fixed"|"Expected"|"None";rate_period:"Monthly"|"Yearly";invested_on:string;maturity_on:string|null;compounding:"Monthly"|"Quarterly"|"Yearly"|"At maturity"|"None";monthly_addition:number;current_value:number|null;contribution_type:"Monthly"|"On maturity"};
type Modal="current"|"remaining"|"monthly"|"assets"|"add"|null;
type DurationUnit="Days"|"Months"|"Years";
type FormState={name:string;investment_type:string;principal_amount:string;expected_rate:string;rate_type:"Fixed"|"Expected"|"None";rate_period:"Monthly"|"Yearly";invested_on:string;duration:string;duration_unit:DurationUnit;compounding:Investment["compounding"];monthly_addition:string;current_value:string;contribution_type:Investment["contribution_type"]};
const TARGET=7000000; const TYPES=["Cash / Uninvested","FD","RD","SIP","Mutual Fund","PPF","Stock","Other"];
const COMPOUNDING=["Monthly","Quarterly","Yearly","At maturity","None"] as const;
const RATE_PERIODS=["Monthly","Yearly"] as const;
function money(v:number){return `₹${Math.round(Math.max(0,v)).toLocaleString("en-IN")}`}
function dateValue(s:string){return new Date(`${s}T00:00:00`)}
function formatDate(s:string|null){return s?dateValue(s).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}):"—"}
function dayDiff(a:Date,b:Date){return Math.max(0,Math.floor((b.getTime()-a.getTime())/86400000))}
function daysInMonth(d:Date){return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function daysInYear(d:Date){return new Date(d.getFullYear(),1,29).getDate()===29?366:365}
function addMonthsSafe(d:Date,n:number){const x=new Date(d),day=x.getDate();x.setDate(1);x.setMonth(x.getMonth()+n);x.setDate(Math.min(day,daysInMonth(x)));return x}
function addDuration(start:string,amount:string,unit:DurationUnit){const d=dateValue(start),n=Math.max(0,Number(amount)||0);if(unit==="Days")d.setDate(d.getDate()+n);else if(unit==="Months")return addMonthsSafe(d,n).toISOString().slice(0,10);else d.setFullYear(d.getFullYear()+n);return d.toISOString().slice(0,10)}
function durationFromDates(start:string,end:string|null):{amount:string;unit:DurationUnit}{if(!end)return{amount:"",unit:"Months"};const a=dateValue(start),b=dateValue(end);const months=(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth();if(a.getDate()===b.getDate())return months%12===0?{amount:String(months/12),unit:"Years"}:{amount:String(months),unit:"Months"};return{amount:String(dayDiff(a,b)),unit:"Days"}}
/** Day-by-day growth. None compounding means simple daily interest, not zero interest. */
function calculateInvestment(inv:Investment,today:Date){
 const start=dateValue(inv.invested_on),maturity=inv.maturity_on?dateValue(inv.maturity_on):null,end=maturity&&maturity<today?maturity:today,principal=Number(inv.principal_amount||0),payment=Number(inv.monthly_addition||0),days=dayDiff(start,end);
 if(inv.investment_type==="Cash / Uninvested"||inv.expected_rate<=0){const value=maturity&&maturity<today&&inv.current_value!=null?Number(inv.current_value):principal;const contributed=inv.contribution_type==="On maturity"&&maturity&&today>=maturity?payment:0;return{value:value+contributed,contributed,earned:0,days,daily:0}}
 let balance=principal,contributed=0,cursor=new Date(start),next=inv.contribution_type==="Monthly"?addMonthsSafe(start,1):null;
 while(cursor<end){const nextDay=new Date(cursor);nextDay.setDate(nextDay.getDate()+1);const rate=inv.rate_period==="Monthly"?inv.expected_rate/100/daysInMonth(cursor):inv.expected_rate/100/daysInYear(cursor);balance+=balance*rate;if(next&&nextDay>=next&&next<=end){balance+=payment;contributed+=payment;next=addMonthsSafe(next,1)}cursor=nextDay}
 if(inv.contribution_type==="On maturity"&&maturity&&today>=maturity){balance+=payment;contributed+=payment}
 const stale=maturity&&maturity<today&&inv.current_value!=null?Number(inv.current_value):null,value=stale??balance,earned=Math.max(0,value-principal-contributed);return{value,contributed,earned,days,daily:days?earned/days:0}
}
function isStale(i:Investment,today:Date){return Boolean(i.maturity_on&&dateValue(i.maturity_on)<new Date(today.getFullYear(),today.getMonth(),today.getDate()))}
function emptyForm():FormState{return{name:"",investment_type:"Cash / Uninvested",principal_amount:"",expected_rate:"",rate_type:"None",rate_period:"Monthly",invested_on:new Date().toISOString().slice(0,10),duration:"",duration_unit:"Months",compounding:"Monthly",monthly_addition:"",current_value:"",contribution_type:"Monthly"}}
function Ring({value}:{value:number}){const r=58,c=2*Math.PI*r,d=c*Math.min(value,100)/100;return <div className="relative size-36"><svg viewBox="0 0 144 144" className="size-36 -rotate-90"><circle cx="72" cy="72" r={r} fill="none" stroke="#e8eaf1" strokeWidth="12"/><circle cx="72" cy="72" r={r} fill="none" stroke="#7c3aed" strokeWidth="12" strokeLinecap="round" strokeDasharray={`${d} ${c-d}`}/></svg><div className="absolute inset-0 grid place-items-center text-center"><div><b className="text-2xl">{value.toFixed(1)}%</b><div className="text-[11px] font-semibold text-slate-400">complete</div></div></div></div>}
export default function GoalPage(){
 const [userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState<string|null>(null),[items,setItems]=useState<Investment[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[modal,setModal]=useState<Modal>(null),[editing,setEditing]=useState<string|null>(null),[form,setForm]=useState<FormState>(emptyForm());const today=new Date();
 async function load(){const s=createClient(),{data:{user}}=await s.auth.getUser();setUserId(user?.id??null);setEmail(user?.email??null);if(user){const{data}=await s.from("goal_investments").select("*").order("invested_on",{ascending:true});setItems((data??[])as Investment[])}else setItems([]);setLoading(false)}
 useEffect(()=>{let live=true;const s=createClient();load();const{data}=s.auth.onAuthStateChange(()=>{if(live)load()});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 const calculated=useMemo(()=>items.map(inv=>({inv,calc:calculateInvestment(inv,today)})),[items,today.toDateString()]);const current=calculated.reduce((s,x)=>s+x.calc.value,0),principal=items.reduce((s,x)=>s+Number(x.principal_amount||0),0),earned=calculated.reduce((s,x)=>s+x.calc.earned,0),remaining=Math.max(TARGET-current,0),progress=Math.min(current/TARGET*100,100),monthly=items.reduce((s,x)=>s+(x.contribution_type==="Monthly"?Number(x.monthly_addition||0):0),0),stale=items.filter(x=>isStale(x,today)).length;
 const completion=useMemo(()=>{if(remaining<=0)return"Goal reached";if(monthly<=0)return"Add monthly contribution";const d=new Date();d.setMonth(d.getMonth()+Math.ceil(remaining/monthly));return d.toLocaleDateString("en-IN",{month:"short",year:"numeric"})},[remaining,monthly]);
 function edit(i:Investment){const d=durationFromDates(i.invested_on,i.maturity_on);setEditing(i.id);setForm({name:i.name,investment_type:i.investment_type,principal_amount:String(i.principal_amount),expected_rate:String(i.expected_rate),rate_type:i.rate_type,rate_period:i.rate_period??"Yearly",invested_on:i.invested_on,duration:d.amount,duration_unit:d.unit,compounding:i.compounding,monthly_addition:String(i.monthly_addition||""),current_value:i.current_value==null?"":String(i.current_value),contribution_type:i.contribution_type??"Monthly"});setModal("add")}
 async function save(e:FormEvent){e.preventDefault();if(!userId||!form.name.trim())return;setSaving(true);const maturity=form.duration?addDuration(form.invested_on,form.duration,form.duration_unit):null;const s=createClient(),payload={user_id:userId,name:form.name.trim(),investment_type:form.investment_type,principal_amount:Number(form.principal_amount)||0,expected_rate:Number(form.expected_rate)||0,rate_type:form.investment_type==="Cash / Uninvested"?"None":form.rate_type,rate_period:form.rate_period,invested_on:form.invested_on,maturity_on:maturity,compounding:form.investment_type==="Cash / Uninvested"?"None":form.compounding,monthly_addition:Number(form.monthly_addition)||0,current_value:form.current_value?Number(form.current_value):null,contribution_type:form.contribution_type};const result=editing?await s.from("goal_investments").update(payload).eq("id",editing).eq("user_id",userId).select().single():await s.from("goal_investments").insert(payload).select().single();setSaving(false);if(!result.error&&result.data){setItems(p=>editing?p.map(i=>i.id===editing?result.data as Investment:i):[...p,result.data as Investment]);setEditing(null);setForm(emptyForm());setModal("assets")}}
 async function remove(id:string){const{error}=await createClient().from("goal_investments").delete().eq("id",id).eq("user_id",userId);if(!error)setItems(p=>p.filter(i=>i.id!==id))}async function logout(){await createClient().auth.signOut();location.href="/goal"}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Loading your goal…</main>;if(!userId)return <main className="min-h-screen bg-slate-50 p-4 grid place-items-center"><section className="w-full max-w-md rounded-[2rem] bg-white p-8 text-center shadow-xl ring-1 ring-slate-200"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-violet-50 text-violet-600"><CircleDollarSign size={30}/></div><p className="mt-5 text-xs font-bold tracking-[.22em] text-violet-600">TARGETBUD</p><h1 className="mt-2 text-3xl font-black">Your ₹70 lakh goal</h1><p className="mt-3 text-slate-500">Login to save your goal and investments privately.</p><Link href="/login" className="mt-7 inline-flex w-full justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white"><LogIn size={18}/> Login / Sign up</Link><Link href="/" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/> Back</Link></section></main>;
 return <main className="min-h-screen bg-slate-50 px-3 py-4 text-slate-900 sm:px-6 sm:py-6"><div className="mx-auto max-w-6xl"><header className="mb-4 flex items-center justify-between rounded-2xl bg-white px-4 py-3 shadow-sm ring-1 ring-slate-200"><Link href="/" className="flex items-center gap-2 font-extrabold"><span className="grid size-9 place-items-center rounded-xl bg-violet-600 text-white">T</span>TargetBud</Link><div className="flex items-center gap-2"><span className="hidden max-w-48 truncate rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold text-slate-600 sm:block">{email}</span><button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold"><LogOut size={16}/> Logout</button></div></header>
 <section className="overflow-hidden rounded-[2rem] bg-white shadow-[0_20px_60px_rgba(15,23,42,.08)] ring-1 ring-slate-200"><div className="p-5 sm:p-7"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-5"><Ring value={progress}/><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">MY TARGET</p><h1 className="mt-1 text-3xl font-black sm:text-4xl">₹70 lakh</h1><p className="mt-1 text-sm text-slate-500">Your investments, growth and progress in one place.</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-violet-50 px-3 py-1.5 text-xs font-bold text-violet-700">{items.length} asset{items.length===1?"":"s"}</span>{stale>0&&<button onClick={()=>setModal("assets")} className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">{stale} matured</button>}</div></div></div><button onClick={()=>{setEditing(null);setForm(emptyForm());setModal("add")}} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3.5 font-bold text-white shadow-lg shadow-violet-200"><Plus size={19}/> Add investment</button></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Current value" value={money(current)} hint="Till today" icon={<WalletCards size={18}/>} onClick={()=>setModal("current")}/><Metric label="Interest / growth" value={money(earned)} hint="Earned till today" icon={<TrendingUp size={18}/>} onClick={()=>setModal("current")}/><Metric label="Remaining" value={money(remaining)} hint="To ₹70 lakh" icon={<TrendingUp size={18}/>} onClick={()=>setModal("remaining")}/><Metric label="Monthly addition" value={money(monthly)} hint="Monthly contributions" icon={<CircleDollarSign size={18}/>} onClick={()=>setModal("monthly")}/><Metric label="Est. completion" value={completion} hint="At current plan" icon={<CalendarDays size={18}/>} onClick={()=>setModal("monthly")}/></div><div className="mt-4 flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"><div><p className="text-sm font-bold">Principal {money(principal)}</p><p className="mt-1 text-xs text-slate-500">Growth earned till today {money(earned)}</p></div><button onClick={()=>setModal("assets")} className="inline-flex items-center gap-1 text-sm font-bold text-violet-600">View investments <ChevronRight size={17}/></button></div></div></section>
 {modal&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/20 p-3 backdrop-blur-sm sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><section className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[2rem] bg-white p-5 shadow-2xl ring-1 ring-slate-200 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-[.18em] text-violet-600">{modal==="add"?(editing?"EDIT INVESTMENT":"NEW INVESTMENT"):modal==="assets"?"YOUR ASSETS":"GOAL DETAILS"}</p><h2 className="mt-1 text-2xl font-black">{modal==="add"?(editing?"Edit investment":"Add investment"):modal==="current"?money(current):modal==="remaining"?`${money(remaining)} left`:modal==="monthly"?`${money(monthly)} / month`:"Your investments"}</h2></div><button onClick={()=>setModal(null)} className="grid size-10 place-items-center rounded-xl bg-slate-100"><X size={19}/></button></div>
 {modal==="add"&&<form onSubmit={save} className="mt-6 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Investment name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="tb-field" placeholder="HDFC FD"/></Field><Field label="Type"><select value={form.investment_type} onChange={e=>setForm({...form,investment_type:e.target.value})} className="tb-field">{TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Principal invested"><input required type="number" min="0" value={form.principal_amount} onChange={e=>setForm({...form,principal_amount:e.target.value})} className="tb-field" placeholder="600000"/></Field><Field label="Interest / growth rate"><input type="number" min="0" step="0.01" value={form.expected_rate} onChange={e=>setForm({...form,expected_rate:e.target.value})} className="tb-field" placeholder="2.50"/></Field><Field label="Rate period"><select value={form.rate_period} onChange={e=>setForm({...form,rate_period:e.target.value as FormState["rate_period"]})} className="tb-field">{RATE_PERIODS.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Return type"><select value={form.rate_type} onChange={e=>setForm({...form,rate_type:e.target.value as FormState["rate_type"]})} className="tb-field"><option>None</option><option>Fixed</option><option>Expected</option></select></Field></div>
 <div className="rounded-2xl bg-violet-50 p-4 ring-1 ring-violet-100"><div className="mb-3 flex items-center gap-2"><CalendarDays size={17} className="text-violet-600"/><div><p className="text-sm font-extrabold">Investment period</p><p className="text-xs text-slate-500">Enter how long from the start date — maturity is calculated automatically.</p></div></div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_1.2fr]"><Field label="Start date"><input required type="date" value={form.invested_on} onChange={e=>setForm({...form,invested_on:e.target.value})} className="tb-field bg-white"/></Field><Field label="Duration"><input type="number" min="1" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})} className="tb-field bg-white" placeholder="6"/></Field><Field label="Unit"><select value={form.duration_unit} onChange={e=>setForm({...form,duration_unit:e.target.value as DurationUnit})} className="tb-field bg-white"><option>Days</option><option>Months</option><option>Years</option></select></Field></div>{form.duration&&<div className="mt-3 rounded-xl bg-white px-3 py-2.5 text-sm font-bold ring-1 ring-violet-100">Matures on <span className="text-violet-700">{formatDate(addDuration(form.invested_on,form.duration,form.duration_unit))}</span></div>}</div>
 <div className="grid gap-4 sm:grid-cols-2"><Field label="Payment type"><select value={form.contribution_type} onChange={e=>setForm({...form,contribution_type:e.target.value as Investment["contribution_type"]})} className="tb-field"><option>Monthly</option><option>On maturity</option></select></Field><Field label={form.contribution_type==="Monthly"?"Monthly contribution":"Maturity contribution"}><input type="number" min="0" value={form.monthly_addition} onChange={e=>setForm({...form,monthly_addition:e.target.value})} className="tb-field"/></Field><Field label="Compounding"><select value={form.compounding} onChange={e=>setForm({...form,compounding:e.target.value as Investment["compounding"]})} className="tb-field">{COMPOUNDING.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Recorded current value (optional)"><input type="number" min="0" value={form.current_value} onChange={e=>setForm({...form,current_value:e.target.value})} className="tb-field"/></Field></div><div className="flex justify-end gap-2"><button type="button" onClick={()=>setModal(null)} className="rounded-xl border px-4 py-3 font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-violet-600 px-5 py-3 font-bold text-white">{saving?"Saving…":editing?"Save changes":"Add to goal"}</button></div></form>}
 {modal==="assets"&&<div className="mt-5 space-y-3">{calculated.map(({inv,calc})=><div key={inv.id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-extrabold">{inv.name}</h3><span className="rounded-full bg-white px-2 py-1 text-[11px] ring-1 ring-slate-200">{inv.investment_type}</span>{isStale(inv,today)&&<span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-bold text-amber-700">Matured</span>}</div><p className="mt-1 text-xs text-slate-500">{formatDate(inv.invested_on)} → {formatDate(inv.maturity_on)} · {inv.expected_rate}% / {inv.rate_period.toLowerCase()}</p></div><button onClick={()=>edit(inv)} className="inline-flex items-center gap-1 rounded-xl bg-white px-3 py-2 text-xs font-bold text-violet-600 ring-1 ring-slate-200"><Edit3 size={14}/> Edit</button></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Principal" value={money(inv.principal_amount)}/><Mini label="Current value" value={money(calc.value)}/><Mini label="Earned" value={money(calc.earned)}/><Mini label="Daily avg" value={money(calc.daily)}/></div><div className="mt-3 flex justify-between text-xs text-slate-500"><span>{calc.days} days · {inv.contribution_type}</span><button onClick={()=>remove(inv.id)} className="font-bold text-red-500">Delete</button></div></div>)}{!items.length&&<p className="rounded-2xl bg-slate-50 p-5 text-center text-sm text-slate-500">No investments yet. Add your first one.</p>}</div>}
 {modal==="current"&&<div className="mt-5 space-y-3">{calculated.map(({inv,calc})=><div key={inv.id} className="flex justify-between rounded-2xl bg-slate-50 p-4"><span className="font-bold">{inv.name}<small className="block mt-1 text-xs font-normal text-slate-500">Principal {money(inv.principal_amount)}</small></span><span className="text-right font-black">{money(calc.value)}<small className="block mt-1 text-xs font-bold text-emerald-600">+{money(calc.earned)} earned</small></span></div>)}<div className="rounded-2xl bg-violet-50 p-4"><p className="text-xs font-bold text-violet-700">TOTAL GROWTH EARNED</p><p className="mt-1 text-2xl font-black text-violet-800">{money(earned)}</p></div></div>}
 {modal==="remaining"&&<div className="mt-5 rounded-2xl bg-slate-50 p-5"><Row label="Target" value={money(TARGET)}/><Row label="Current value" value={money(current)}/><div className="my-4 border-t"/><Row label="Remaining" value={money(remaining)} strong/></div>}
 {modal==="monthly"&&<div className="mt-5 space-y-3">{items.filter(i=>i.contribution_type==="Monthly").map(i=><Row key={i.id} label={i.name} value={`${money(i.monthly_addition)} / month`}/>) }{monthly===0&&<p className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">No monthly contributions set.</p>}<div className="rounded-2xl bg-violet-50 p-4"><p className="text-xs font-bold text-violet-600">ESTIMATED COMPLETION</p><p className="mt-1 text-xl font-black text-violet-800">{completion}</p></div></div>}
 </section></div>}</div></main>}
function Metric({label,value,hint,icon,onClick}:{label:string;value:string;hint:string;icon:React.ReactNode;onClick:()=>void}){return <button onClick={onClick} className="rounded-2xl bg-white p-4 text-left ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-xs font-bold text-slate-400">{label}</p><span className="text-violet-500">{icon}</span></div><p className="mt-1 text-xl font-black tracking-tight">{value}</p><p className="mt-1 text-[11px] text-slate-400">{hint}</p></button>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200"><p className="text-[10px] font-bold text-slate-400">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className="flex items-center justify-between gap-3 py-1.5"><span className={strong?"font-bold":"text-slate-600"}>{label}</span><span className={strong?"text-lg font-black text-violet-700":"font-bold"}>{value}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span>{children}</label>}
