"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase-browser";

const regions=[['Arrival City',0,0],['Whisper Forest',-27,-9],['Iron Factory',27,-12],['Storm Mountain',22,25],['Underground',-24,25]] as const;
type Remote={root:any;target:{x:number;z:number};name:string};

export default function SkyfallWorld(){
 const canvas=useRef<HTMLCanvasElement>(null),keys=useRef(new Set<string>()),joy=useRef({x:0,y:0}),look=useRef({x:0,active:false,lastX:0}),jumpRef=useRef(false),remotes=useRef<Record<string,Remote>>({}),knob=useRef<HTMLDivElement>(null);
 const me=useRef<any>({id:Math.random().toString(36).slice(2),name:'Guest',x:0,z:0});
 const [region,setRegion]=useState('Arrival City'),[online,setOnline]=useState(1),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(false),[retry,setRetry]=useState(0),[fullscreen,setFullscreen]=useState(false);
 useEffect(()=>{
  const q=new URLSearchParams(location.search);me.current.name=q.get('name')||localStorage.getItem('skyfall-name')||'Guest';const room=(q.get('room')||'SKY-WORLD').toUpperCase();
  let e:any,ch:any,dead=false,script:HTMLScriptElement|null=null,timeout:number|undefined;
  const start=async()=>{try{
   setLoaded(false);setLoadError(false);
   if(!(window as any).BABYLON)await new Promise<void>((ok,no)=>{let settled=false;script=document.createElement('script');script.src='https://cdn.babylonjs.com/babylon.js';script.async=true;const fail=()=>{if(!settled){settled=true;window.clearTimeout(timeout);no(new Error('Babylon.js failed to load'))}};script.onload=()=>{if(!settled){settled=true;window.clearTimeout(timeout);ok()}};script.onerror=fail;document.head.appendChild(script);timeout=window.setTimeout(fail,15000)});if(dead)return;
   const B:any=(window as any).BABYLON,c=canvas.current;if(!c)throw new Error('Canvas unavailable');e=new B.Engine(c,true,{stencil:true,antialias:true});const s=new B.Scene(e);s.clearColor=new B.Color4(.48,.67,.82,1);s.fogMode=B.Scene.FOGMODE_EXP2;s.fogDensity=.006;s.fogColor=new B.Color3(.48,.67,.82);
   const cam=new B.UniversalCamera('cam',new B.Vector3(0,5,-10),s);cam.inputs.clear();cam.minZ=.1;cam.maxZ=180;
   new B.HemisphericLight('sky',new B.Vector3(0,1,0),s).intensity=.95;const sun=new B.DirectionalLight('sun',new B.Vector3(-.5,-1,.4),s);sun.intensity=1.7;
   const mat=(n:string,h:string)=>{const x=new B.StandardMaterial(n,s);x.diffuseColor=B.Color3.FromHexString(h);x.specularColor=new B.Color3(.12,.12,.12);return x};
   const grass=mat('Grass','#4f7b52'),road=mat('Road','#454b55'),water=mat('Water','#3b7891'),stone=mat('Stone','#747b83'),dark=mat('Dark','#30353b'),wood=mat('Wood','#76563d'),leaf=mat('Leaf','#356044'),roof=mat('Roof','#a24f3f'),gold=mat('Gold','#d5a72c'),skin=mat('Skin','#f1c27d'),shirt=mat('Shirt','#3e6fa8'),enemy=mat('OtherPlayer','#c96b5a');
   const box=(n:string,x:number,y:number,z:number,w:number,h:number,d:number,ma:any)=>{const p=B.MeshBuilder.CreateBox(n,{width:w,height:h,depth:d},s);p.position.set(x,y+h/2,z);p.material=ma;return p};
   const cyl=(n:string,x:number,y:number,z:number,d:number,h:number,ma:any)=>{const p=B.MeshBuilder.CreateCylinder(n,{diameter:d,height:h,tessellation:12},s);p.position.set(x,y+h/2,z);p.material=ma;return p};
   const floor=B.MeshBuilder.CreateGround('terrain',{width:100,height:100,subdivisions:2},s);floor.material=grass;const river=B.MeshBuilder.CreateGround('river',{width:9,height:100},s);river.position.x=11;river.position.y=.015;river.material=water;const path=B.MeshBuilder.CreateGround('road',{width:8,height:100},s);path.position.y=.03;path.material=road;
   const tree=(x:number,z:number)=>{cyl('trunk',x,0,z,.55,2,wood);const crown=B.MeshBuilder.CreateSphere('tree-crown',{diameter:3.3,segments:8},s);crown.position.set(x,3.1,z);crown.material=leaf};
   for(let i=0;i<22;i++){const a=i*2.4;tree(-31+Math.sin(a)*8,-11+Math.cos(a)*11)}for(let i=0;i<14;i++)tree(22+Math.sin(i*2.7)*9,26+Math.cos(i*2.7)*9);
   for(let i=0;i<7;i++){const x=-7+(i%4)*4,z=-6+Math.floor(i/4)*5;box('building',x,0,z,3,3+(i%3)*1.5,3,stone);box('roof',x,3+(i%3)*1.5,z,3.2,.35,3.2,roof);box('door',x,0,z-1.56,.8,1.5,.08,dark)}
   for(let i=0;i<8;i++){const x=22+(i%4)*4-6,z=-13+Math.floor(i/4)*6;box('factory',x,0,z,3.5,4,3,dark);cyl('chimney',x+1,4,z+1,.7,4,stone)}
   for(let i=0;i<9;i++){const a=i*.8;box('mount',22+Math.cos(a)*10,0,25+Math.sin(a)*9,2+(i%2),3+(i%3)*1.5,2+(i%2),stone)}for(let i=0;i<10;i++){const a=i*.63;box('ruin',-24+Math.cos(a)*9,0,25+Math.sin(a)*8,2,2+(i%3),2,stone)}
   for(let i=0;i<4;i++)box('light',-3+i*2,.2,-12,.18,2,.18,gold);const bridge=B.MeshBuilder.CreateBox('bridge',{width:4,height:.6,depth:20},s);bridge.position.set(11,.4,0);bridge.material=wood;
   const makeAvatar=(rootName:string,ma:any,x:number,z:number)=>{const root=B.MeshBuilder.CreateTransformNode(rootName,s);root.position.set(x,0,z);const body=B.MeshBuilder.CreateBox(rootName+'-body',{width:1.05,height:1.7,depth:.65},s);body.parent=root;body.position.y=1.15;body.material=ma;const head=B.MeshBuilder.CreateSphere(rootName+'-head',{diameter:1.05,segments:16},s);head.parent=root;head.position.y=2.45;head.material=skin;const leg1=B.MeshBuilder.CreateBox(rootName+'-leg1',{width:.36,height:.85,depth:.48},s);leg1.parent=root;leg1.position.set(-.27,.43,0);leg1.material=dark;const leg2=B.MeshBuilder.CreateBox(rootName+'-leg2',{width:.36,height:.85,depth:.48},s);leg2.parent=root;leg2.position.set(.27,.43,0);leg2.material=dark;return {root}};
   const local=makeAvatar('player',shirt,0,0),av=local.root;const shadow=B.MeshBuilder.CreateDisc('shadow',{radius:1,tessellation:24},s);shadow.rotation.x=Math.PI/2;shadow.position.y=.05;shadow.material=dark;
   const addRemote=(id:string,p:any)=>{if(id===me.current.id)return;if(!remotes.current[id]){const a=makeAvatar('remote-'+id,enemy,Number(p?.x)||0,Number(p?.z)||0);remotes.current[id]={...a,target:{x:Number(p?.x)||0,z:Number(p?.z)||0},name:String(p?.name||'Player')}}else{remotes.current[id].target={x:Number(p?.x)||0,z:Number(p?.z)||0};remotes.current[id].name=String(p?.name||remotes.current[id].name)}};
   const removeRemote=(id:string)=>{const r=remotes.current[id];if(r){r.root.getChildMeshes().forEach((m:any)=>m.dispose());r.root.dispose();delete remotes.current[id]}};
   const syncPresence=()=>{const state=ch?.presenceState?.()||{};const seen=new Set<string>();Object.entries(state).forEach(([id,v]:any)=>{const p=v?.[0];if(p){seen.add(id);addRemote(id,p)}});Object.keys(remotes.current).forEach(id=>{if(!seen.has(id))removeRemote(id)});setOnline(Math.min(100,Math.max(1,Object.keys(state).length)))};
   try{const sb=createClient();ch=sb.channel('skyfall-arena:'+room,{config:{presence:{key:me.current.id}}});ch.on('presence',{event:'sync'},syncPresence);ch.on('presence',{event:'join'},syncPresence);ch.on('presence',{event:'leave'},syncPresence);ch.on('broadcast',{event:'move'},({payload}:any)=>{if(payload?.id)addRemote(payload.id,payload)});ch.subscribe(async(st:string)=>{if(st==='SUBSCRIBED'){await ch.track(me.current);syncPresence()}})}catch{}
   let last=0,vy=0,camYaw=0,lastRegion='Arrival City';setLoaded(true);
   e.runRenderLoop(()=>{const dt=Math.min(e.getDeltaTime()/1000,.05);let x=joy.current.x,z=-joy.current.y;if(keys.current.has('w')||keys.current.has('arrowup'))z++;if(keys.current.has('s')||keys.current.has('arrowdown'))z--;if(keys.current.has('a')||keys.current.has('arrowleft'))x--;if(keys.current.has('d')||keys.current.has('arrowright'))x++;const l=Math.hypot(x,z)||1;av.position.x=Math.max(-47,Math.min(47,av.position.x+x/l*6*dt));av.position.z=Math.max(-47,Math.min(47,av.position.z+z/l*6*dt));
    if(jumpRef.current&&av.position.y<=.05){vy=6;jumpRef.current=false}vy-=16*dt;av.position.y=Math.max(0,av.position.y+vy*dt);shadow.position.x=av.position.x;shadow.position.z=av.position.z;me.current.x=av.position.x;me.current.z=av.position.z;
    let near:typeof regions[number]=regions[0],nd=Infinity;for(const r of regions){const d=Math.hypot(r[1]-av.position.x,r[2]-av.position.z);if(d<nd){nd=d;near=r}}if(near[0]!==lastRegion){lastRegion=near[0];setRegion(near[0])}
    Object.values(remotes.current).forEach(r=>{r.root.position.x+=(r.target.x-r.root.position.x)*Math.min(1,dt*12);r.root.position.z+=(r.target.z-r.root.position.z)*Math.min(1,dt*12)});
    if(ch&&Date.now()-last>120){last=Date.now();ch.send({type:'broadcast',event:'move',payload:me.current})}
    if(look.current.active)camYaw+=look.current.x*.004;const dist=9.5;cam.position.x+=(av.position.x-Math.sin(camYaw)*dist-cam.position.x)*.16;cam.position.z+=(av.position.z-Math.cos(camYaw)*dist-cam.position.z)*.16;cam.position.y+=(av.position.y+4.8-cam.position.y)*.16;cam.setTarget(new B.Vector3(av.position.x,av.position.y+1.25,av.position.z));s.render()});
   const kd=(x:KeyboardEvent)=>{keys.current.add(x.key.toLowerCase());if(x.key===' ')jumpRef.current=true},ku=(x:KeyboardEvent)=>keys.current.delete(x.key.toLowerCase()),rs=()=>e?.resize();addEventListener('keydown',kd);addEventListener('keyup',ku);addEventListener('resize',rs);
   return()=>{dead=true;window.clearTimeout(timeout);ch?.unsubscribe();Object.keys(remotes.current).forEach(removeRemote);e?.dispose();removeEventListener('keydown',kd);removeEventListener('keyup',ku);script?.remove()}
  }catch{if(!dead){setLoaded(false);setLoadError(true)}}};start();return()=>{dead=true}},[retry]);
 const setKnob=(ev:React.PointerEvent)=>{const el=ev.currentTarget as HTMLElement,r=el.getBoundingClientRect(),dx=ev.clientX-(r.left+r.width/2),dy=ev.clientY-(r.top+r.height/2),m=Math.min(r.width*.32,Math.hypot(dx,dy)),a=Math.atan2(dy,dx),nx=Math.cos(a)*m,ny=Math.sin(a)*m;joy.current={x:nx/(r.width*.32),y:ny/(r.width*.32)};if(knob.current)knob.current.style.transform=`translate(calc(-50% + ${nx}px),calc(-50% + ${ny}px))`};
 const joyStart=(ev:React.PointerEvent)=>{ev.stopPropagation();(ev.currentTarget as HTMLElement).setPointerCapture(ev.pointerId);setKnob(ev)};
 const joyMove=(ev:React.PointerEvent)=>{ev.stopPropagation();if(ev.buttons)setKnob(ev)};
 const joyEnd=(ev?:React.PointerEvent)=>{ev?.stopPropagation();joy.current={x:0,y:0};if(knob.current)knob.current.style.transform='translate(-50%,-50%)'};
 const jump=()=>{jumpRef.current=true};
 const lookStart=(ev:React.PointerEvent)=>{if((ev.target as HTMLElement).closest('[data-control]'))return;look.current={x:0,active:true,lastX:ev.clientX};(ev.currentTarget as HTMLElement).setPointerCapture(ev.pointerId)};
 const lookMove=(ev:React.PointerEvent)=>{if(!look.current.active)return;look.current.x=ev.clientX-look.current.lastX;look.current.lastX=ev.clientX};
 const lookEnd=()=>{look.current={x:0,active:false,lastX:0}};
 const toggleFullscreen=async()=>{try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();setFullscreen(true)}else{await document.exitFullscreen();setFullscreen(false)}}catch{}};
 return <main className="min-h-screen bg-[#0b1110] text-white"><div className="mx-auto max-w-7xl px-2 py-3 sm:px-3 sm:py-4"><header className="mb-2 flex items-center justify-between gap-2"><div><Link href="/games" className="text-xs text-white/60">← Games</Link><h1 className="mt-1 text-2xl font-black">Skyfall Arena</h1><p className="text-xs text-white/55">{region} · {me.current.name} · {loaded?'world ready':'loading world'}</p></div><div className="flex items-center gap-2"><div className="rounded-full border border-white/20 bg-black/30 px-3 py-2 text-xs">● {online}/100 online</div><button onClick={toggleFullscreen} className="rounded-full border border-white/20 bg-white/10 px-3 py-2 text-xs font-semibold backdrop-blur">{fullscreen?'Exit':'Fullscreen'}</button></div></header>
 <div className="relative overflow-hidden rounded-2xl border border-white/15 bg-[#79a6ba] shadow-2xl select-none touch-none"><canvas ref={canvas} aria-label="Skyfall Arena 3D multiplayer world" className="block h-[78vh] min-h-[500px] w-full" onPointerDown={lookStart} onPointerMove={lookMove} onPointerUp={lookEnd} onPointerCancel={lookEnd}/>{loadError&&<div className="absolute inset-0 grid place-items-center bg-black/35 p-6"><div className="max-w-sm rounded-2xl border border-white/20 bg-black/70 p-5 text-center backdrop-blur"><p className="text-sm font-bold">World failed to load</p><p className="mt-1 text-xs text-white/65">The 3D engine did not start. Retry without leaving the room.</p><button onClick={()=>setRetry(x=>x+1)} className="mt-4 rounded-full border border-white/30 bg-white/15 px-4 py-2 text-xs font-bold">Retry world</button></div></div>}
 <div className="pointer-events-none absolute left-3 top-3 rounded-xl border border-white/20 bg-black/45 px-3 py-2 text-[11px] backdrop-blur">{region} · {online>1?`${online-1} other player${online>2?'s':''} nearby`:'You are first in this world'}</div>
 <div className="pointer-events-none absolute right-3 top-3 rounded-xl border border-white/20 bg-black/40 px-3 py-2 text-[11px] text-white/75 backdrop-blur">Third-person · drag to look</div>
 <div className="pointer-events-none absolute bottom-3 left-3 rounded-xl border border-white/20 bg-black/45 px-3 py-2 text-[11px] text-white/80 backdrop-blur">Joystick · drag to look · jump · {online}/100 online</div>
 <div data-control className="absolute bottom-4 left-4 h-32 w-32 touch-none rounded-full border-2 border-white/35 bg-black/30 shadow-2xl backdrop-blur sm:h-36 sm:w-36" onPointerDown={joyStart} onPointerMove={joyMove} onPointerUp={joyEnd} onPointerCancel={joyEnd}><div className="pointer-events-none absolute inset-2 rounded-full border border-white/15"/><div ref={knob} className="pointer-events-none absolute left-1/2 top-1/2 size-14 -translate-x-1/2 -translate-y-1/2 rounded-full border border-white/60 bg-white/25 shadow-xl sm:size-16"/></div>
 <div data-control className="absolute bottom-4 right-4 flex items-end gap-3 touch-none"><button aria-label="Jump" onPointerDown={(e)=>{e.stopPropagation();jump()}} className="grid size-16 place-items-center rounded-full border-2 border-white/40 bg-black/45 text-2xl font-black shadow-2xl backdrop-blur active:scale-95 sm:size-20">↑</button></div>
 </div>
 <div className="mt-3 grid gap-2 grid-cols-2 sm:grid-cols-5">{regions.map(r=><div key={r[0]} className={`rounded-xl border p-3 ${region===r[0]?'border-white/30 bg-white/[.09]':'border-white/10 bg-white/[.04]'}`}><p className="text-[10px] uppercase tracking-widest text-white/45">Region</p><p className="mt-1 text-sm font-bold">{r[0]}</p></div>)}</div></div></main>;
}